### ISSUE TITLE
Sardine Ball not synthable

### ISSUE THREAD

**Issue by Deepupuu** [EdenServer/community#1296] opened 2019-03-16 03:21 UTC
It seems TOAU fish synths don't work, I've previously reported Istakoz not working for Peeled Lobster. Now I've also run across Hamsi not working for Sardine Ball, I'm starting to see a pattern here with TOAU fish alternate synths not working. Please look into it so I can start selling what I fish up in TOAU areas, thanks :D

**Comment by PrettyCoolPattern** [comment] 2020-04-23 17:15
I compiled a list of all the ToAU fish and began checking for synth entries and item id's.

I got about a quarter of the way done and found that the issue is definitely not ToAU related but isolate to the  Istakoz and Hamsi incidents. If you find anything else, definitely bring it up.

Here is the fix for Hamsi and coincidently 2 more recipe fixes that I spotted right next to Hamsi:

INSERT INTO `synth_recipes` VALUES (3177,0,0,0,0,0,11,0,0,0,0,4098,5449,0,0,0,0,0,0,0,0,17392,17392,17392,17392,2,2,2,2,'Sliced Sardine');
INSERT INTO `synth_recipes` VALUES (3178,0,0,0,0,0,11,0,0,0,0,4098,5449,=,0,0,0,0,0,0,0,17392,17392,17392,17392,2,2,2,2,'Sliced Sardine'); -- sliced sardine (cook 11) https://www.bg-wiki.com/bg/Sliced_Sardine
INSERT INTO `synth_recipes` VALUES (3179,0,0,0,0,0,13,0,0,0,0,4098,4240,4483,0,0,0,0,0,0,0,17393,17393,17393,17393,6,6,6,6,'Sliced Cod');
INSERT INTO `synth_recipes` VALUES (3180,0,0,0,0,0,7,0,0,0,0,4098,4383,0,0,0,0,0,0,0,0,17394,17394,17394,17394,1,1,1,1,'Peeled Lobster');

They all had item code 4240 in them which was cyclone crystal and not listed as a required mat on any reference sites.

Here is the fix for Istakoz which was simply missing the peeled crawfish entry. I assigned it its own unique incremental ID value in variable slot one `ID` as 4559 which was simply next on my synth_recipes.sql file (keep in mind, it may not be for yours):

INSERT INTO `synth_recipes` VALUES (4559,0,0,0,0,0,7,0,0,0,0,4098,4240,5453,0,0,0,0,0,0,0,17394,17394,17394,17394,1,1,1,1,'Peeled Lobster');


Here is my partially finished research list:
xx is cleared


Denizanasi xx
Hamsi erogenous code
Kalamar xx
Yilanbaligi xx
Kayabaligi xx
Sazanbaligi xx
Istakoz Fixed Peeled Lobster
Istiridye  xx
Mercanbaligi xx
Ahtapot (mistaken entry on https://ffxiclopedia.fandom.com/wiki/Ahtapot ? not an actualy blind potion craft ingredient) xx
Pterygotus xx
Alabaligi xx
Dark Bass
Turnabaligi
Caedarva Frog
Yayinbaligi
Kaplumbaga
Black Ghost
Blindfish	
Cave Cherax	
Lamp Marimo
Rhinochimera
Betta
Dil
Istavrit
Gurnard
Veydal Wrasse
Lakerda
Gugru Tuna
Noble Lady
Mola Mola
Gugrusaurus
Veydal Wrasse
Uskumru
Mola Mola
Gugrusaurus
Kalkanbaligi
Kilicbaligi
Uskumru

**Comment by mlandrum22** [comment] 2020-04-24 02:34
Istakotz should be able to make crayfish balls too.

**Comment by PrettyCoolPattern** [comment] 2020-04-24 03:08
> Istakotz should be able to make crayfish balls too.

https://ffxiclopedia.fandom.com/wiki/Istakoz
peeled crayfish wasn't listed on there but here's the insert for that:

INSERT INTO `synth_recipes` VALUES (4560,0,0,0,0,0,3,0,0,0,0,4098,5453,0,0,0,0,0,0,0,0,16993,16993,16993,16993,1,1,1,1,'Peeled Crayfish');

**Comment by 59blargedy** [comment] 2022-09-21 15:42
resolved in september 21, 2022 update

**Closed by 59blargedy** 2022-09-21 15:42 UTC
Labels: Crafting/Helm

**Comment by Tofutoshi** [comment] 2023-10-10 00:52
Unable to craft crayfish balls using Istatoz.

![Screenshot 2023-10-09 174606](https://github.com/EdenServer/community/assets/107894001/ef2df621-9ad1-401a-9d1b-c8fcf5aa7429)
![Screenshot 2023-10-09 174637](https://github.com/EdenServer/community/assets/107894001/e719b6ec-d61f-499b-835a-14fdf7cd1fa8)
![Screenshot 2023-10-09 174655](https://github.com/EdenServer/community/assets/107894001/427a28ec-745d-4243-8e28-8127282d2547)
![Screenshot 2023-10-09 174048](https://github.com/EdenServer/community/assets/107894001/6b71e9f7-cd47-404c-ba65-477b171218bb)
