### ISSUE TITLE
Invite bug when seeking party

### ISSUE THREAD

**Issue by Oneirowatts** [EdenServer/community#1366] opened 2019-03-22 07:09 UTC
When seeking for party and you get an invite in a different zone the invite party flag stays up.

**Comment by Volkaru** [comment] 2019-03-22 07:17
Duplicate of #1171 and #907

**Comment by godmode** [comment] 2019-03-22 11:35
For some reason the first one got closed so let’s leave this one opened although the fix is coming Sunday.

**Closed** 2019-05-08 00:36 UTC
