### ISSUE TITLE
"The Requiem" Bard AF Quest 

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#766] opened 2019-01-15 11:11 UTC
NMs are not spawning. I just checked the tomb and got the key item without having to do the fight. :(

**Comment by godmode** [comment] 2019-02-07 00:39
Duplicate of #224

**Comment by godmode** [comment] 2019-02-07 00:39
Had you ever helped someone do this fight before Serephim?

**Closed by godmode** 2019-02-07 00:39 UTC

**Comment by Serephim** [comment] 2019-02-07 06:41
> Had you ever helped someone do this fight before Serephim?

I've done it before for Voretechz's Bard but that was on Kupo.
