### ISSUE TITLE
Overlord Bakgodek (drop group issue)

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#242] opened 2018-10-28 00:32 UTC
https://ffxiclopedia.fandom.com/wiki/Overlord_Bakgodek

Either Highlander's Targe or Nightmare Sword drops, but never both; Nightmare Sword being the more common drop.

We got both drops.

**Comment by roriffxi** [comment] 2018-10-29 05:04
https://github.com/EdenServer/community/issues/175

Duplicate of this one? tho it looks like it may be inappropriately tagged as fixed in the original report

**Closed** 2018-10-30 01:57 UTC
Labels: fixed
