### ISSUE TITLE
cast bars

### ISSUE THREAD

**Issue by yueamyen** [EdenServer/community#446] opened 2018-12-09 23:08 UTC
cast bar completing long before spell is casted. Im low lvl so have only witnessed on stone and poison so far.

**Comment by godmode** [comment] 2018-12-10 00:10
Hi, thanks for reporting. This is actually part of another issue. We need things dat modded so they display correctly but the casting time is correct. Duplicate of #15

**Closed by godmode** 2018-12-10 00:10 UTC
