### ISSUE TITLE
Adventurer's Assistant (Adventurer's Coupon) missing dialogue (Can't trade)

### ISSUE THREAD

**Issue by xizeta** [EdenServer/community#1712] opened 2019-05-28 06:54 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30190430_0

Several of the Adventurer's Assistants are missing dialogue and I am unable to trade the Adventurer's Coupon.

Working correctly:
```
Jack of Clubs | Port Windurst D-6
Jack of Diamonds | Windurst Walls C-13
Jack of Hearts | Windurst Waters G-9
Jack of Spades | Windurst Woods H-10

Arva | Bastok Mines H-7
Dulsie | Port Bastok J-8
Reet | Bastok Markets G-7
```

Not working:
```
Quasim | Metalworks G-8

Bricorsant | Port San d'Oria H-8
Daveille | Northern San d'Oria D-8/9
Luthiaque | Southern San d'Oria G-9
```

**Comment by xizeta** [comment] 2019-05-28 10:00
SE completely removed these dialogue strings after they changed to the tutorial quest model. We have agreed a temporary workaround where these NPCs will accept the trade and grant the correct reward. But please be aware, they will not display any additional dialogue and this is expected behavior for now.

**Comment by 59blargedy** [comment] 2023-05-03 22:17
resolved in may 3, 2023 update

**Closed by 59blargedy** 2023-05-03 22:17 UTC
Labels: temp-fixed, needs-dat-mod

**Comment by KevinSShaffer** [comment] 2023-06-16 02:33
How was this resolved?  I just created a new Hume and Arva isn't accepting the coupon or giving dialogue options.  A friend of mine confirmed.

**Comment by 59blargedy** [comment] 2023-06-16 14:17
you'll want to talk to Reet in bastok markets to trade your coupon. will look at arva.

**Comment by KevinSShaffer** [comment] 2023-06-16 18:14
To be clear, the issue is either that Arva is broken or that he quest should send the player to Reet.
