### ISSUE TITLE
Haste cap is low for ToAU era

### ISSUE THREAD

**Issue by everlast101069** [EdenServer/community#2025] opened 2019-09-10 22:14 UTC
### Checklist
 

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x] I have provided my client version in the details. (type /ver into your game window)

### Details

Game ver: 30181205_0

After asking about the total haste cap a dsp site was referenced which based upon the code was listed as 80%.  The haste total wasn't capped and the max during ToAU era was 93.75% with all the equip 25.x, magic 43.x, and ja 25%. The update for haste reduction happened during the introduction of haste samba when dnc was around which was wotg era. 

https://www.bg-wiki.com/bg/Attack_Speed
https://www.bluegartr.com/threads/55473-Haste-Cap
https://www.ffxionline.com/forum/ffxi-game-related/general-ffxi-discussion/72840-haste-nerf

**Comment by Mozzy4Ever** [comment] 2019-09-17 04:22
For anyone wanting to verify: 

![image](https://user-images.githubusercontent.com/11255886/65011324-c750af00-d8d8-11e9-9672-c87de22792e3.png)


https://github.com/DarkstarProject/darkstar/blob/6b9f3d77eb2201b923160c50d13379d9f3b1ee8a/src/map/entities/battleentity.cpp

Line 243

**Comment by Mozzy4Ever** [comment] 2020-03-11 13:49
To update:
http://www.playonline.com/pcd/update/ff11us/20080311cPxl31/detail.html (March 11th, 2008): A maximum limit has been placed on the total amount of bonus attack speed that can be gained from a combination of spells, abilities, and items.

Looks like that update was what added the 80% max haste.

**Comment by Falaras** [comment] 2020-04-02 19:00
I guess this was never a bug and was a custom change not communicated.

**Comment by Falaras** [comment] 2020-05-15 14:55
Godmode mentioned to bug report this in his Q&A because he was unaware it was an issue, thought I'd add some more information. 

https://www.bg-wiki.com/bg/Version_Update_(03/11/2008) is when it was nerfed to 80% 

>A maximum limit has been placed on the total amount of bonus attack speed that can be gained from a combination of spells, abilities, and items.

This only really has any impact on Dark Knight's with Rune Chopper and Apocalypse but it severely hinders those weapons, if not outright kills Rune Choppers viability. 
The max Haste a non Drk can get is 43% Magic + 25% Gear + 10% JA from Hasso so they can't even reach the OOE 80% cap that Eden has. 
Drk gets access to Desperate Blows which allows them to gain 15% JA Haste for the 30 second duration of Last Resort which stacked with Hasso is 25% JA Haste. Which means Drk can get 43%+25%+25% with both Hasso and Desperate Blows stacking for around 93% Haste with a 2handed weapon only. 

The only thing this affects is the damage output Apocalypse and Rune Chopper can do in a zerg. Especially with Apocalypse being already a little too weak in my opinion, this makes it a way less appealing weapon than it should be in 2007 era FFXI.

**Comment by Relic3** [comment] 2020-05-15 15:45
This will also affect things like bahamuts zaghnal when Bahamut v2 comes out as this should be a formidable Zerg option as well if you don't have k club, m Kris, etc. Right now, 2h weapons on DRK are undertuned on Zerg fights because of this, and even after this fix, k club is still superior.

**Comment by VirtuosusFFXI** [comment] 2020-05-15 21:53
> The only thing this affects is the damage output Apocalypse and Rune Chopper can do in a zerg. Especially with Apocalypse being already a little too weak in my opinion, this makes it a way less appealing weapon than it should be in 2007 era FFXI.

This most likely affects DRG as well, at least on Eden. Looking through spirit_surge.lua on the DSP repository, Spirit Surge is giving 25% Job Ability haste. Spirit Surge wasn't changed to JA haste until 2012, so if Eden is using this then it is OOE.

**Comment by Falaras** [comment] 2020-05-15 23:03
Good catch I had no idea Spirit Surge was programmed like that. Either way I don't think it will have a huge impact on balance. I mainly put that in case someone thought this would buff Kraken Club zerging or something which could really throw game balance off.

**Comment by icariumkupo** [comment] 2020-05-16 02:42
Could we consider keeping Rune Chopper equipment haste but restore Apoc to it's former glory of having aftermath it's own haste category.

**Comment by Relic3** [comment] 2020-05-30 16:01
Was this fixed but forgot in the patch notes?

**Comment by bkesecker** [comment] 2020-05-30 17:17
> Was this fixed but forgot in the patch notes?

The code to enable and disable the haste cap was added.  Issue closed in error.  Reopening.

**Comment by slassen** [comment] 2020-05-30 20:42
For public information, when an issue is linked to a code change (called a PR, or pull request, in the developer world) and that code change is merged into the main branch—the issue is automatically closed. That’s what happened here.

**Comment by roriffxi** [comment] 2020-06-08 18:42
I did a lot of research and couldn't find anything to support Apoc aftermath or Rune Chopper being anything but gear haste.  Including the full math on achieving maximum haste in Bluegartr forms before the 80% delay reduction cap was implemented, where Apocs aftermath was explicitly counted as gear haste.

https://web.archive.org/web/20071213212002/https://tubbers.livejournal.com/7576.html
https://www.bluegartr.com/threads/52417-Yey!-Another-Haste-Topic!

The way the math works out is if you figure total delay reduction is 512 (meaning if you managed to get 512 delay reduction you'd have a delay of 0 and would instantly kill anything you engaged and got into range on)

So you get:
128 from equipment haste
224 from magic haste (haste spell, SV'd marches)
51 from hasso
75 from 3/3 desperate blows
=
478 / 512 = 93.3% delay reduction as the cap, only achieveable with Apoc / rune chopper due to it making it possible to cap equipment haste.  Which a Drk otherwise cannot do in-era.

If either of those weapons were untyped haste you'd be able to bring delay reduction 
110 (max gear haste w/o one of those 2 weapons)
224 magic
51 hasso
75 desp blows
51 or 46 (apoc vs rune chopper)

=
506 or 511 / 512
98.82 or 99.80% delay reduction which would be talked about if it were actually possible because the dmg dealt in that 30 seconds would probably solo AV by waiting for it to use mighty strikes and then have a Pld cover the drk with invincible up.

**Comment by Slamm21** [comment] 2020-06-08 19:41
it was the same as what became JA haste, which was likely still capped at 25%
the difference is you could have 20% JA haste 24/7 with it+ Hasso
to simplify without going into /1024 the max 22% of gear haste on DRK you could get
20% from marches
15% spell
20% JA haste
=77% haste 24/7
In a zerg it would be 90.75% as you would cap magic haste at 43.75%
Right now a RC War can do the same at 70% haste all day with little cost
cap gear haste at 25% (easy with RC)
20% marches
15% spell
10% JA from hasso

**Comment by everlast101069** [comment] 2020-06-08 19:56
Catastrophe before the JA was equipment. I had it. You capped JA haste with desperate blows 5/5.

"Slycer said:
Hello!

Thanks for all your responses regarding battle mechanics.
About Dark Knight
I have been reviewing discussion threads such as "Is Dark Knight too strong?" and I realize as I commented at Vana'fest that they have become stronger over time. At the same time, we put off many of the adjustments that were initially considered, but many people remembered these and were still interested.

For Dark Knight, we plan to make adjustments to Last Resort and Desperate Blows.

In the current situation, for all jobs, the equipment/magic haste maximum is the same. However, as far as abilities go, Desperate Blows is, by far, the highest value of all of them.

If we simply reduced the value of Desperate Blows then it would just become weaker, so, instead, we will reduce the value of Desperate Blows but also move some percentage of the haste effect to Last Resort:

Current status:
* Desperate Blows Haste maximum +25% (assuming 5 merits)
Adjustment:
* Desperate Blows: Haste maximum +10% (assuming 5 merits)
* Last Resort: Haste +15%

To clarify, we will make this adjustment so that the haste is effective even if you have your sub job set to Dark Knight.

Presently, it's difficult to imagine a situation in which someone would choose dark knight as a sub job. However, I think after this adjustment, a number of new possibilities will be opened up to allow it to be considered."

**Comment by Slamm21** [comment] 2020-06-08 20:01
The above is a 2013 update, not what we are discussing here.

**Comment by everlast101069** [comment] 2020-06-08 20:06
> The above is a 2013 update, not what we are discussing here.

Doesn't really matter. If the switch hasn't been flipped for it by now its going to be an OOE setting at 80%.

**Comment by Slamm21** [comment] 2020-06-08 20:15
I think the most important thing is can anyone find any proof of the aftermath being anything but equipment haste as that would be needed for any change to be considered. I've tried and come back with nothing.
Aside from that, I'd personally love to see the original haste cap.

**Comment by Falaras** [comment] 2020-06-08 21:49
Honestly I imagine for the most part many people would just be happy with Haste being uncapped again first and a separate ticket can be discussed about how to classify Apocalypse's haste.

**Comment by KnowOne134** [comment] 2020-11-11 02:38
haste cap removal has been coded and is toggleable in settings. if they want it on then so be it or can add it to the homepage that we are using capped haste version

**Closed by KnowOne134** 2020-11-11 02:38 UTC
