### ISSUE TITLE
The Savage

### ISSUE THREAD

**Issue by montijin** [EdenServer/community#1328] opened 2019-03-18 05:21 UTC
This fight feels really undertuned, my group killed it in almost under a minute. (I used 8 bullets total on the entire fight) Ouryu has less than 4500 HP while the wiki says it has 6k~

The spell damage was also really low
![8tG3XnK](https://user-images.githubusercontent.com/2160211/54508325-8cfb5a80-4913-11e9-9b1e-712b7fc07776.png)

**Comment by Strumerjohn** [comment] 2019-03-18 07:22
The only healing done was just two Regen II spells. I just stood there doing nothing for the rest of the minute.

**Comment by isotor** [comment] 2019-05-06 07:52
https://github.com/DarkstarProject/darkstar/pull/5951

**Comment by Slamm21** [comment] 2019-05-29 09:01
We did this today, I did not need to heal once and it was so weak I was attacking it as rdm after a while.
It also seemed to give up before 30%

**Comment by godmode** [comment] 2019-05-29 11:33
This issue will be addressed. Most likely players will be warped to the location to attempt the fight again that have already completed it. Additional CoP missions won’t be released until this issue is addressed. Thanks for reporting.

**Comment by EliannaEden** [comment] 2019-05-29 18:48
So, are we getting our progress rolled back? Most of us who have stayed current on CoP actually discussed this bug report with Monti in private and agreed. Not everyone who acknowledged the situation will have come here and posted. We've cleared 12-20~ people since then and Ouryu doing a bit more damage and having more hp wouldn't have stopped us from progressing past this. 

Lord of Onzozo didn't have counter until a few days ago, so is it time to roll back every club drop from Kupo to current Eden?

**Comment by godmode** [comment] 2019-05-29 18:57
No, wouldn’t be like that at all. It would be just redoing the battle. All progress would stay the same.

**Comment by godmode** [comment] 2019-05-29 18:59
There should be incentive to report bugs not hide in fear. So original reporters are usually exempt unless it’s a large issue.

**Comment by Slamm21** [comment] 2019-05-29 23:21
One thing I would like to add is my one attempt to sleep him failed. Granted my gear is fairly gimped for 50cap but I did have int+15 and a glamour jupon (enfeebling+3) equipped. Shiva's sleep did land.

It could have just been bad luck as magic hit rate can never be 100% but the common tactic on retail was:
Sleep > move to feet> fight > sleep if having issues. 
He would build up a sleep resistance quickly but you could usually get 2 or 3 sleeps in to help recover a bit since he hit pretty hard on retail.

Also, I do not remember if in era, but at some point, it was changed so you could have more than one mistmelt or trade them. right now they don't say rare/ex but you can't trade and if you try to get a 2nd you just lose both feathers and get nothing.

**Comment by EliannaEden** [comment] 2019-05-30 04:31
For more context, we ran this 2 weeks ago with WAR/BLM/BLM/WHM/RNG/RDM and damage wasn't as clear cut as some of these accounts make it. The WAR was BiS for LV50 and was eaten alive once shadows went down. Ouryu was hitting fast and hard, he went down in 5 melee hits even with 4 mages casting Cure II's and III's. Once it went up in the air we just cast benediction and followed the tried and true strategy of Elemental Seal + Freeze. 

We did not have any spells cast as we just sealed and silenced it during the initial pull. The air attacks were hitting my BLM for 120-180 depending on resists. Once it was in the air it only lived for 3 spell casts before the BCNM ended. Ouryu's HP was below 30% at this point due to a spell hitting at the last moment. 

I don't know if there is a variable in the BCNM that would account for this difference in damage people are experiencing. I can say that this most recent fight was more difficult than the fight we did a few days after the mission was released on Eden.

**Comment by godmode** [comment] 2019-05-30 09:57
Oh I see. So the only problem you can tell is his casting strength?

**Comment by Slamm21** [comment] 2019-05-30 14:18
Looking at the screenshot his physical strength seems about right where his magic damage is way too low. I assume they had barstonra which would help. Also, he seems to give up early? looked for us like 45% instead of at 30% which matches with the comment of 4.5k hp before he gave up instead of 6k.

I watched an old video here [](https://www.youtube.com/watch?v=O0SJLYTlonE) and at 6:26 you see a stonega II did 240 to their tank which would be 279 without shell 2. I don't believe mobs have the multiple targets penalty to spell damage players have.

Even at a full 1/16th resist it should still do 15 damage to anything except a rdm or whm (MDB job traits) and on a battle like this, you would not expect that to happen because of the level and int difference.

You can also see in the video how easy it was to sleep him. That elvaan rdm/blm would have needed int+20 to beat the magic hit rate of my gear as hume rdm/nin and much higher than that to sleep so many times like they did. Considering they had full RSE this is unlikely.

He also may have much low physical defence than he is supposed to have? as he died very quickly in both our experiences.

**Comment by EliannaEden** [comment] 2019-05-30 16:01
> Looking at the screenshot his physical strength seems about right where his magic damage is way too low. I assume they had barstonra which would help. Also, he seems to give up early? looked for us like 45% instead of at 30% which matches with the comment of 4.5k hp before he gave up instead of 6k.

At 1:13 the PLD is hit for 240 damage by the air attacks. His HP goes from 1008 > 768. 

At 1:30 the PLD is hit for 57 DMG. His HP goes from 768 > 711. 

At 2:57 the PLD is hit by Stonega II for 186 DMG. His HP goes from 1010 > 824.

At 2:59 the PLD is hit my a melee attack for 156 DMG. His HP goes from 824 > 668.
668 > 552 (Physical attack)
552 > 403 (Physical attack)

3:28 the PLD is hit by an air attack for 121 DMG. He went from 886 HP to 765.

4:57 the PLD is hit by a physical attack for 39 dmg. He went from 1010 > 971 HP. 
971 > 851 (Physical attack)

6:18 the PLD is hit by Stonega II for 186 dmg He went from 1010 to 824 HP.
824 > 584 (Air attack)
584 > 344 (Air attack)
534 > 294 (Air attack)
 
At 6:47 the PLD is hit by a physical attack for 212 dmg. He went from 832 to 620 HP.

From 6:50 > 7::26 I can't tell wtf is going on, too many spam heals and panic. 

At 8:36 the PLD is hit by a physical attack for 118 dmg. He went from 1010 HP to 892 HP.

At 9:11 the PLD is hit by an air attack for 230 dmg. He went from 883 to 653 HP. 

Are we watching the same video here guys? Also, yes mobs are subjected to the same magic penalty as when casting agas as player characters. Proof? Run Dynamis once or let a god in Sky cast on you individually or in a party. 

His damage in the video varies as widely as I've experienced on Eden. This fight in retail was a joke and I was part of the JP party who had first clear and was part of the first party to step foot in Sea on our server. What are you guys remembering?

**Comment by EliannaEden** [comment] 2019-05-30 21:16
4,500 HP was close. It was actually 5000. 

Our damage was as follows >

5
9
48
43
6
18
5
14
37
9
19
264
240
750
231
792
734
48
136
229
54
239
157
102
91
26
42
56
10
38
138
216
223
Total Damage Done: 5029

The indicator on Ouryu's HP definitively said 30% when the BCNM ended. I can't attest to damage but you can see by the logs he hits fairly hard and the ninja was barely able to keep shadows while it was on the ground. 

In flight, we were getting hit between 40-200+ damage depending on resists. 

This was all done on May 30th, 2019. 

![Elianna_2019 05 30_144401](https://user-images.githubusercontent.com/50064958/58665072-4fd91e80-82ed-11e9-995d-735c39644e7c.png)
![Elianna_2019 05 30_144408](https://user-images.githubusercontent.com/50064958/58665073-4fd91e80-82ed-11e9-8c5f-7b5872274368.png)
![Elianna_2019 05 30_144413](https://user-images.githubusercontent.com/50064958/58665075-4fd91e80-82ed-11e9-8f89-da0d7b68402b.png)
![Elianna_2019 05 30_144417](https://user-images.githubusercontent.com/50064958/58665077-4fd91e80-82ed-11e9-890b-87a7e0b87ec4.png)
![Elianna_2019 05 30_144421](https://user-images.githubusercontent.com/50064958/58665078-4fd91e80-82ed-11e9-9860-a02473567a2c.png)
![Elianna_2019 05 30_144427](https://user-images.githubusercontent.com/50064958/58665079-5071b500-82ed-11e9-8c92-8ce3ac2fed6e.png)
![Elianna_2019 05 30_144432](https://user-images.githubusercontent.com/50064958/58665080-5071b500-82ed-11e9-8776-6cb944a2d338.png)

**Comment by Slamm21** [comment] 2019-05-30 23:56
some nice numbers there for insight.
I cannot be 100% it was 45% because it happened so fast, it seems part of the issue was his defence being too low as 5k instead of 6k hp is not a huge difference but he did die far too quickly for us (about 2 mins).

The fight was always a joke, and anything that can be slept repeatedly like that will be even with a mismatched setup.
In our fight we had no proper tank, our tank was a drg/nin with 2 thieves using SATA+hide to keep him with hate on the right foot and while dual boxing one of those thieves I only got tp once to do that and terror stopped it anyway. The drg kept hate from damage alone and it died before I even had to cure. Yes it was weak on retail but nothing like that. Our damage was just the DRG, two thieves, shiva and a bst and me but by the time I realised how weak he was and went to attack it I only did 60 damage. 

He seems to be hitting about right for 200damage ish, and looking at the logs maybe he had a hard time keeping shadows because slow never landed and paralyze never seemed to proc? Our drg with just ichi never had an issue.

that is a better analysis of the video than I made, the 240 damage was, in fact, an aerial attack as he was casting that previous to being slept, my mistake. Just going over the nukes:

At 2:57 the PLD is hit by Stonega II for 186 DMG. His HP goes from 1010 > 824.
6:18 the PLD is hit by Stonega II for 186 dmg He went from 1010 to 824 HP.
That means without shell 2 it would have been 216 damage

You can work out Ouryus int from the 216 damage, which means since stonega 2 has a value of 201 that Ouryu has 15 more int than the galka. The galka has 32 int at level 50 as pld/war since he is unlikely to have any int in gear so Ouryu, therefore, must have 47 int. Even with shell 2 and a full 1/16th resist that should still do 10 damage to anything except a RDM or WHM.

**Comment by tacbox3** [comment] 2019-05-31 13:40
I think part of the issue here is better player knowledge and preparation. Yes he's gone down fast for most of us but this fight was always a DPS race. Having multiple BLM to freeze was an accepted strat on retail and seems to be a common theme among many of the groups in this thread on Eden.

The only thing that felt strange to me was that aggro was static once he was flying. I'm not sure if this was intended behavior, but our tank was getting absolutely crushed and he didn't lose aggro to the 2 BLM we had casting freeze.

Unfortunately I don't have screen grabs to back these comments up, but seeing as the comments are trending towards 'this was easy but not broken', I wanted to add my impressions.

**Comment by godmode** [comment] 2019-08-25 22:24
Thanks @isotor

**Closed** 2019-08-31 10:29 UTC
Labels: in-code-review
