### ISSUE TITLE
Bluestreak Gyugyuroon Drop Rate Bugged

### ISSUE THREAD

**Issue by itzalme** [EdenServer/community#2992] opened 2020-06-15 11:23 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
This NM really needs to have its drop rate looked at. We are currently 0/14 on anything dropping from this NM. I've looked at every forum and site even ones related to 2006. https://www.bluegartr.com/threads/48347-Bluestreak-Gyugyuroon
None of the sites seem to have the drop rate as low as it is for either item. 
Game Version : 30181205_0

**Comment by 59blargedy** [comment] 2020-06-24 21:26
duplicate of https://github.com/EdenServer/community/issues/2974.

**Closed by 59blargedy** 2020-06-24 21:26 UTC
