### ISSUE TITLE
Hitting a worm while it's going underground makes it untargetable

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1150] opened 2019-02-28 20:39 UTC
And it's still hitting you :(

**Comment by CloudyDesarroi** [comment] 2019-03-01 14:25
Not a permanent fix by any means, but if this happens to you again you may want to try "/attack <bt>". That's worked for me when fighting worms in Qufim.

**Comment by rpcon** [comment] 2019-06-24 20:53
This has happened to me about a dozen times, in both KRT and La Thiene. I will try using attack < bt > next time.

**Comment by Mahou81** [comment] 2019-07-25 11:54
Same here. /attack <bt> doesn't work that well either. Either you can only get in 1 hit and then automatically disengage, or you immediately disengage again without hitting it.

**Comment by godmode** [comment] 2019-08-24 13:05
Duplicate of #135

**Closed by godmode** 2019-08-24 13:05 UTC
