### ISSUE TITLE
player on threat list after logged out

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#450] opened 2018-12-10 02:18 UTC
if player A aggros a mob, player B hits the mob and then logs out, player A should not be on the threat list, but mobs still chase through the zone to player A

**Comment by beauxq** [comment] 2019-09-06 04:58
I'm wondering if there's a misunderstanding here.
The issue title is not describing what the original description is.
The problem is that player A is on the threat list when they shouldn't be. In the given scenario, player A never logged out. Only player B logged out.

**Comment by godmode** [comment] 2019-09-06 11:08
I’m unsure if that is how it worked in retail but I’m not 100%. Since there were no close notes though I’m going to open it again.

**Comment by KnowOne134** [comment] 2019-09-06 11:56
Understood issue wrong. Unsure if this is working as intended though

**Comment by beauxq** [comment] 2019-09-07 12:46
I remember pretty well that's how it worked in retail.
If you don't do anything to the mob, you shouldn't be on the threat list.
When an aggressive mob detects you, it should chase and attack you, but not put you on the threat list - until you do something to it.

**Comment by bkesecker** [comment] 2019-09-07 13:05
What about the situation that Player A aggroed, but did not claim, and then did something to Player B who had claim before player B disconnected/logged out (e.g. cure)?

**Comment by godmode** [comment] 2019-09-07 13:43
I don’t think that’s what is meant by this ticket.

**Comment by beauxq** [comment] 2019-09-07 14:08
bkesecker pointing out something that is unclear about my previous comment.

Yes, curing someone on the threat list should put you on the threat list.

The main point is: Detection from an aggressive mob should not put you on the threat list.

But that bring up a question in my mind that I'm not sure about:
Does a single attack with Trick Attack put you (the Trick Attack user) on the threat list?
That one I don't know.

**Comment by beauxq** [comment] 2019-09-20 14:50
Linking also should not put you on the threat list, just like aggro.

**Comment by KnowOne134** [comment] 2020-04-11 00:18
believe this was fixed few patched back?

**Comment by KnowOne134** [comment] 2020-05-14 19:51
Closing issue, can re open another issue if experience a problem since no feedback

**Closed by KnowOne134** 2020-05-14 19:51 UTC
