### ISSUE TITLE
Goblin Smithy dropping incorrect items

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2390] opened 2020-01-07 23:11 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Goblin Smithy drop Chainmails on Eden. This is not in their loot pool according to:
http://www.ffxidb.com/items/12552
http://www.ffxidb.com/zones/123/goblin-smithy

**Comment by xizeta** [comment] 2020-01-16 19:02
I farmed this in era. It's also on the wiki in 2007.
https://ffxiclopedia.fandom.com/wiki/Goblin_Smithy?oldid=345008

**Comment by ShiyoKozuki** [comment] 2020-01-19 01:02
Not all goblin smithies are supposed to drop chain armor, they currently do on Eden. The only recorded(500+ kills each, 8k for yugtunga jungle) of goblins dropping them on FFXIDB are listed here:
http://www.ffxidb.com/zones/157/goblin-smithy
http://www.ffxidb.com/zones/193/goblin-smithy
http://www.ffxidb.com/zones/198/goblin-smithy

Middle delkfutts, Ordelle's caves, and maze of shak. Also none of them are listed as dropping CHAINMAIL just the offpieces(legs, feet, gloves, helm).

Anyone can edit a wiki, ffxidb is factual data taken from the game.

**Comment by Dribblet** [comment] 2020-01-19 02:12
January 23, 2008, 2 page updates after the posted entry about chainmail being in-era, droprate reporting was added to ffxiclopedia.
https://ffxiclopedia.fandom.com/wiki/Goblin_Smithy?direction=next&oldid=425088

What this means is that players could report if they get an item from a monster they can self-report it by adding it to the database, and if you hover over the ??? or __%, it will show you an amount that shows x/x, to signify people that killed a mob and did/didn't get anything.

Case and point:
https://ffxiclopedia.fandom.com/wiki/Goblin_Smithy?oldid=1428501
March 9, 2013, Over 5 years since the droprate reporting was added to the wiki, results in 0/170 for Chainmail drops from Smithys in Yuhtunga. From this we can conclude that chainmails weren't removed via patch (If they were i'd like the see the patch in question), but were removed from the wiki after enough drops showed a 0% chance for the chainmail.

As far as potential in-era evidence, it's largely hearsay, however we can conclude from these pre-2007 posts:

- 2hours in jungle, no pieces of chain armor - https://ffxi.allakhazam.com/db/bestiary.html?fmob=388&p=2#m108618853223311
- Chain Hose from Delkfutt and Ordelle, no reports from Kazham - https://ffxi.allakhazam.com/db/item.html?fitem=605&p=2#m11267275401765
 - 150+ killed, says the 35-39 goblins drop chainmail set pieces, but never the body - https://ffxi.allakhazam.com/db/bestiary.html?fmob=388&p=1#m111265134527763
 - More reports of the chain hose drop, but never the body - https://ffxi.allakhazam.com/db/item.html?fitem=605&p=2#m11267275401765
 - Even the allakazham page for chainmail only lists Attowah Goblins as dropping it (A claim that also merits investigation)

There are reports of Chain Hose and other pieces of the chain armor set dropping from Smithys in Ordelle, Delkfutt, and elsewhere, but never any reports or evidence of the chainmail body dropping from any Goblin. The reason Chainmail itself is ever included is because people get it in their heads that if 1 piece drops, the other pieces like the body must also drop. 

Between the ffxiclopedia wiki never reporting any chainmail body drop in their reports, we can conclude that no monster drops this crafted piece of armor. You can also confirm this by the other pieces of crafter armor that drop from mobs:

- Lizard Jerkin set drops from orcs but the body is crafted only https://ffxiclopedia.fandom.com/wiki/Lizard_Jerkin?oldid=378411
 - Leather set drops from orcs and goblins, but the Vest is crafted only https://ffxiclopedia.fandom.com/wiki/Leather_Vest?oldid=390635
 - Cuir set pieces drop from 40+ beastmen mobs like goblins/yagudo, but the body is crafted only https://ffxiclopedia.fandom.com/wiki/Cuir_Bouilli?oldid=400196

Until there is provable evidence of a chainmail dropping on video or otherwise, it is very safe to say that next to no mob will drop the body piece of a crafted armor.

**Comment by Volkaru** [comment] 2020-01-24 23:31
Re-opening. The issue isn't that they aren't supposed to drop it or not. It's that only SOME in certain zones could drop it. However any smithy in any zone is currently dropping it.

**Comment by 59blargedy** [comment] 2021-11-29 16:41
resolved in November 29, 2021 update

**Closed by 59blargedy** 2021-11-29 16:41 UTC
