### ISSUE TITLE
KS99 Early Bird Catches the Wyrm flying issues

### ISSUE THREAD

**Issue by TracentEden** [EdenServer/community#4605] opened 2021-10-18 15:52 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Steps to Reproduce:

In KS99 Early Bird Catches the Wyrm, if the wyrm is brought from above 66% to below 33% very quickly (before the wyrm has a chance to go to the center and fly) by like big SC + MB, the wyrm behavior becomes unstable and it jumps up and down rapidly spamming touchdown, sometimes this behavior stops after many touchdowns (like 5+) but unclear what causes that to happen. 

Relatedly, if the wyrm is stunned when it is attempting to land (at or near 33%) the wyrm will stay in the air (which I assume is not intended behavior?).

**Comment by Mozzy4Ever** [comment] 2022-01-22 20:33
To add to this: Seems like now if you stun it right around when it's supposed to go back into ground phase, it'll stay in the air instead and the cluster will crash shortly thereafter
If you DD it too hard and it'll still do the touchdown spam from above, but also crash cluster afterwards.

Crashing could be due to the draw-in function? I believe in both instances nobody was getting drawn in but they should've been

**Comment by Mozzy4Ever** [comment] 2022-01-25 06:08
Followup: Confirmed via test server that the crash is due to the draw-in function. Built hate on 1 char who had GM on. Cast Fire with other char and ran 40' away. !clearenmity on "GM" char and zone crashed

**Comment by 59blargedy** [comment] 2022-07-08 13:09
resolved in July 8, 2022 update

**Closed by 59blargedy** 2022-07-08 13:09 UTC
Labels: BCNM
