### ISSUE TITLE
attohwa ginseng 

### ISSUE THREAD

**Issue by rathorse** [EdenServer/community#3538] opened 2020-12-28 11:14 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

item : attohwa ginseng  is not dropping from appropriate mobs for quest Tea with a tonberry?.  https://classicffxi.fandom.com/wiki/Tea_with_a_Tonberry%3F

**Comment by Shoruto** [comment] 2020-12-28 22:25
Duplicate of #3539

**Closed by Shoruto** 2020-12-28 22:25 UTC
Labels: Quest/Mission
