### ISSUE TITLE
Automaton WS Don't have SC properties.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1005] opened 2019-02-16 18:44 UTC
It seems this isn't just an issue with Inhibitor activating the WS too fast as detailed in #997 . I don't know about other WS. But Arcuballista doesn't make an SC no matter what I try. I've even manually deployed my auto so the timing would be better. But no SC yet. Talked with other PUPs and they've confirmed they've never seen their auto close an SC properly.

**Comment by jmcmorris** [comment] 2019-02-16 22:00
Duplicate of https://github.com/EdenServer/community/issues/997

**Closed by jmcmorris** 2019-02-16 22:00 UTC
