### ISSUE TITLE
Darters in Dragon's Aery need alliance-wide enmity

### ISSUE THREAD

**Issue by Goto28** [EdenServer/community#3423] opened 2020-11-17 18:38 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

A linkshell would have wiped to Nidhogg today were this properly functioning, I can imagine there would have probably been a number of wipes in the past too had this been working correctly. The Darter's of Dragon's Aery have alliance hate.

https://ffxiclopedia.fandom.com/wiki/Darter

**Comment by Shoruto** [comment] 2020-11-17 18:40
Duplicate of #1909

**Closed by Shoruto** 2020-11-17 18:40 UTC
