### ISSUE TITLE
Citipati (And other undead) are alive during the day.

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#421] opened 2018-12-06 23:19 UTC
Screenshot attached.  See time on the bottom of the screen. 

![image](https://user-images.githubusercontent.com/37130689/49617636-6a0bf280-f983-11e8-8432-f67c08d4ce2c.png)

**Comment by icariumkupo** [comment] 2018-12-07 00:59
Duplicate of #125

**Comment by godmode** [comment] 2019-02-16 22:01
Is this still happening?

**Comment by Aneyus** [comment] 2019-03-26 04:22
I believe this particular issue should be resolved.

**Closed** 2019-03-26 10:49 UTC
