### ISSUE TITLE
The Demons in Ule run at Flee speed

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#3390] opened 2020-10-30 21:54 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

I was running through Uleguerand Range and aggroed a couple Demons. I used Flee but they were running just as fast as I was and then I used Hide and they were not affected.

Edit: looks like they track by scent, so the Hide thing I think is ok? Not 100% sure on that part, but they were running as fast as I was. The BLM was able to cast on my a couple times while I was running at Flee speed.

**Comment by falzum** [comment] 2020-10-31 10:31
I've had this happen before too, once. One (Maybe more) of the demons there is miscategorized as true sight I believe. I tried to reproduce after I died so I could report exactly where it was but it must have despawned on me. Every time I do the enm I run infront of demons now hoping to narrow it down but it hasn't happened again to me, yet.

**Comment by Shoruto** [comment] 2020-10-31 14:04
Because the Kindred aggro to both Sight and Scent, using hide which greatly reduces the chance of getting aggroed by Sight would allow the Kindred to still aggro via Scent until you either went through water or had someone cast Deodorize on you when your out of the range.  The last part wouldn't be possible since you weren't able to get out of range.  So far I haven't found any era evidence to support or refute the moving at Flee speed.  Kindred is not on the list of monsters that have an innate speed increase.

**Comment by Mozzy4Ever** [comment] 2020-10-31 14:09
> Because the Kindred aggro to both Sight and Scent, using hide which greatly reduces the chance of getting aggroed by Sight would allow the Kindred to still aggro via Scent until you either went through water or had someone cast Deodorize on you when your out of the range. The last part wouldn't be possible since you weren't able to get out of range. So far I haven't found any era evidence to support or refute the moving at Flee speed. Kindred is not on the list of monsters that have an innate speed increase.

Tracking via Scent doesn't work on Eden because it's navmesh related. 
Bug report is a duplicate of https://github.com/EdenServer/community/issues/3146 though.

**Comment by Shoruto** [comment] 2020-10-31 14:21
Regarding the flee issue I did locate a source that states Demons have a trait of movement speed increase.  I brought it back to era date. Doesn't specify how much.  The ooe states 25% increase which still shouldn't keep up with flee (60%) https://ffxi.gamerescape.com/w/index.php?title=Category:Demons&oldid=142252

**Comment by falzum** [comment] 2020-10-31 14:21
Demons always moved at flee speed.

Source: meriting and being puller on high level demons back in the pre ToAU days. I can still hear my friends on ventrillo saying 'Holy shit demons got wheels'.

**Comment by Balrahn** [comment] 2020-10-31 15:31
I remember demons having flee speed from retail.

**Comment by KnowOne134** [comment] 2020-10-31 15:52
Can be checked on my npclogger github for mob speed it recorded

**Comment by KnowOne134** [comment] 2020-11-04 01:29
they run just slightly slower than flee speed, by the time flee wears off they would be right back on you in a sec or 2 also a dupe ticket

**Closed by KnowOne134** 2020-11-04 01:29 UTC
