### ISSUE TITLE
Memory Receptacle Empty Seed knocks back when absorbed by shadows

### ISSUE THREAD

**Issue by randomslumber** [EdenServer/community#5664] opened 2023-06-04 18:19 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Noticed today during sliver run that empty seed was causing knockback when absorbed by shadows. Not sure if that's intended. The OOE wiki says knockback is an additional effect of the attack??

**Comment by dowzer** [comment] 2023-06-04 19:44
https://youtu.be/wL9yN-dhDNE?t=213

That's working as intended

![emptyseed](https://github.com/EdenServer/community/assets/54732693/bb1b9b78-5bc5-4bbd-ae61-2963e26e4d9c)

**Comment by slassen** [comment] 2023-06-05 19:09
Closing this issue since it behaved this way in era retail.

**Closed by slassen** 2023-06-05 19:09 UTC
