### ISSUE TITLE
Additional Effects on weapons missing or not implemented properly

### ISSUE THREAD

**Issue by SBC-Nyxai** [EdenServer/community#1487] opened 2019-04-07 00:10 UTC
I've been using a Stun Kukri and Bloody Blade for some time now across a range of different mob difficulties (too weak to VT). Neither of these weapons have ever proc'd their additional effect. When a bloody bolt proc's even for 0 hit points there is still an animation and a text message saying it did so. Bloody Blade has never given an animation or text for any HP drain. Additionally, the Stun Kukri has simply never proc'd. I know some lower level added fire damage procs do work but seeing as these two weapons have never worked for me I'm concerned that some of the higher level added effect weapons do not work at all.

**Comment by Tjonke** [comment] 2019-04-08 00:12
It's the same for ALL the elemental staves, they just don't have an additional dmg effect procc.

**Comment by gweivyth** [comment] 2019-04-08 12:17
Holy Lance and Webcutter also fall under this, #1283

**Comment by greyenvy** [comment] 2019-04-08 13:47
I have never seen any of the Great Axe additional effects proc (Plantbane's fire dmg, Raifu's lightning dmg) but I have seen katana added effects proc, specifically Busuto +1's poison.  It wasn't often but I got a few in Zitah the other day on NIN.  That might help with tracking down code I guess.

**Comment by AnkleAssassinz** [comment] 2019-04-08 14:37
There are weapons additional effect that do work as intended:
-Also Confirmed Busuto's poison effect works.
- Garuda's dagger silence effect also works as intended. It seems to processed more often on too weak mobs and less on xp-giving mobs; as expected. 
- Cruel Spear(lvl 20: Additional effect Impairs Evasion) also works. Not tested Cruel Scythe.

**Comment by gweivyth** [comment] 2019-04-08 14:58
Since we are compiling a list of added effects, Yoto +1 works as intended, although the proc rate seems embarrassingly low.  (Not the 5%~ advertised on Wiki.)

**Comment by Volkaru** [comment] 2019-04-08 18:20
Hellfire Axe works, albeit rarely.

**Comment by DrfistMD** [comment] 2019-04-08 19:36
Dark Mezraq works, albeit like the others seems fairly low.

**Comment by Lan-var** [comment] 2019-04-24 18:43
Dainslaif also doesn't work sadly.

**Comment by Lan-var** [comment] 2019-04-26 18:03
Wing Sword doesn't work either.

**Comment by AkumoBunni** [comment] 2019-05-21 19:41
Is there any plan to have this working? Had a bloody blade made and a bit disappointed it doesn't work..

**Comment by Volkaru** [comment] 2019-05-21 21:12
Someone is currently working on them, yes. It's a lot to do. They have to pretty much code for every single weapon.

**Comment by gweivyth** [comment] 2019-05-23 13:59
> Is there any plan to have this working? Had a bloody blade made and a bit disappointed it doesn't work..

I've completely finished coding all of the added effect weapons up to level 75, I just need to finish data gathering proc rates/damage rates on retail, which has been taking some time.

**Comment by bkesecker** [comment] 2019-05-23 14:03
I am presently reviewing a pull request that partially resolves some of these.

**Comment by gweivyth** [comment] 2019-05-24 19:19
> I am presently reviewing a pull request that partially resolves some of these.

I'm about 80% done with data gathering if you just want to wait a few days.  I'm going on vacation the last week of the month and plan on finishing this project while I'm on the beach drinking Corona.  

For anyone who is curious, I've found that weapon added effects have a pretty static formula that they all use.  It appears that their ranges are actually relative to their weapon damage, and all weapons had static rates at which they proc.  (Unless otherwise noted on things like Ifrit's Blade, Shiva's Shotel, etc.)

Pretty cool findings so far.

**Comment by andimandi1** [comment] 2019-06-25 20:54
Hi there, just tried Bloody Blade and additional effect still doesn't seem to work. Have you already had time to implement the updates? Thanks

**Comment by bkesecker** [comment] 2019-06-27 11:35
> Hi there, just tried Bloody Blade and additional effect still doesn't seem to work. Have you already had time to implement the updates? Thanks

When this, and some other GitHub issues become closed, these would be fixed live after about a week of being closed.  The order is roughly: issue created > staff research  > prioritized > assigned > researched > coded > local testing > pull request > review > adjust > merge > build > deploy > smoke test > live.  This cycle can take a long time.

**Comment by andimandi1** [comment] 2019-06-27 12:37
Appreciate the update BK. Hadn't seen any more comments for the past month so was curious where it stands.

**Comment by gweivyth** [comment] 2019-06-28 18:50
I have all of these completely written and I even tested most of them against retail values and have them corrected, but I got banned so I'm not going to waste any more time testing the values.  If someone else wants them they can reach out to me and I'll share what I've got.

**Comment by bkesecker** [comment] 2019-06-29 00:11
> I have all of these completely written and I even tested most of them against retail values and have them corrected, but I got banned so I'm not going to waste any more time testing the values.  If someone else wants them they can reach out to me and I'll share what I've got.

Thank you for the heads up Gweivyth.  If you still want to share your data, let me know via Discord, name is Cygon.

**Comment by Volkaru** [comment] 2020-01-22 11:51
Suggesting to link all reports on broken additional effects to this bug report. And not close it until every single one is fixed. There are still many out there that aren't functioning.

**Comment by ShiyoKozuki** [comment] 2020-01-22 14:50
Sacrifice torque latent doesn't work
https://www.bg-wiki.com/bg/Sacrifice_Torque

**Comment by Slamm21** [comment] 2020-01-22 21:55
Tred Scythe doesn't work, should be best scythe right now outside of apoc
(https://github.com/EdenServer/community/issues/2296)

**Comment by gweivyth** [comment] 2020-01-24 16:55
> Tred Scythe doesn't work, should be best scythe right now outside of apoc
> (#2296)

I'll look into this one tonight. I probably missed it on my big batch of weapons cause it doesn't have a listed hidden effect.

**Comment by gweivyth** [comment] 2020-01-24 18:22
#2441 has lua pasted into ticket that should fix it.

**Comment by gweivyth** [comment] 2020-01-24 18:42
Also did #931 on its respective ticket as well.  That one may need extra code review, I didn't have the chance to run it thru a live server test.

**Comment by gweivyth** [comment] 2020-01-24 18:45
Also added #2309

**Comment by gweivyth** [comment] 2020-01-24 19:16
#1955 added.

**Comment by KnowOne134** [comment] 2020-07-08 00:53
believe we have added all, make new tickets for any that are not working

**Closed by KnowOne134** 2020-07-08 00:53 UTC
Labels: in-code-review
