### ISSUE TITLE
Batallia Downs hill issue 

### ISSUE THREAD

**Issue by charley222** [EdenServer/community#1119] opened 2019-02-23 18:36 UTC
i find a lot of bug in Batallia Downs    
monster run in the background inside the little hill   also agro   sometime you just can not hit them  also sometime they are stuck there  , i`m going to add more video to identify this issue 
https://www.youtube.com/watch?v=2b0GarnPM9I

i hope this will help thank you

**Comment by Aneyus** [comment] 2019-02-24 01:51
This is a longstanding issue in DSP with monsters on uneven terrain. It's particularly noticeable with ranged/caster mobs because they do not attempt to close the 'gap' between you and just stay in their unreachable spot. 
The best way to deal with this for now is to try to pull the mob to a new spot if you have to fight it, and wait for the navmesh overhaul to eventually fix this and other similar issues.

**Comment by godmode** [comment] 2019-02-24 13:27
Duplicate of #1105

**Closed by godmode** 2019-02-24 13:27 UTC
