### ISSUE TITLE
Give a Moogle a Break - Still Nothing

### ISSUE THREAD

**Issue by Siushaga** [EdenServer/community#642] opened 2019-01-01 16:05 UTC
I'm still not able to trigger the Bronze bed furniture quest in my Mog House. I've had a bed placed for probably 6 weeks by now. As more and more patch notes have popped up stating that the quest not trigger is fixed, I've tried placing the bed again in case it had to be freshly placed after the changes, but still not getting anything. Bronze Bed is stored in Mog Safe 1 and placed via the layout feature. Even get a KI for Moghancement: Experience. I've also tried going multiple weeks without touching it. 

Checked my city reputation with checker NPC in town, as well as with Eden website.
Checker NPC has me at rank 8:
<Name>! People are talking about you! Every infant in his cradle knows your name! And they hold you in highest regard! I am so proud of you! May your kind deeds continue!

Website player search has me at rank 6:
http://www.edenxi.com/db/characters/26880/Siushaga

So either way I should have enough reputation. Any ideas what I might be doing wrong?

**Comment by godmode** [comment] 2019-01-01 16:08
Duplicate of #371 Even though it's closed we still see follow ups. Will look into it for you.

**Closed by godmode** 2019-01-01 16:08 UTC
