### ISSUE TITLE
BST has out of era ability "Ready"

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#921] opened 2019-02-07 11:23 UTC

**Comment by icariumkupo** [comment] 2019-02-07 14:27
#380

**Comment by rujind** [comment] 2019-02-07 14:38
Ah TY, I did see that thread but only read the first post. I'm hoping staff actually did some testing to see if this ability should be kept in or not. Seeing BST pets use 3 WS every mob seems OP, but would have to see an actual parse.

**Comment by godmode** [comment] 2019-02-07 16:17
Duplicate of #380

**Closed by godmode** 2019-02-07 16:17 UTC
