### ISSUE TITLE
An Explorer's Footsteps bugged

### ISSUE THREAD

**Issue by yokhai** [EdenServer/community#909] opened 2019-02-04 19:56 UTC
The quest "An Explorer's Footsteps" will not drop from my quest list when i turn the clay tablet to Abelard so he constantly talks about the quest, blocking me on any other quest he is apart of, meaning I cannot progress through "Signed in Blood". Was told this was a known issue and a GM needs to manually remove the "An Explorer's Footsteps" quest flag.

**Comment by godmode** [comment] 2019-02-07 00:32
Duplicate of #858

**Closed by godmode** 2019-02-07 00:32 UTC
