### ISSUE TITLE
Crimson-toothed Pawberry fight mechanics 

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#4397] opened 2021-06-30 13:11 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Crimson-toothed_Pawberry

A retail capture might be necessary for some aspects but here are the differences I see on the wiki vs. fighting him:

1) He should only use Carbuncle, currently he summons a random avatar.
2) He should use astral "multiple times" and the wiki references him using it below 25% for "more damage". Currently He 2 hours at the start (correct) and then around 50%, but never again.
3) Sleep/Silence resistance? Not sure, I sleep him fine occasionally but its not usually necessary.
4) There is a wiki testimonial for 912 damage to a 75 THF from Searing Light. The same THF took 800+ from another one. Other people reference 200ish, so I'm not sure if resists are at play or what, but I never see big numbers like that when I fight it.

**Comment by 59blargedy** [comment] 2021-08-02 16:11
resolved in august 2nd mini-update. 
because of the level of the avatar, a damage value that high for searing light is impossible, and im honestly unsure what that thf was talking about, could find no era vids that seemed to match, and confirmed avatar level on retail.

**Closed by 59blargedy** 2021-08-02 16:11 UTC
