### ISSUE TITLE
Critical hits aren't correct

### ISSUE THREAD

**Issue by DistantClose** [EdenServer/community#45] opened 2018-10-03 17:11 UTC
On my Warrior my melee swings fully buffed with Berserkers axe avg 280-300 
When a crit procs I do 270

**Comment by Lilswitche** [comment] 2018-10-03 17:19
What mob were you targetting? I noticed funky stuff last night when I was leveling sam - namely Minuet IV giving me very little extra damage on top of my base damage.  I'm not sure, but damage calculation altogether may need to be looked at.

**Comment by beauxq** [comment] 2018-10-03 20:21
https://github.com/EdenServer/community/issues/47

We posted at about the same time.

**Comment by godmode** [comment] 2018-10-20 18:18
Duplicate of #47

**Closed by godmode** 2018-10-20 18:18 UTC
