### ISSUE TITLE
I believe BST has inaccurate axe skill

### ISSUE THREAD

**Issue by ZaksHouse** [EdenServer/community#857] opened 2019-01-26 20:22 UTC
I am currently level 23 and noticed I didn't receive the weapon skill "Gale Axe" BST should unlock it at level 23 along with WAR. I capped axe out at skill level 69 at level BST23.  I even went through old data on the wiki in around August 2007 showing BST still obtained it back then. It's not a big deal on that WS since I probably wont use it but gives BST lower skill on his best weapon.

**Comment by godmode** [comment] 2019-01-26 20:55
Did you zone and check again in case of a bug?

**Comment by rujind** [comment] 2019-01-26 21:04
Re-equipping weapons can fix bugs like this also.

**Comment by ZaksHouse** [comment] 2019-01-27 00:40
I will try when I log back in later tonight and let you know of the results away from game currently.

**Comment by ZaksHouse** [comment] 2019-01-27 02:09
Once I logged in its no longer capped at blue I can skill up some more thanks for that I will remember that to take off weapon and such.

**Comment by godmode** [comment] 2019-01-28 01:10
Duplicate of #56

**Closed by godmode** 2019-01-28 01:10 UTC
