### ISSUE TITLE
Ready isn't working

### ISSUE THREAD

**Issue by mlandrum22** [EdenServer/community#2106] opened 2019-10-08 00:24 UTC
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Using PanzerGalahad in Dynamis and I don't have any Ready commands.

In the menu there is Ready, just no moves to select. Doesn't appear macroing in the moves works either.

I can't use Sic with her out either.

**Comment by trodeghero** [comment] 2019-10-08 00:30
Similar with FunguarFamiliar. As 75 BST I summoned one and it had ready moves except for dark spore and silence gas.  When I tried to use frogkick I got R0, not sure if it's connected.

**Comment by mlandrum22** [comment] 2019-10-08 23:45
Many pets are missing Ready moves, but not all of them or all of the moves. For instance, the Antlion has all his moves, but the Diremite is missing Spinning Top and Grapple but has his other 2 moves.

**Comment by Volkaru** [comment] 2019-10-08 23:45
Many reports in-game and on discord of certain moves causing an R0.

**Comment by KnowOne134** [comment] 2019-11-03 06:17
No more reports except for that 1 day after update correct?

**Comment by mlandrum22** [comment] 2019-11-03 06:18
No, the ready moves are still missing from a number of pets.

**Comment by KnowOne134** [comment] 2019-11-03 06:20
Seems more people would have chimed in on this except for the 1st day. Would need a list of moves that aren't working

**Comment by mlandrum22** [comment] 2019-11-03 14:38
Well we’re told not to “bump” git tickets unless we have new info. I checked the beetle and diremite again after the previous update and they were still missing their moves. I talked about it in discord but didn’t re-report here.

I can check the other pets I have once eden is working again.

**Comment by godmode** [comment] 2019-11-03 16:01
If anyone else is having the same problems they can thumbs up the ticket or chime in as well. I’m nervous that it may be a corrupt dat or something of that nature. Are all BST that you know missing the same commands?

**Comment by mlandrum22** [comment] 2019-11-03 16:36
Most other BSTs only use the crab and they're working fine. Like I'm pretty sure I'm the only person on the server to ever use a beetle.

I can confirm, though, that the Diremite was missing Spinning Top on another player (Gameover).

I didn't check the low level pets (hare/sheep/fly/tiger/lizard) since they don't cap at 75, and I ran out of flytraps so I haven't tested that one.

**Comment by Wade9363** [comment] 2019-11-03 16:41
I have the mats to make a few stacks of Diremite.  When the server is back up I'll work with Azmanz to test

**Comment by trodeghero** [comment] 2019-11-03 17:09
FunguarFamiliar is still missing dark spore and silence gas. That's all I know for sure

**Comment by MB213** [comment] 2019-11-03 21:39
Oh this is new...
I've used every era pet except for the Sabotender and none were missing any moves, but I mostly stopped playing BST close to a year ago. I'll test and see if I have the same issues on my client when the server is back up (I'm still using a pretty old client). After that I'll install the new client and see what happens.

**Comment by KnowOne134** [comment] 2019-11-03 21:47
Tested on test server. Even reverted code to add the antilion moves. Issue
still persists. It's not that they aren't usable. The list is strait empty
on ready menu

**Comment by Wade9363** [comment] 2019-11-05 06:32
Initial Testing:  I will update this as I get more of these done.

**Missing or Broken TP moves:**

- Hare Familiar - Wild Carrot
- Amigo Sabotender - Both TP moves listed: However, ??? Needles does not result in a TP move and does consume 3 Ready charges
- Panzer Galhad - Power Attack, High Frequency Field, Rhino Attack, Rhino Guard, Spoil
- Shellbuster Orob - Cursed Sphere
- Funguar Familiar - Shakeshroom, Silence Gas, Dark Spore

**Appears to be Working as Intended:**

- Ambusher Allie
- Chopsuey Chucky
- Homunculus
- Saber Siravarde
- Coldblood Como
- Sheep Familiar
- Voracious Audrey
- Flowerpot Ben

**Have not yet tested:**
Keeneared Steffi
Lullaby Melodia
Flowerpot Bill
Tiger Familiar
Flytrap Familiar
Lizard Familiar
Mayfly Familiar
Eft Familiar
Beetle Familiar
Antlion Familiar
Crab Familiar
Courier Carrie
Mite Familiar

**Comment by mlandrum22** [comment] 2019-11-05 15:21
Thanks Wade.

I believe the NQ and HQ share the same move errors, for instance both Lars and Diremite Familiar are missing Grapple and Spinning Top. So I don't think we have to check any the ones you listed, I think you got them all except for the Crabs, which have all their moves.

Also: Wild Carrot was added to Hares later, they shouldn't have that here.

**Comment by mlandrum22** [comment] 2019-12-20 17:34
Pulled out a Diremite last night, still broken.

**Comment by mlandrum22** [comment] 2020-03-25 00:44
Diremite still missing AoE. LifeDrinker Lars stuck somewhere without food :(

**Comment by statuseffect** [comment] 2020-04-10 21:35
BeetleFamiliar missinf Ready commands

**Comment by statuseffect** [comment] 2020-04-10 21:38
Also Homunculus and FlowerpotBen are EXTREMELY weak. Can barely hit the mob and all attacks/TP moves hit for 1 dmg.

**Comment by 59blargedy** [comment] 2020-12-21 16:10
resolved in December 21, 2020 patch

**Closed by 59blargedy** 2020-12-21 16:10 UTC
