### ISSUE TITLE
Greater Pugils not spawning in Korroloko Tunnel

### ISSUE THREAD

**Issue by boxofrain1** [EdenServer/community#2519] opened 2020-03-11 10:27 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
On the same map as the spider room where the webcutter nm spawns, e,f, and g-9. all internet sources mention greater pugils spawn but there are zero.

**Comment by FariskaEden** [comment] 2020-03-15 00:36
Duplicate of https://github.com/EdenServer/community/issues/2459

**Comment by 59blargedy** [comment] 2020-09-20 18:50
resolved september 20 update

**Closed by 59blargedy** 2020-09-20 18:50 UTC
