### ISSUE TITLE
Sea Serpent Grotto Sahagins

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#1123] opened 2019-02-24 13:06 UTC
There are maybe a dozen Sahagins that get caught up with doors or walls if they're zoned into Norg.  There are a few stuck at the stairs next to Masan camp, and a few stuck at a wall behind the door to Norg.

**Comment by godmode** [comment] 2019-02-24 13:27
Duplicate of #1105

**Closed by godmode** 2019-02-24 13:27 UTC
