### ISSUE TITLE
Aggro bugs in Temple of Uggalepih

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#457] opened 2018-12-10 11:13 UTC
Couple days ago I was killed in the Temple of Uggalepih by Tonberry mobs aggroing, linking and casting through walls/doors outside the door to the room at (J-9) on map 3. Multiple mobs linked and cast spells on me with no path to me or line of sight. 

When this happened, I was raised by a party member who still had aggro. I raised, and the one mob that was actually in the same room as me immediately chased me down and killed me again despite being well out of aggro range, i.e. it was obvious I never lost threat despite dying.

**Comment by beauxq** [comment] 2018-12-10 13:14
looks like maybe this was not fixed when it said it was:

https://github.com/EdenServer/community/issues/365

**Comment by godmode** [comment] 2019-02-16 20:47
Duplicate of #530

**Closed by godmode** 2019-02-16 20:47 UTC
