### ISSUE TITLE
BST Charmed Pets constantly getting stuck. Very difficult to level BST as a result

### ISSUE THREAD

**Issue by TakEden** [EdenServer/community#602] opened 2018-12-28 00:51 UTC
The monster I have charmed will constantly get stuck on things. If I don't go all the way back to where it is stuck, or run far enough that the pet instantly teleports to me, it will not move.

This honestly makes leveling BST feel quite awful, would love a fix on this :(

Edit: 

Also when a pet is "Petrified" it can still move around, but can't do anything until it wears off. Strange interaction/bug.

**Comment by ZaksHouse** [comment] 2019-02-05 19:45
Is there any time frame on this fix?

**Comment by godmode** [comment] 2019-02-05 21:41
No, it has a long term development label on it. It will likely be awhile before it’s fixed

**Comment by godmode** [comment] 2019-02-16 21:18
Duplicate of #438

**Closed by godmode** 2019-02-16 21:18 UTC
Labels: Long Term Development
