### ISSUE TITLE
Black Mage Spell List/Cast Time

### ISSUE THREAD

**Issue by SairielXI** [EdenServer/community#302] opened 2018-11-09 15:53 UTC
The Black Mage magic list shows the correct recast times for the spells, but the MP cost and the casting bar timing are incorrect. Stone, for example, shows as costing 4MP to cast and the cast bar pops up, quickly runs through to 100% in about a second then the spell goes off 2/3 seconds later.

There was a similar report about this I think that I found whilst searching, which shows as fixed, but the issue is still there. I have checked on White Mage too confirm if it was only Black Mage with this issue, and it seems to be the case as Cure has the right cost and cast time.

**Comment by godmode** [comment] 2018-11-09 16:05
Duplicate of #15

**Closed by godmode** 2018-11-09 16:05 UTC

**Comment by godmode** [comment] 2018-11-09 16:06
Duplicate of #30

**Comment by godmode** [comment] 2018-11-09 16:08
Thanks for reporting. We have plans to adjust this with a day mod in the future but it is not a primary focus right now. As it will take a good amount of time to work on.
