### ISSUE TITLE
I threw away Dynamis Xarc hourglass in Dynamis Beaucidine (old one from previous run) and got kicked out

### ISSUE THREAD

**Issue by HitGubz** [EdenServer/community#4863] opened 2022-02-04 21:56 UTC
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)
- [X ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

I threw away Dynamis Xarc hourglass in Dynamis Beaucidine (old one from previous run) and got kicked out

**Comment by Mozzy4Ever** [comment] 2022-02-04 22:11
Duplicate of https://github.com/EdenServer/community/issues/2976

**Comment by rude-jerk** [comment] 2022-02-07 16:48
Closing as duplicate

**Closed by rude-jerk** 2022-02-07 16:48 UTC
