### ISSUE TITLE
Ranged attack

### ISSUE THREAD

**Issue by Balrahn** [EdenServer/community#1298] opened 2019-03-16 10:59 UTC
On retail if you start your ranged attack on a mob and it later runs out of range, your ranged attack will still go off. On this server however your ranged attack gets interrupted.

**Comment by godmode** [comment] 2019-03-16 12:03
Duplicate of #859

**Closed by godmode** 2019-03-16 12:03 UTC

**Comment by ThrisStraizo** [comment] 2019-03-29 05:01
As a side note, this particular issue has been around since before the ranged rework.  This has caused much of my seething rage as I've pulled my way to 75 on two jobs now.  If anything should be fixed, let it be this particular issue among all the ranged bugs for the love of god.
