### ISSUE TITLE
Wardrobe 2 not working

### ISSUE THREAD

**Issue by killmore627** [EdenServer/community#2004] opened 2019-09-02 11:05 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

On bastok character named Nwa his mogwardrobe did not open after receiving rank 6

**Comment by godmode** [comment] 2019-09-02 12:05
Duplicate of #996

**Closed by godmode** 2019-09-02 12:05 UTC

**Comment by killmore627** [comment] 2019-09-02 12:26
Sorry never had to fill out a ticket before. My character nwa completed rank 6 and did not receive mogwardrobe 2

**Comment by godmode** [comment] 2019-09-02 12:28
It’s fine, just make a GM ticket. And if you do fill out a ticket make sure to follow the checklist.
