### ISSUE TITLE
Fishing Fatigue is Incorrect

### ISSUE THREAD

**Issue by Blex64** [EdenServer/community#2824] opened 2020-05-10 15:59 UTC
### Checklist
- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

Client Version 30181205_0

Fishing Fatigue is incorrect. SE moved away from the "pools" system, which were reset upon zoning, when they introduced the "minigame" for fishing with the arrows. The new fatigue system was simply a limit on the number of fish caught per character per day. 

[Here's ](https://www.bluegartr.com/threads/35405-Is-fishing-truely-THIS-nerfed)a forum thread from 2005 with people discussing (read: complaining) about the new system.

**Comment by Mozzy4Ever** [comment] 2020-05-10 18:57
Fishing pools were always a thing, they just restocked quickly enough that you would only notice if you had a TON of people fishing from a single pool (or there were very few fish in the pool). Eden doesn't have fishing fatigue.

**Comment by Blex64** [comment] 2020-05-10 19:03
Fishing pools were _not_ a thing after this update, and when they were a thing, you could zone to restock them. Eden does have a form of fishing fatigue in the pools, and it's incorrect.

**Comment by Mozzy4Ever** [comment] 2020-05-10 19:09
https://www.ffxionline.com/forum/ffxi-game-related/crafting-synthesis/fisher/58716-fishing-question

Post from after 2005 that speaks of fishing pools.

**Comment by Setz0r** [comment] 2020-05-10 20:00
retail always had pools from the beginning, the removed them in 2014 with the arrow mini-game, it says it clearly in the patch notes for the mini-game.

**Comment by Balrahn** [comment] 2020-09-20 17:12
Finding an empty pool on retail was a rare occurance, yet on Eden it's a rare occurance to find a pool that is not depleted. (yes I'm exaggerating, but something is very off) It doesn't take many players to run out of fish here, and it should get an adjustment.

**Comment by KnowOne134** [comment] 2022-02-21 17:55
We have multiple systems on Eden that are tailored to a smaller population with unlimited account access, vs. the individual fatigue found on retail with paid subscriptions and characters. 
Fishing pools being implemented vs. fishing fatigue is one of those. We already have 'custom' fishing for our era with the arrow mini-game due to client and capture limitations, so no solution here is going to be truly era. Our ultimate goal is to create a balanced economy and a huge factor of that is limiting the NPC gil entering the economy, which is why pools exist in the manner they do.

If there's questions or comments about fishing pool sizes they can be posted in feedback or ffxi-chat on discord. Going to close this since it's working as intended within the framework we've designed for Eden.

**Closed by KnowOne134** 2022-02-21 17:55 UTC
Labels: Crafting/Helm
