### ISSUE TITLE
Something still wrong with RA delay

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1195] opened 2019-03-06 00:18 UTC
There is still something wrong with RA delay. If you start to RA but cancel it, or it doesn't go off for ANY reason (ie mob out of range) you still get a very long lockout on RA.

**Comment by Strumerjohn** [comment] 2019-03-06 06:50
Yeah man I feel like my ranged attacks have a claimshield on them sometimes lol

**Comment by baroom84** [comment] 2019-03-09 21:53
Also getting a snapshot prob causes you to wait the whole delay to re-fire on cor.

**Comment by godmode** [comment] 2019-03-16 12:03
Duplicate of #859

**Comment by 59blargedy** [comment] 2020-10-12 03:24
resolved with recent update

**Closed by 59blargedy** 2020-10-12 03:24 UTC
