### ISSUE TITLE
BST Tame not working, 100% fail rate

### ISSUE THREAD

**Issue by him911** [EdenServer/community#3253] opened 2020-09-12 18:30 UTC
It was somewhat reliable on retail even without additional tame+ gear, less so on higher level mobs but its not working at all here

### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

**Comment by FriskArt** [comment] 2020-09-12 20:17
I've had it work like once or twice. It does however work on unclaimed mobs but it doesn't seem to increase charm rate.

**Comment by 59blargedy** [comment] 2020-09-15 15:54
duplicate of https://github.com/EdenServer/community/issues/2803

**Closed by 59blargedy** 2020-09-15 15:54 UTC
