### ISSUE TITLE
Groundskeeper Meltdown Damage

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#3611] opened 2021-02-01 03:15 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [] I have provided my client version in the details. (type /ver into your game window)

### Details

Groundskeepers in Sky still do inconsistent damage when using Meltdown.  Meltdown damage should be based on remaining HP of the Groundskeeper and not so wildly inconsistent among players in the same party.  I.e. one player taking twice the damage of all else in the party.  I believe this should be the same for mobs of the same type that use self-destruct.

**Comment by dowzer** [comment] 2021-02-01 03:41
Duplicate of #2685

**Comment by 59blargedy** [comment] 2021-06-28 14:45
resolved in June 28th, 2021 update

**Closed by 59blargedy** 2021-06-28 14:45 UTC
Labels: Combat
