### ISSUE TITLE
Zoning allows for re-rolling of loot

### ISSUE THREAD

**Issue by magicmd** [EdenServer/community#1434] opened 2019-03-31 05:02 UTC
In the dunes I accidentally lotted on a magicked skull twice, and the 2nd roll ended up beating the person who was supposed to get it. I had no idea that it would let me lot twice, so I thought it was a completely new skull (it showed up in the pool as if I hadn't attempted to roll at all). It seems if you roll, then zone into a different area, then back to the first it will let you reroll on loot.

![bug report](https://user-images.githubusercontent.com/49112301/55285015-8f68a600-5350-11e9-88e2-cbd44422cf3e.png)

**Comment by MGramolini** [comment] 2019-03-31 08:31
As far as I know leaving the party or zone lets you reroll on loot items and is the intended behavior.

**Comment by magicmd** [comment] 2019-03-31 08:33
I remember letting you reroll, but I don't remember having the 2nd roll take priority over the first. Even if you rerolled, the first lot was always the one that mattered. I'm fairly certain i'm not misremembering this, because it's highly abusable.

**Comment by Setz0r** [comment] 2019-03-31 08:33
Yes, this was retail behavior.

**Comment by MGramolini** [comment] 2019-03-31 08:36
Yes to which comment setz? ;)

**Comment by Setz0r** [comment] 2019-03-31 08:38
In retail, you could leave the party and rejoin or zone and come back and it would let you reroll on an item.

**Comment by Setz0r** [comment] 2019-03-31 08:40
don't beat yourself up @magicmd. it was just a magicked skull.  at least it wasn't a rare HNM drop :D

**Comment by magicmd** [comment] 2019-03-31 08:40
I guess that's true. I'll have to remember it. Sorry for the bogus bug report.

**Comment by godmode** [comment] 2019-03-31 13:18
No problem. We’d rather have a report if you think something is wrong and just close it than no report and something that was wrong be in the game without anyone saying. Thanks!

**Closed by godmode** 2019-03-31 13:18 UTC
