### ISSUE TITLE
Goblin Poacher in Gustav Tunnel

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#991] opened 2019-02-15 19:29 UTC
The Goblin Poachers in Gustav Tunnel will often be "out of range"
Maybe its the elevation changes?

**Comment by mpinholster** [comment] 2019-02-15 19:50
Easy fix...swap the rangers to the DRK or THF Goblins?

**Comment by godmode** [comment] 2019-02-16 20:40
Duplicate of #353

**Closed by godmode** 2019-02-16 20:40 UTC
