### ISSUE TITLE
Golden Salvage 100% mimic

### ISSUE THREAD

**Issue by Nonono-Amb** [EdenServer/community#5506] opened 2023-02-26 12:15 UTC
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Tier 1 assault Golden Salvage got 12/12 mimics when checking cursed chest as smn. The same situation occurred 3 times of 6 run in a week after last schedule maintenance.

**Comment by KnowOne134** [comment] 2023-02-26 12:57
How are you checking the chests?

**Comment by Nonono-Amb** [comment] 2023-02-26 14:48
I summoned Garuda then walk close to each cursed chest.

**Comment by Mirridelle** [comment] 2023-06-26 23:29
Just had this happen to us too. We counted each chest we checked in the chat log, and I went back and confirmed that each count in the chat log was accompanied by the message of a mimic attacking, so it really was 12 separate mimics. My thought was that perhaps the correct chest changes when the in-game day changes, similar to how MRs in Promyvion work. The game day did switch over to a new day when we were doing the assault.

Version 30181205_0

**Comment by KnowOne134** [comment] 2023-06-29 18:37
Going as smn and smns attacking before triggering? Are you trying to click the chests?

**Comment by Mirridelle** [comment] 2023-06-29 19:05
Yes we used SMN strat. Most chests would morph into mimics before I can click on them properly, since they morph once I'm standing next to them.

**Comment by KnowOne134** [comment] 2023-06-29 19:26
Note to self
Check if progress changes as players enter zone and disrupts the mob spawned to be correct trigger

**Comment by Mirridelle** [comment] 2023-07-01 21:14
Update: Just had a run today where the correct chest still spawned into a mimic, but because I clicked on it first fast enough, it still gave us the clear (while still spawning into a mimic and attacking me/my avatar).

It looks like we need to be clicking on each chest fast, before they spawn into mimics when you get close to them, because even the real chest can still morph into a mimic and therefore be unclickable. If you successfully click on a chest before it morphs into a mimic, you should get the message "The chest contains..." even if it is a false chest. The real chest may or may not morph into a mimic when you get close, but if it's real, you can still click and get the win if you're fast enough.

![Erutanda_2023 07 01_140731](https://github.com/EdenServer/community/assets/134561322/bb87c268-9a54-483e-a0d8-b6993239963e)

**Closed** 2023-08-07 14:09 UTC
