### ISSUE TITLE
Energy Drain and Energy Steal do not appear to work

### ISSUE THREAD

**Issue by mpinholster** [EdenServer/community#1460] opened 2019-04-03 19:17 UTC
Energy Drain and Energy Steal do not appear to work

I looked and didn't see a Bug Report for this

**Comment by gweivyth** [comment] 2019-04-05 12:40
Need more detail, what kind of mobs are you trying them on?  I believe requirements for these weapon skills is that the monster actually has to have MP to drain, so you'd need to be using it on mage type beastmen or crabs.

**Comment by isotor** [comment] 2019-04-05 12:48
To save OP spending more time on this no extra detail is required - these have skeleton scripts on current DSP and I can't imagine these have been anywhere near high enough priority to be any different on Eden at present.

https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_drain.lua
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_steal.lua

**Comment by mpinholster** [comment] 2019-04-05 14:24
I tried it on Robber Crabs and those Quicksand Cave Beetles.

I have accidentally used it on Lesser Colibris in the past.

**Comment by gweivyth** [comment] 2019-04-05 15:23
> To save OP spending more time on this no extra detail is required - these have skeleton scripts on current DSP and I can't imagine these have been anywhere near high enough priority to be any different on Eden at present.
> 
> https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_drain.lua
> https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_steal.lua

Well that'll do it, lol.   Can't imagine these would be too hard to write, I might even be able to do it if they work similarly to other weapon skills + current Aspir.  I'll mess with it this weekend.

**Comment by Jamini** [comment] 2019-07-09 05:52
I would like to update this to confirm Energy Steal and Energy Drain still do not work.

![image](https://user-images.githubusercontent.com/1775680/60862663-3b414d80-a1ec-11e9-8160-3e425325ef91.png)

**Comment by E5una** [comment] 2019-08-09 10:22
Can also confirm this. I've tried on mage beastmen as well as elementals and thbe result is always the same, nothing prints in the log after I ready the ability, and I never gain mp.

**Comment by iklarazu** [comment] 2020-05-21 10:50
### Checklist


- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I would have been grateful if @Volkaru had read my post, giving examples of other similar WS to copy scripts/draw inspiration from, instead of essentially saying "lol those work, **close thread**," however, I do understand #2874 was closed based on dupe. This thread is evidently dead. As the tasks weren't checked in the original post, I'll hijack it and start from here.

/ver 30181205_0

[Energy Drain](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_drain.lua) and [Energy Steal](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_steal.lua) are empty scripts that don't do anything. Tested on thf/whm and brd/whm, using either WS shows the animation, the log states "player readies weapon skill," but nothing happens.

This is not a case of recovering 0 MP; the weapon skill fails to activate. I've tested this on mobs with MP such as crabs, as well as mage-type Ahriman and Goblins, 



In addition to the screen above from @Jamini, here are 2 further screens from #2874 provided by @Nyur0 to show both ED and ES not doing anything:

![image](https://user-images.githubusercontent.com/65654611/82430497-61b25500-9a5b-11ea-9664-86d20d801feb.jpg)
![image](https://user-images.githubusercontent.com/65654611/82430499-61b25500-9a5b-11ea-861e-d3773026be29.jpg)

Here are other weapon skill scripts with similar effects: [Starlight](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/starlight.lua), [Moonlight](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/moonlight.lua), [Spirit Taker](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/spirit_taker.lua), [Sanguine Blade](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/sanguine_blade.lua) (though this is of course HP instead of MP, so may not be useful.)

If there's something I can do to help test or provide additional details, please let me know.

**Comment by 59blargedy** [comment] 2020-05-21 11:19
unfortunately, we can't just assume other mp/hp return wses are related in terms of how they function. what helps in cases like this are links to data on the wses themselves, or testing done in retail. As the energy weaponskills actually have "we're not sure how these wses work" on the wiki, they are difficult to implement without retail testing at 1k 2k 3k tp, with varying amounts of mind, HP, skill levels, base damage, etc. 
it's clear they do not work here, but to make them work, more concrete data is needed.  

that being said, I went ahead and did some bare bones tests the other day during this free retail period and need a few more before compiling and providing to get this fixed.  on first look, they seem to follow ftp rules vs. any hp/skill functions like the wses mentioned.

**Comment by Nyur0** [comment] 2020-05-28 14:46
Tested out Starlight and Moonlight on THF as I was skilling my club up. Confirming that those two do work on Eden.

Unfortunately, Energy Drain/Steal seem to be buggy. Shame! Would be nice to have for /whm soloing.

Thanks for your detailed research on this!

**Comment by DrfistMD** [comment] 2020-09-17 09:10
Starlight does not appear to be currently functioning.  0MP recovered and does not consume TP.  Captured a brief clip of this while out learning some BLU magic.

https://www.youtube.com/watch?v=EqMvJQQQlrQ

**Comment by 59blargedy** [comment] 2020-12-14 15:38
resolved December 14th update

**Closed by 59blargedy** 2020-12-14 15:38 UTC
Labels: Combat
