### ISSUE TITLE
Odd BST pet behaviour

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#67] opened 2018-10-04 20:55 UTC
Pet behavior and movement is not consistent.  Sometimes the pet will idle and not follow you after killing a mob as if 'Stay' was used or won't engage when 'Fight' is used.   Sometimes moving around the pet will cause it to follow you again.

**Comment by chlorr** [comment] 2018-10-04 21:19
I've also noticed some wild BST pets do not like to follow their owners, Master walks north pet stays / walks south then they come back to each other

**Comment by Lilswitche** [comment] 2018-10-04 21:20
It's starting to look like it's a pathing issue and the monster gets stuck.

**Comment by AJ3281** [comment] 2018-10-24 00:34
I have noticed same. In addition when "fight" is used and they are stuck they were not always attacking even when side by side mob. I had to "heel" them then "fight" again for them to engage.

**Comment by ZaksHouse** [comment] 2019-01-19 16:10
I have also noticed when you "heel" to pull pet back so you can avoid links it wont come back unless your literally on top of its face and walk it back with you I should be able to "heel" from good distance and make my pet follow along with what mob I am fighting so I can fight in a safe spot instead of pool of links or aggro.

**Comment by godmode** [comment] 2019-02-16 21:18
Duplicate of #438

**Closed by godmode** 2019-02-16 21:18 UTC
