### ISSUE TITLE
BLU AF quest Omens BCNM not working

### ISSUE THREAD

**Issue by Bel85** [EdenServer/community#2598] opened 2020-04-01 09:23 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I have the BLU AF quest "Omens" in quest log. I can click on the Omens option when trying to enter the battlefield at Navukgo Execution Chamber. I then get a message saying: "You cannot enter the battlefield at present. Please wait a little longer". I get into the BCNM anyway, but there is no mob there and no music plays. The place is empty. I can choose the option "run away" when trying to exit which puts me back at the BCNM entrance.

I was alone, not in a party. A GM tried to help me, but the same thing happened to them when we were in a party and I was told to file a report. I checked the zone and there was noone else there as far as I could see.

Client version: 30181205_0

Thanks.

**Comment by E5una** [comment] 2020-04-11 16:31
Just wanted to mention an old ticket that was closed but the issue may have resurfaced: 

https://github.com/EdenServer/community/issues/1058

BLU's are currently unable to get their AF (the +15 skill on body is crucial to spell resistance on Eden) due to this battlefield blocking progress.

**Comment by E5una** [comment] 2020-04-19 17:51
Sorry that this is not new information, but wanted devs to be aware that there are now a growing group of blue mages that can't get their AF due to this pre-requisite quest not working. BLU desperately needs its AF body to function properly with resists, so this is very important to the growing number of blue mages that are asking about this in the discord blue mage channel. 

Thanks, and sorry to not provide any new info. If there's a way I can help resolve this ticket faster please contact me on discord E5una#7556 and I can help test or look at code (relatively cluelessly) if it helps at all.

**Comment by E5una** [comment] 2020-04-26 11:41
This ticket can be closed, there is proof it was resolved as a side effect of some other tickets in the BLU discord channel where Tobio confirmed he was fighting the Immortal Flan.

**Comment by KnowOne134** [comment] 2020-04-26 12:00
Fixed with yesterday's update

**Closed by KnowOne134** 2020-04-26 12:00 UTC
