### ISSUE TITLE
Charybdis Accuracy too high

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#2148] opened 2019-10-21 16:48 UTC
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X ] I have provided my client version in the details. (type /ver into your game window)

### Details

Charybdis seems to have way too high of accuracy at the moment. Watched a THF with 452 evasion get absolutely rolled by it. I had 380 eva and in 1 attack round it stripped all 3 shadows. According to https://ffxiclopedia.fandom.com/wiki/Talk:Charybdis#Dualbox , THF/NIN with ~350-400 evasion made it a joke of a fight (though long cause of dps obviously). A couple of testimonials state that they were able to cast Ni into Ni cause of how long it took for Charybdis to actually land hits.

**Comment by VeilEden** [comment] 2019-10-21 17:35
Can confirm. I tried this as 75 Nin, Hasted as well, and got absolutely decimated. I had +58 Evasion at the time iirc, and it hardly ever missed, even with Kurayami applied. By ~80% my timers were botched. Additionally, the next attack round it landed all 6(?) hits, all of them criticals and it 100>0 me. He’s turned up.

**Comment by Wade9363** [comment] 2019-10-21 17:42
I got my ass handed to me by Charbydis also, but never fought him on retail so I didn't know if that was normal.

**Comment by Setz0r** [comment] 2019-10-21 17:44
i tanked him as nin on retail a few times, with moderate evasion+ gear he had about a 50% accuracy, with double mambo he had like a 10% accuracy.  a well geared thf with double mambo was practically invincible to him.

**Comment by piercingdark** [comment] 2019-10-21 20:23
I can confirm with capped evasion on my Ninja, evasion and haste gear, elegy on charby, haste on me, double mambo... Still couldn’t keep timers up for utsusemi. Retail was much easier.

**Comment by Archer409** [comment] 2019-10-21 23:30
Have tanked Charybdis 6 times on eden as Nin. Ranging from very average evasion gear with a bard double mambo and was able to tank well and never felt in danger.  

The most recent kill I had much better gear. Checkparam said 375 evasion and i had 8% haste gear on. NO bard. No gear swaps so i was 100% in evasion set. Had a rdm for support/haste/enfeebs and was able to keep shadows up most of fight.  Felt about right for the amount of evasion i had.  I tanked him in retail a bunch and he feels about the same to me.

**Comment by Mozzy4Ever** [comment] 2019-10-21 23:32
> Have tanked Charybdis 6 times on eden as Nin. Ranging from very average evasion gear with a bard double mambo and was able to tank well and never felt in danger.
> 
> The most recent kill I had much better gear. Checkparam said 375 evasion and i had 8% haste gear on. NO bard. No gear swaps so i was 100% in evasion set. Had a rdm for support/haste/enfeebs and was able to keep shadows up most of fight. Felt about right for the amount of evasion i had. I tanked him in retail a bunch and he feels about the same to me.

When was this "most recent kill"?

**Comment by Archer409** [comment] 2019-10-21 23:36
> 
> 
> > Have tanked Charybdis 6 times on eden as Nin. Ranging from very average evasion gear with a bard double mambo and was able to tank well and never felt in danger.
> > The most recent kill I had much better gear. Checkparam said 375 evasion and i had 8% haste gear on. NO bard. No gear swaps so i was 100% in evasion set. Had a rdm for support/haste/enfeebs and was able to keep shadows up most of fight. Felt about right for the amount of evasion i had. I tanked him in retail a bunch and he feels about the same to me.
> 
> When was this "most recent kill"?

Approx 2 weeks ago

**Comment by Slamm21** [comment] 2019-10-22 00:25
This is normal, you had to be well geared on nin eva wise to tank him on retail and generally, a brd helped a lot but was not needed.
Just make sure your RDM is actually landing enfeebles and has some kind of mnd build for slow/para and int for blind and he is pretty easy. An MP geared one will barely affect it.

**Comment by VeilEden** [comment] 2019-10-22 06:39
+108 Evasion for my fight, and others with double mambos and we all got face rolled. He was never that accurate on retail. Solo evasion tank? Never. THF or NIN duo with a Brd? All the time. Something’s off imo. Or the majority here is majorly unlucky.

**Comment by Slamm21** [comment] 2019-10-22 07:04
I've fought him about 10 times on Eden including Solo, never had an issue. Debuffed he hits slowly and you can go ichi to ichi as a thf or ni to ni on a nin for the most part.

**Comment by Mozzy4Ever** [comment] 2019-10-22 07:06
> I've fought him about 10 times on Eden including Solo, never had an issue. Debuffed he hits slowly and you can go ichi to ichi as a thf or ni to ni on a nin for the most part.

When was the last time you fought him? Wondering if maybe something was inadvertently changed

**Comment by VeilEden** [comment] 2019-10-22 07:41
Dunno. Maybe he’s spawning at different levels? My experience was about 2-2.5 months ago? But for our experiences to be so vastly different doesn’t make sense. And yeah, soloing it is easy as a Rdm or Blm. Bind/Grav are pretty OP on Eden.

**Comment by Slamm21** [comment] 2019-10-22 08:26
about 2 months ago last time.
But we usually did it rdm+thf and no issues whatsoever.
I wouldn't say bind/grav is different to retail, just some mobs have too weak a resistance to magic in general, such as KB.

**Comment by Redenius** [comment] 2019-11-14 04:11
I tired this as RDM + THF and failed miserably unlike retail. We had to do it RDM + BLM nuke / bind method.

**Comment by FFXIGravedigger** [comment] 2019-11-14 09:09
My charby fight wasn't too horrible but we had a perfect setup. WHM/RDM/RDM/THF/BRD/NIN the brd did double march (not mambo) the thf did spike dmg without feeding it tp. I remember in retail its TP moves are nasty wipes all shadows. The RDM in group landed enfeebs which was key to the fight. https://www.youtube.com/watch?v=PfmB1kIr2eA (( 7:47:35 )) start of charby fight ends at (( 8:08:28 ))  If you want to check out how the fight went. I felt the fight was easier than on retail because Cross-attack seemed to do lower dmg here, its accuracy felt in era though my evasion set on ninja isn't the best geared at time of video my ninja had +46 evasion on gear with no evasion merits at the time this video was shot.

**Comment by StriderClerix** [comment] 2019-11-14 11:42
Also worth noting that Mambo does not work properly on this server....

**Comment by Volkaru** [comment] 2019-11-15 22:11
Can confirm he is overtuned on here. And this is a recent development. Before I was able to solo this on PUP. That was four months ago. Just tried today. He tore through my two hour'd automaton in a minute. Then bodied our very well geared BLU/NIN shortly after. Then hit a galka PUP with Protect V and Defender for a very high amount in one attack round compared to my last attempt.
![Volkaru_2019 11 15_140001](https://user-images.githubusercontent.com/9113384/68979220-cab9c700-07b1-11ea-92bb-a8bc753e7002.png)

**Comment by VirtuosusFFXI** [comment] 2019-11-15 23:08
I feel as though it's accuracy is for sure overtuned, but I'm not entirely sure whether it's damage is overtuned or not compared to era. 5 Attack rounds hit my BLU with Terra's/Jelly Ring/Umbra Cape (Nighttime bonus too) and Cocoon for an average of 80-100 per hit for a total of 400 damage. More than I was expecting for sure, however I did not exactly come prepared to tank it in the first place, since our strategy was to have the puppet tank it. 

I didn't have defense food, defense songs/roll or /war or anything of the sort. Our followup attempt showed that you can pretty easily brute force the damage it deals with PLD/RDM, PLD/BLU, BLU/WAR, BLU/PLD, etc types of setups where you just stack PDT and high defense.

**Comment by Slamm21** [comment] 2019-12-26 22:10
I fought this again today. I highly suspect a bunch of MP geared RDMs trying to enfeeble him is the issue. with slow, para and blind on him the NIN I killed with barely got hit and I don't have slow/par/blind2 yet. If anything he is too easy and not too hard imo.

**Comment by Mozzy4Ever** [comment] 2019-12-26 23:37
> I fought this again today. I highly suspect a bunch of MP geared RDMs trying to enfeeble him is the issue. with slow, para and blind on him the NIN I killed with barely got hit and I don't have slow/par/blind2 yet. If anything he is too easy and not too hard imo.

Nope. Taru here, never gear for MP for obvious reasons. At the time my Para2/Slow2 (cause lolblind2) build was ~MND96

**Comment by Slamm21** [comment] 2019-12-27 00:02
MND96 seems low honestly.
I have 64+80MND (144)

**Comment by raventn** [comment] 2019-12-28 05:41
problem with Charybdis is his acc and its mnk that use "both" fist dmg and they hit very hard.
since he is like kraken club user it s DSP broken mob it was same problem on Nasomi just he changed his attack to just 1 beacuse he is to broken.

**Comment by Slamm21** [comment] 2019-12-28 08:22
Most of the hits won't land though because of blind and cheap eva gear, and the trick with any mob that hits multiple times is as soon as you see the first hit land, you start recasting shadows. When the first hit lands, every hit has landed and you are just seeing the animations so you will never be interrupted. So as a NIN you just go NI to NI.

With slow from a RDM without mp gear he will take a long time between hits and if you have a brd too it is funny how long he takes with elegy on top of slow.

**Comment by ShiyoKozuki** [comment] 2019-12-28 10:02
Full DD gear on nin/war at 75 with double mambo + elegy + hojo and I was invincible to him on retail at 75.

**Comment by StriderClerix** [comment] 2019-12-28 13:05
> Full DD gear on nin/war at 75 with double mambo + elegy + hojo and I was invincible to him on retail at 75.

Please take note of my reply regarding Mambo. Might not be able to reproduce that here.

**Comment by Slamm21** [comment] 2020-08-04 11:34
I did this again recently, no brd.
The NIN almost never got hit because of debuffs and he was not in eva gear. Closing.

**Closed by Slamm21** 2020-08-04 11:34 UTC
