### ISSUE TITLE
Beastman's seals from mobs that don't give exp. 

### ISSUE THREAD

**Issue by klement87** [EdenServer/community#1185] opened 2019-03-04 22:04 UTC
Was skilling up in Qufim and was getting seals from crabs that weren't giving exp. I had a lower level character with me that they check easy prey to so that could be why.

**Comment by icariumkupo** [comment] 2019-03-04 23:03
#1047

**Comment by godmode** [comment] 2019-07-11 22:25
Duplicate of #1047

**Closed by godmode** 2019-07-11 22:25 UTC
