### ISSUE TITLE
Quest Sorcery of the North Drops from quest log

### ISSUE THREAD

**Issue by zernon916** [EdenServer/community#3381] opened 2020-10-29 04:09 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Finished Tele Holla quest, zoned, picked up Quest: Sorvery of the North,  Checked was in log, went to Feyin, got key, got chest, No Longer in quest log, no key item...

**Comment by Shoruto** [comment] 2020-10-29 15:48
Closing because it's a duplicate of #3382

**Closed by Shoruto** 2020-10-29 15:48 UTC
