### ISSUE TITLE
Ullikummi Lottery Repop Audit

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#2121] opened 2019-10-11 18:00 UTC
### Checklist

- [yes ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
30181205_0
### Details

Can we get an audit on Ulli's respawn time?  Per the wiki, it's 4-12 hours, however in my experience and other LS members experience, the fastest they have seen is 6.5 hours. 

https://ffxiclopedia.fandom.com/wiki/Ullikummi?oldid=43689

**Comment by Slamm21** [comment] 2019-10-12 05:12
Every time you see a lottery window, the end number is always wrong.
4-12 hours means 4+ hours. After 4 hours since the last kill the window is open and then it is a pure lottery until it pops.
I have had him pop 20mins after we got there and one day he didn't pop after 10hrs and we went to bed.

**Comment by Mozzy4Ever** [comment] 2019-11-12 18:45
@Slamm21 the problem with lottery NMs is on retail, there were only a few NMs that had a confirmed "max" respawn time with consistent PH kills (like LoO). On private servers, most lottery NM respawn timers are coded by doing a random between the lowest and highest reported respawn time. After that random'd time has passed, THEN window is open and the mob (typically) has a low % chance to spawn. For instance, take https://github.com/DarkstarProject/darkstar/blob/111102af33d980c44b5c9841d3db7234185a8663/scripts/zones/West_Ronfaure/mobs/Forest_Hare.lua

    dsp.mob.phOnDespawn(mob, ID.mob.JAGGEDY_EARED_JACK_PH, 5, math.random(3000, 21600)) -- 50 minutes to 6 hours

So when JEJ dies, a random time between 50 minutes and 6 hours is rolled. Before that time is up, killing placeholders is pointless. After that time is up, killing a placeholder has a 5% (that's what the 5 after JAGGEDY_EARED_JACK_PH means) to spawn. This is obviously not the proper way to do this, as on retail it's pretty well documented that placeholder NMs have a base respawn time, and then % chance to spawn after each placeholder kill. Doing lottery NMs in this way can result in some veeeery long respawn times compared to retail, as their window could potentially not open until the very longest reported respawn time at which point you have to deal with the low % pop rate

**Comment by mlandrum22** [comment] 2019-11-12 19:53
Sounds like this is something that should be changed.

**Comment by Slamm21** [comment] 2020-01-02 08:10
Had another 10 hours before we all passed out job last night, no one had been there before us. Worst we had was 14 I think before giving up. The issue might be the % chance of pop is too low but honestly, I have too fuzzy a memory of that time in retail to be sure. Sometimes he does pop quickly too.

**Comment by Mozzy4Ever** [comment] 2020-01-02 14:41
> Had another 10 hours before we all passed out job last night, no one had been there before us. Worst we had was 14 I think before giving up. The issue might be the % chance of pop is too low but honestly, I have too fuzzy a memory of that time in retail to be sure. Sometimes he does pop quickly too.

What time EST did you go up? ^^;

**Comment by Kurtalicious** [comment] 2020-04-24 18:51
This is a real thing.  I have never seen Ulli respawn in less than 12 hours. Something is not right.

**Comment by Slamm21** [comment] 2020-05-08 09:46
The problem is Ulli window should always open after 4 hours, not 4-12
The same can be said with every NM which has a coded range on DSP.

**Comment by 59blargedy** [comment] 2020-07-06 15:54
shouldnt be an issue since removing upper bounds a few months ago, closing

**Closed by 59blargedy** 2020-07-06 15:54 UTC
