### ISSUE TITLE
Dynamis - San d'Oria Boss respawning his adds indefinitely

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#3363] opened 2020-10-23 02:20 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Steps to reproduce:
1. Pull the boss statue and it will summon 2 NMs and a few other mobs
2. Kill both NMs and all mobs before switching to the boss
3. The boss will resummon all of the same mobs again

Alternatively, choosing to kill the boss statue first will instead depop the NMs (and maybe mobs too?) which may also be incorrect behavior.

**Comment by Mozzy4Ever** [comment] 2020-10-23 03:05
Kinda duplicate of https://github.com/EdenServer/community/issues/2295
Same bug, different zone.

**Comment by VirtuosusFFXI** [comment] 2020-10-23 03:35
Ah yeah, I searched for sandy related bugs to this and didn't find any except one offhand mention from a 2018 report where it was sort of a different issue.

**Comment by Garphilius** [comment] 2020-10-23 04:22
Aye, this happens in all the zones. Most notably in Beaucedine where you kill all 4 shadow dragons before the Eye. Once you engage the Eye again, it will pop all 4 shadow dragons again. This is extremely annoying requiring either a puller pull all 4 shadow dragons far away (but that takes time, especially here on Eden where mobs get stuck) or hold the 4 shadow dragons while you kill the Eye.

**Comment by falzum** [comment] 2020-10-23 11:38
The dragons in bcd repopping if you kill them before Angra Mainyu is normal behavior. Killing the giant statues on the way to Fei'Yin stops them from respawning.

**Comment by Garphilius** [comment] 2020-10-23 11:44
Of course, we know that. What I just said is taking into account the fact that we already killed all the big statues.

**Comment by Oyaziiiiiii** [comment] 2020-10-23 23:47
From my experience this happens when the main boss loses aggro. If it loses aggro it'll spawn everything again when it's pulled again.

**Comment by Garphilius** [comment] 2020-10-24 01:57
Yeah, that is 100％ what we experience as well, Mcdohl.

**Comment by rude-jerk** [comment] 2020-12-28 16:17
Resolved in December 28, 2020 patch.

**Closed by rude-jerk** 2020-12-28 16:17 UTC
Labels: dynamis
