### ISSUE TITLE
OP Warp Won't Activate When Having Less Than Default CP

### ISSUE THREAD

**Issue by HunnyDoo** [EdenServer/community#1268] opened 2019-03-13 13:22 UTC
Let's say a warp costs 100 CP, the default amount is 1000 CP, but you only have 500 CP. Occasionally this will cause the warp npc to just turn your character invisible and never actually warp. It's as though the game checks and sees you can afford 100 CP, but there's some additional check freaking out that you're under 1000 CP.

**Comment by MGramolini** [comment] 2019-03-13 13:36
duplicate of https://github.com/EdenServer/community/issues/512 ?

**Closed** 2019-03-19 10:00 UTC
