### ISSUE TITLE
Aht Urhgan Mission 15: The Black Coffin

### ISSUE THREAD

**Issue by Wannaspoon** [EdenServer/community#3210] opened 2020-08-24 05:21 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details
Not able obtain a second Ephramadian Gold Coin.
Also when attempting to enter the fight you're sent into oblivion as you where in the COR AF3 fight.

https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_15:_The_Black_Coffin

**Comment by KnowOne134** [comment] 2020-08-29 00:14
click on the headstone to get another coin

**Comment by KnowOne134** [comment] 2020-08-29 00:18
duplicate of https://github.com/EdenServer/community/issues/3201

**Closed by KnowOne134** 2020-08-29 00:18 UTC
