### ISSUE TITLE
Thief ability: Hide

### ISSUE THREAD

**Issue by dowzer** [EdenServer/community#3152] opened 2020-08-02 19:16 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Hide is not working as intended. It still successfully activates with aggro from sneak detecting mobs, such as aquans. amorphs, and bats. It will also allow the player to run by sneak aggroing mobs without detection.

Player tries to hide, but it spotted by the monster. Does that message exist on Eden? 

There is some functionality, for example Orcs detect by sight and scent. Hide won't activate, yet there is no message displayed for failing to hide.

**Comment by Slamm21** [comment] 2020-08-02 22:51
Duplicate of
https://github.com/EdenServer/community/issues/810

**Closed by Slamm21** 2020-08-02 22:51 UTC
