### ISSUE TITLE
Can't Receive last cutscene for RDM AF3 hat. Version 30181205_0

### ISSUE THREAD

**Issue by Redmage1** [EdenServer/community#1549] opened 2019-04-16 20:36 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I am trying to receive my AF hat for RDM. I have looked at multiple guides and they all say the same thing, so I know I have completed it correctly. The last part of the quest is go to G citadel behind the first gate and pop the NM when you examine the oak box, kill the NM, trade the nailbiter to the oak box and get a CS. I have done this. Once I got back to North Sandy, the last cutscene did not trigger and I did not receive my AF hat. I left Sandy completely and zoned back in and still have not received the cutscene. I waited until JP midnight (even though that isn't part of the quest) to see if it would trigger and still nothing.

**Comment by Shoruto** [comment] 2019-04-17 12:03
Duplicate of #608

**Comment by Redmage1** [comment] 2019-04-17 19:57
I know this is a duplicate which is why I didn't check the first box but when I looked at the issue I never saw it being resolved so I out in a new ticket for it and contacted a GM. I don't know what my next steps are.

**Comment by Shoruto** [comment] 2019-04-17 20:02
Totally understandable, keep in contact with the GM.  The dev's definitely are aware of the issue, however there are so many bugs to correct, it takes time.  Your best bet right now is stay talking with the GM.  It will be resolved at some point just gotta be patient.

**Comment by Redmage1** [comment] 2019-04-17 21:59
Okay, so just wait until its fixed until i get my hat? Not that im not patient. Im jw what you guys do, if I receive the item or not.

**Comment by Redmage1** [comment] 2019-04-18 22:08
Can close this issue. Went back for a random 3rd time. This time i refought the NM instead of just traiding the nailbiter again and got a new nailbiter, traded that and did the CS, zoned into n sandy and it worked.

**Comment by Redmage1** [comment] 2019-04-18 22:08
3rd times a charm

**Comment by Shoruto** [comment] 2019-04-18 22:24
Awesome glad it finally worked :)

**Comment by bkesecker** [comment] 2019-04-24 11:34
Once development fixes the concurrency issues with character variables, issues like this should be minimized.  Closing since 608 is out there.

**Closed by bkesecker** 2019-04-24 11:34 UTC
