### ISSUE TITLE
[PLD]Valor Surcoat doesn't give augmented cover

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#3117] opened 2020-07-19 15:16 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

The Relic body piece for PLD (from Dynamis Xarcabard) doesn't grant MP when you cover with it equiped. It should augment cover to allow you to take a few hits to fill up your manabar, but doesn't give any MP back.

**Comment by Shoruto** [comment] 2020-11-03 18:59
Duplicate of #2119

**Closed by Shoruto** 2020-11-03 18:59 UTC
Labels: Job
