### ISSUE TITLE
Blizzard Gloves - Not giving the en-blizzard effect

### ISSUE THREAD

**Issue by rhys2266** [EdenServer/community#3122] opened 2020-07-21 13:25 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

I bought a pair of blizzard gloves to try out w/ Soboro and they give absolutely no additional effect, nothing comes up in the status bar nor chat window to say the effect should/did land on me

ver 30181205_0

**Comment by ThrisStraizo** [comment] 2020-07-21 20:23
Duplicate of #2732

**Comment by 59blargedy** [comment] 2020-07-21 22:46
closing as duplicate

**Closed by 59blargedy** 2020-07-21 22:46 UTC
