### ISSUE TITLE
Strange Pop Conditions on Sheep in Antlion's Clothing

### ISSUE THREAD

**Issue by Eme-FFXI** [EdenServer/community#884] opened 2019-01-29 13:30 UTC
Tried this today and lost due to time. Wierd thing was:
* NM spawned initially where its supposed to, eventually hid again after enough damage
* I searched all other spots but only the other antlions popped, I killed them all
* returning to the beginning, the NM popped again and eventually hid the 2nd time
* I searched the whole area but NM would pop at the very beginning again
* for the last time I stayed in close proximity for some time but the NM would not pop, so I searched the whole area, only to come back to the very beginning where it poped the last time.

Strange that it only popped on 1 location and not popping when I was standing there before running outside a specific unknown range. This supposed to happen?

Regards

**Comment by godmode** [comment] 2019-01-29 14:42
Hmm I think I may have overlooked something. Will check on it. Thanks for the report

**Comment by godmode** [comment] 2019-02-07 00:40
Duplicate of #906

**Closed by godmode** 2019-02-07 00:40 UTC
