### ISSUE TITLE
I could read Linkshell chat and I dont even have a Linkshell!

### ISSUE THREAD

**Issue by ClashofallStyles** [EdenServer/community#1188] opened 2019-03-05 04:24 UTC
Hello, Styles Here.

So I was taking a boat ride from Whitegate to Nashmau and while on the boat ride I started being able to read some random LS chatter.
The thing is.. I dont have a LS at all! I've been playing solo.
I just wanted to bring this up to your attention.
![ls](https://user-images.githubusercontent.com/42421341/53780941-ab556500-3ed4-11e9-9cba-dda3b563bd3e.JPG)

**Comment by godmode** [comment] 2019-03-05 13:20
Wow that’s crazy. Thanks for posting. We will have to look deeper into that.

**Comment by maeinit** [comment] 2019-03-08 01:50
I have also received this before--and what's even funnier is it looks like it might have been the same linkshell. I had no linkshell on in slot 1, but I did have one on in slot 2. Randomly I started seeing messages in slot 1 color.

**Comment by Veesae** [comment] 2019-03-08 02:45
![image](https://user-images.githubusercontent.com/48340852/54004051-1c7d5e00-4109-11e9-8818-d586133e49ad.png)

It also happened to me today! I have no LS on either of my slots..

**Comment by godmode** [comment] 2019-03-08 13:04
Is this the same LS then? If so what LS is it?

**Comment by bkesecker** [comment] 2019-03-08 16:50
Looks like different LS.  The first image is Skyward.  Not sure about the second.

**Comment by gweivyth** [comment] 2019-03-11 05:34
Don't think it's Skyward, looks like LittleWonder.

**Comment by Drahkais** [comment] 2019-05-20 01:07
Happening today while standing at the AH. LS appears to be MeanCoeurls in this instance. Not sure what actually triggered the event because I had been standing here doing other things on my second monitor for a while before the chat began to appear out of the blue.

![image](https://user-images.githubusercontent.com/46201385/57990989-9a8ea700-7a60-11e9-930d-667d5c10a5d6.png)

**Comment by Fng098** [comment] 2020-03-01 12:43
I was lucky enough to see WingedSymphonyz's LS chat.  I wonder if it is a bug with zoning?  It seems to happen to me when I zone around in Windhurst.

**Comment by Shoruto** [comment] 2020-11-02 17:29
Duplicate of #1844

**Closed by Shoruto** 2020-11-02 17:29 UTC
