### ISSUE TITLE
Boost modifies Chi Blast incorrectly

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2433] opened 2020-01-20 02:11 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

I believe that boost may be incorrectly modifying the damage formula for chi blast. With temple gloves equipped and boosting 12 times, the max amount of damage that chi blast should do is MNDx10. I have not yet seen something close to this. 

Without using boost, chi blast should range from about (total MND/2) to (total MND) in damage. When I tested chi blast on wild rabbits and used boost once with and without temple gloves equipped a chi blast did less than half my total mind, which should not be possible. Also the damage values from only boosting once were much lower than how they should be according to the formula used from https://www.bluegartr.com/threads/108197-Random-Facts-Thread-Abilities?p=5089420&viewfull=1#post5089420

![image](https://user-images.githubusercontent.com/46270382/72693118-70185080-3afd-11ea-9eb8-75e6962f66e6.png)

version 30181205_0

**Comment by rude-jerk** [comment] 2020-11-03 02:14
The max of `MND * 10` is when both Temple Gloves and Taurine Cesti are equipped.
Max w/ Temple Gloves is `MND * 8.5`.

**Comment by rude-jerk** [comment] 2020-11-03 02:14
Could not reproduce sub-`MND/2` damage results currently.

**Comment by rude-jerk** [comment] 2020-11-03 02:21
Correction: Ignore me! Can reproduce the sub `MND/2` and I see the problem!

**Comment by rude-jerk** [comment] 2020-11-10 00:19
Resolved in November 9, 2020 patch.

**Closed by rude-jerk** 2020-11-10 00:19 UTC
Labels: Combat, Job
