### ISSUE TITLE
Ranged mobs

### ISSUE THREAD

**Issue by Qair** [EdenServer/community#1373] opened 2019-03-23 18:06 UTC
The formula for mobs that use ranged attacks needs to be reviewed. Not only are they stupidly accurate but they do a massive amount of damage. For instance, the ninja yags are hitting my 75 monk with near 100% acc regardless of being 10 levels below me. Also, if anyone has fought goblin rangers lately, it's like trying to fight a cannon. 100-160 damage on ras.

**Comment by godmode** [comment] 2019-03-23 18:18
I believe there is an open ticket for this. I haven’t checked again yet. Did you search the bug reports before posting?

**Comment by bkesecker** [comment] 2019-03-23 18:22
I closed a duplicate of this same issue today.

**Comment by bkesecker** [comment] 2019-03-23 18:24
https://github.com/EdenServer/community/issues/895

**Comment by bkesecker** [comment] 2019-03-23 18:24
This issue is a bit more inclusive.

**Comment by Altnob** [comment] 2019-03-24 13:26
To add to this, they hardly ever run in to melee you. If you're out of melee range they're just going to stand there and power blast your ass with RAs

**Comment by Serephim** [comment] 2019-03-30 03:43
Yeah the goblin rangers in bibiki bay are retardedly powerful. They hit for like 250-300 each arrow and they shoot fast. lol

**Comment by greyenvy** [comment] 2019-03-30 03:47
The Goblin Poachers in Yhoator would hit opos and crawlers for over 200/shot at times.  The formula definitely seems OP.

**Comment by Balrahn** [comment] 2020-06-07 20:51
> 
> 
> The Goblin Poachers in Yhoator would hit opos and crawlers for over 200/shot at times. The formula definitely seems OP.

Bitch please
![Captaaaaaure](https://user-images.githubusercontent.com/12987658/83979809-4d9e9c80-a911-11ea-8701-c60b9bc2928a.JPG)

**Closed** 2020-06-10 01:54 UTC
