### ISSUE TITLE
Beastmaster: Charmed pets don't seem to lose enmity after BST dies

### ISSUE THREAD

**Issue by DeuceFFXI** [EdenServer/community#5806] opened 2023-11-02 19:48 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Went to raise a Beastmaster in  Boyahda Tree earlier who I believe died to their charmed pet, a Korrigan, or a failed charm on one.  The Korrigan remained standing on their body at 20% HP.  Casting tractor on the beastmaster didn't seem to cause any issue; however, after the tractor was accepted, the Korrigan immediately became aggressive to myself, the person who tractored them.

So, it seems the Korrigan didn't recognize the Beastmaster was dead and still had them on their hate table, which then led to the accepted tractor passing aggro to me.  I'm not sure if the Beastmaster died to an enemy or the Korrigan came uncharmed and killed them.  Regardless, really strange bug.

**Comment by Mozzy4Ever** [comment] 2023-11-02 21:09
Duplicate of https://github.com/EdenServer/community/issues/4649

**Comment by DeuceFFXI** [comment] 2023-11-02 21:13
Ah my bad, only searched for "beastmaster"

**Closed** 2023-11-03 22:58 UTC
