### ISSUE TITLE
San D'oria Mission 2-3 Journey to Bastok (Bastok Dragon Fight)

### ISSUE THREAD

**Issue by LunchEden** [EdenServer/community#735] opened 2019-01-11 16:26 UTC
I completed all the prereqs to the dragon fight last year back on Kupo. I completed the Windurst segment (trading shields to Halver), started the Bastok segment (Journey to Bastok), and spoke with Savae E Paleade, then Pius, then Grohm. I appear to be getting the correct dialogue from these Npcs (Grohm speaks of investigating a "strange circle"). However when I click on the burning circle in the Palaborough Mines it does not allow me the option to enter (only option is "None."). I've went back several times and spoke to the appropriate Npcs, relogged, re zoned, and nothing appears to work. It seems I can't advance the mission into the fight and I'm in some sort of weird limbo. I also do not appear to have the "Dark Key" key item although I'm not sure if that is required for the Bastok fight.

My player name is "Lunch" and this is 2-3 Journey to Bastok.

edit: this issue seems to mirror mine - https://github.com/EdenServer/community/issues/556

**Comment by godmode** [comment] 2019-01-12 15:04
Duplicate of #556

**Closed by godmode** 2019-01-12 15:04 UTC
