### ISSUE TITLE
Bird Blood price still inaccurate

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/community#156] opened 2018-10-13 05:27 UTC
Before SE nerfed bird blood farming due to RMT, it was priced at ~300-342gil. It was changed on December 8th, 2008 according to Wiki. https://ffxiclopedia.wikia.com/wiki/Bird_Blood?diff=725235&oldid=713471 was the last change to the page prior to December 8th. I realize that 2008/2009 is the era of the server from what I can tell (haven't heard of any set date) but I believe that since the change in price was due to RMT which we don't have on this server, it'd be nice for new players to have something they can farm for gil. The price currently is ~153 which is less than half of what it used to be

#108 was supposed to update it, but after patch it's still 153 each

**Comment by godmode** [comment] 2018-10-13 05:47
Duplicate of #108

**Closed by godmode** 2018-10-13 05:47 UTC

**Comment by JigokunoOusama** [comment] 2018-11-30 08:38
Seems like all I see farming out there are lazy higher level players.

**Comment by godmode** [comment] 2018-11-30 12:11
We do post nerf prices. He was posting this in order to correct the from 150~ price to 300~ price. So it is intentionally set that high. If you see other prices that are nerfed please report them and we can fix it. Thanks!
