### ISSUE TITLE
Sanction duration too long

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5893] opened 2024-07-07 12:53 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [ ] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

https://ffxiclopedia.fandom.com/wiki/Sanction

Corporal sanction on Eden is lasting 7 hours. ffxi wiki show sanction max duration is 6 hours

**Comment by ReportingRegret** [comment] 2024-07-08 02:21
ffxiclopedia is not always accurate. e.g., when you roll back that page to July 2008, it says 6 hours "Verified" at Lance Corporal rank and then shorter times at higher ranks inexplicably.
Also, other wikis give different info, e.g., https://ffxi.gamerescape.com/wiki/Astral_Candescence says 8 hours

**Comment by DeuceFFXI** [comment] 2024-07-09 00:16
A lot of the wiki pages regarding sanction are constructed poorly and are misleading.  As far as I know and have checked, Sanction/Signet durations were never changed and have stayed consistent.  It may have already been confirmed by a developer, but I can probably rank up again on retail and check.  I still need to get my character to Lance Corporal.  

The shorter sanction durations are related to possession of the Astral Candescence, which isn't currently a mechanic on Eden.

**Comment by Slamm21** [comment] 2024-07-09 08:46
Sanction should start at 3 hours and then increases by 30 minutes for each rank with a max of 8 hours at captain

**Comment by DeuceFFXI** [comment] 2024-07-10 02:02
> Sanction should start at 3 hours and then increases by 30 minutes for each rank with a max of 8 hours at captain

This is not true.

One of the Japanese wiki pages for [Sanction](https://wiki.ffo.jp/html/706.html) has the times listed, which corroborates the claim of a six hour max duration.  I just ranked up to Sergeant on retail, which is #6 on the table of that JP wiki page and confirmed that sanction lasts 6 hours at that rank.  Prior to ranking up I did the same for Corporal.

I've seen the claim that sanction can last up to 8 hours on a couple NA wiki pages, but based on what I've gathered on retail so far that doesn't seem likely.  As I continue to rank up in the future on retail I'll keep an eye out for any discrepancies with the JP wiki page.  For now, I believe it's accurate.

**Comment by Slamm21** [comment] 2024-07-10 15:56
> > Sanction should start at 3 hours and then increases by 30 minutes for each rank with a max of 8 hours at captain
> 
> This is not true.
> 
> One of the Japanese wiki pages for [Sanction](https://wiki.ffo.jp/html/706.html) has the times listed, which corroborates the claim of a six hour max duration. I just ranked up to Sergeant on retail, which is #6 on the table of that JP wiki page and confirmed that sanction lasts 6 hours at that rank. Prior to ranking up I did the same for Corporal.
> 
> I've seen the claim that sanction can last up to 8 hours on a couple NA wiki pages, but based on what I've gathered on retail so far that doesn't seem likely. As I continue to rank up in the future on retail I'll keep an eye out for any discrepancies with the JP wiki page. For now, I believe it's accurate.

Testing with retail would be great yeah, but it seems very odd if the max duration listed on bg wiki is wrong
https://www.bg-wiki.com/ffxi/Astral_Candescence

I can completely understand someone guessing at the ranks in between but you would think the current retail players all at captain would know if it is 6 or 8 hours.

Did you first get 6 hours at rank 4 like it says?
If it does go to 8, I would not be surprised if 8 is at FL with captain just giving the additional tag and free warps as a bonus

**Comment by DeuceFFXI** [comment] 2024-07-10 23:47
BG wiki having inaccuracies on certain pages isn't odd when you understand the history of it.  For context, BG-wiki was created due to drama surrounding FFXIclopedia around 2007.  Many of the people who contributed to FFXIclopedia went over to BG-wiki and a lot of content was simply copy/pasted from one wiki to another at the time.  Later on, as BG-wiki became more popular, many contributions were made, and numerous pages were improved upon.  However, there are still many pages that lack a lot of critical information, because those pages aren't looked at very often.

**Comment by Slamm21** [comment] 2024-07-11 01:56
I know all the history, but that info was added out of era on the page lol.

**Comment by 59blargedy** [comment] 2024-07-11 02:23
guys, it is 6 hours as captain on retail. 
you can stop now unless there's a patch note saying anything about sanction duration being shortened.

**Comment by 59blargedy** [comment] 2024-07-14 19:43
resolved in July 12, 2024 maintenance.

**Closed by 59blargedy** 2024-07-14 19:43 UTC
