### ISSUE TITLE
Beastmaster - with DOT or damage to pet cancels Stay

### ISSUE THREAD

**Issue by Nyoomy** [EdenServer/community#1035] opened 2019-02-18 03:09 UTC
After talking about it in the Discord, I decided to jump on retail to test a few things, and I've captured footage (and by habit at this point when recording footage of retail, packets! Maybe they'll be useful maybe they won't, never hurts though!) of my findings.

The current iteration of both Stay and Leave on Eden/DSP are incorrect.

**Stay**
Currently acts like telling a pet to activate /heal command. This is close, but it stops working in two circumstances where it shouldn't. If a pet has a DoT or is under attack, it currently cancels it's Stay command and runs to it's master.

The only time a pet should ignore a Stay command is if it is actively engaged in combat itself (Read: Actually attacking an enemy. If it's being attacked but is itself idle, it will Stay, as seen below). The heal effect is cancelled whilst it's being attacked, probably the timer resets every time the mob takes damage, either from mob attacks or DoT tics.

https://www.youtube.com/watch?v=ZqGq0jQX0Bw&feature=youtu.be

**Leave**

Currently, using Leave on a pet makes it active instantly. This means that if you use Leave on an aggressive pet, it will instantly aggro anyone close to it (Often times, the Beastmaster who forgets that this is a thing).

There is a roughly 5~10 second grace period where the pet is inactive, idling with no actions whatsoever. As soon as this period ends, it resumes normal functioning, such as movement and aggressive behaviour. I looked back to 2005 pages of posts talking about Leave and can confirm this was the correct behaviour back then pre-MPK patch, too.

https://www.youtube.com/watch?v=ILqlxXmK4n4&feature=youtu.be

**Comment by gweivyth** [comment] 2019-02-18 04:43
Can confirm the second part, we used to summoner pull things in Dynamis all the time abusing this behavior.

**Comment by Nimlith** [comment] 2019-02-18 18:45
Also it seems once you leave your pet it doesn't regen at the same rate as era, taking much longer. Trying to find some footage from era but having no luck, but definitely feels off!

**Comment by godmode** [comment] 2019-08-24 13:12
I believe this was fixed in June. Please comment if it wasn't.

**Comment by Wade9363** [comment] 2019-08-24 15:07
The pet's becoming active immediately after leave was fixed several months ago.

The issue of pets not obeying the Stay command is still not resolved.  As soon as a stayed pet takes damage it immediately Heel's back to the player.  

Just confirmed this is still an issue as of 8/24/19

**Comment by bkesecker** [comment] 2019-11-12 02:44
Reopening to get DoT stay issue looked at again.

**Comment by Wade9363** [comment] 2019-11-12 04:21
The original issue of pets heeling back immediately on taking damage is confirmed as of 11/11/19: both from an active DoT or getting hit by a mob.  The original text is correct and the expected behavior or pets only ignoring a stay command when currently engaged is ear correct.

> Stay
Currently acts like telling a pet to activate /heal command. This is close, but it stops working in two circumstances where it shouldn't. If a pet has a DoT or is under attack, it currently cancels it's Stay command and runs to it's master.

The only time a pet should ignore a Stay command is if it is actively engaged in combat itself (Read: Actually attacking an enemy. If it's being attacked but is itself idle, it will Stay, as seen below). The heal effect is cancelled whilst it's being attacked, probably the timer resets every time the mob takes damage, either from mob attacks or DoT tics.

https://www.youtube.com/watch?v=ZqGq0jQX0Bw&feature=youtu.be>

**Comment by mlandrum22** [comment] 2019-11-13 16:47
While we're on Stay. Stay should not reduce pets TP and should be regening HP much faster than it currently is. It looks like Eden's Stay is what the natural regen should be out of battle, and the Stay should speed up the regen considerably. 

See: #2171

**Comment by KnowOne134** [comment] 2020-08-26 01:58
all is fixed except stay not staying active if pet takes damage

**Comment by KnowOne134** [comment] 2023-11-22 03:05
this was resolved some time ago

**Closed by KnowOne134** 2023-11-22 03:05 UTC
Labels: Job
