### ISSUE TITLE
Sprinklers instantly respawning on the way to Suzaku

### ISSUE THREAD

**Issue by Treble011** [EdenServer/community#1308] opened 2019-03-17 03:47 UTC
The Sprinklers on the staircase leading to the teleporter to Suzaku Island respawn instantly.

Obviously, they should not be. The Sprinklers on the way to Seiryu behaved normally.

**Comment by HunnyDoo** [comment] 2019-03-18 10:08
Can confirm this is true, they come out and of the stairs like an infinite conveyer belt. Finally a monk merit camp! (Joking)

**Comment by godmode** [comment] 2019-05-09 00:51
I was unable to reproduce this. Does this still happen?

**Comment by KnowOne134** [comment] 2022-02-21 01:40
unable to reporduce either closing issue

**Closed by KnowOne134** 2022-02-21 01:40 UTC
