### ISSUE TITLE
Energy Steal & Energy Drain Dagger WS Broken?

### ISSUE THREAD

**Issue by Nyur0** [EdenServer/community#2874] opened 2020-05-20 09:34 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

Hey everyone,

I'm currently 65THF/WHM in Sea Serpent Grotto. Been testing out the 'Energy Drain' and 'Energy Steal' Dagger WS on Royal Leeches (Lv. 35~38). WS animation goes off, but no record of MP being consumed. Can someone look into this?

version 30181205_0

Hit me up in game if you need more info! :)

Nyuro

![energydrain](https://user-images.githubusercontent.com/65654611/82430497-61b25500-9a5b-11ea-9664-86d20d801feb.jpg)
![energysteal](https://user-images.githubusercontent.com/65654611/82430499-61b25500-9a5b-11ea-861e-d3773026be29.jpg)

**Comment by Nyur0** [comment] 2020-05-20 09:36
There is an open case from 2019 it seems, but I wanted to re-address if possible as /whm is a viable sub for my farming.

**Comment by iklarazu** [comment] 2020-05-20 10:26
The original post is [here.](https://github.com/EdenServer/community/issues/1460)

@isotor linked to the WS lua scripts on DSP, as they're pretty much dead; [Energy Drain](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_drain.lua) and [Energy Steal.](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/energy_steal.lua)

I've noticed that the club WS [Starlight](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/starlight.lua )  and [Moonlight](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/moonlight.lua) also probably don't do what they're supposed to, though I don't have club skill that high to test.

The only MP restoring WS that looks complete on DSP is [Spirit Taker.](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/spirit_taker.lua)

It should be noted however ST converts damage dealt into MP, whereas Energy Steal/Drain 'steal' MP, if the target has it. On that note, and I don't know if it helps but going to link anyway for info, but [Sanguine Blade](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills/sanguine_blade.lua) is damage to HP, that may help to compare.

**Comment by Volkaru** [comment] 2020-05-20 15:03
Starlight and Moonlight function properly on eden. Please reference/comment on a previous bug report instead of making a new one if you've already searched for and found it. Duplicate of #1460

**Closed by Volkaru** 2020-05-20 15:03 UTC
