### ISSUE TITLE
Can not purchase Goldsmith's Ring from Ellard

### ISSUE THREAD

**Issue by apessius** [EdenServer/community#4937] opened 2022-03-03 04:54 UTC
Ellard is a guy in the goldsmithing guild. He is supposed to give you items in exchange for GP. He forgot how to give a goldsmith's ring. This is in Eden era.

Steps to reproduce:
1. Be a leet goldsmither 
2. Get leet goldsmithing points, like over 80000
3. Tell Ellard you want the ring
4. Ellard acts stupid and doesn't give you the ring

Proof is because it doesn't work

ver 30181205_0
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [x ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by E5una** [comment] 2022-03-03 11:39
This item was added in the June 9th 2008 patch so it is not missing from current Eden but will presumably be added when Eden's 2008 patch drops. Until then please hold off on bug reporting missing 2008 content. Ty for the report either way though

**Comment by E5una** [comment] 2022-03-03 11:46
Closing as a duplicate of https://github.com/EdenServer/community/issues/4832

**Closed by E5una** 2022-03-03 11:46 UTC
