### ISSUE TITLE
Charm

### ISSUE THREAD

**Issue by 00coca** [EdenServer/community#2900] opened 2020-05-26 18:41 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window) Version 30181205_0

### Details
I have been getting miss charms, I wouldn't complain about the odd one, but I am getting destroyed, lvl 40 bst, +16chr sea serpent grotto, could not land charm on crab decent challenge, 7 miss charms in a row, tame does not work, death.  This made me almost cry, a definite WTF moment. With this set up I can land a tough, last 90 seconds. easy prey 5 min. these are really out of line, I played shiva at NA Launch, easy prey are supposed to last almost an hour, then ticks down from there, used to be able to charm a tough in this era and 2 hour to keep 30 min or longer. The main issues is landing a charm, accuracy of this is out of whack, also the duration is out too, tough should be 7.5 min, even match 12.5-15 min, decent challange 15-45min, easy prey should be 30-60 min, too weak should be 60+ min. 

As far as I know, charisma is to land or accuracy of the claim
charm is the duration, which is based on a formula of chr + charm 
sic has a super long recast time, could it be fixed that it is reset with a new mob? instead of the 3.5 min recast time?
also

The way pets act, they will not intercept target, target has to hit u first, before pet will attack, I notice this in pet swapping.

This is the nuts and bolts of this class until 75 charming a pet ect. Now if warriors provoke missed as much as charm that would be funny or not funny depending, or shield bash misses like tame, or  boost makes attack go up but will always miss target, these would make each class way less desirable to play, but still playable to some degree, I ask that we make these small changes to each of these classes "joking of course" if we can not fix charm and tame and length of hold, sic, ect.

I would really like some help on these issues, it may not be noticeable for a 75, with full af but the grind up to it sure is as several of the other bsts I have met say as well. the charm gods can be cruel, lets hope the eden coders can be sympathetic to the bsts of eden.
cheers

**Comment by statuseffect** [comment] 2020-06-01 18:37
Even with 70+ BST me and my duo partner are experiencing the same issues with poor Charm accuracy, even with Apollo's and HQ charm gear. We are getting high miss charms on DC mobs causing us to die as Tame does not work as intended. 

This needs to be addressed. Also the level difference formula on charmed pets needs to be looked at as well. There's camps that are supposed to be great at my level range that are utter garbage because the pets allowed are too weak for the target mobs. IE: Bibiki with Catoblepas and Cardarva mire with Karakul pets on Imps.

**Comment by 59blargedy** [comment] 2022-11-21 15:46
resolved in November 21, 2022 update

**Closed by 59blargedy** 2022-11-21 15:46 UTC
Labels: Job
