### ISSUE TITLE
Nyzul Weapon not dropping

### ISSUE THREAD

**Issue by DeepupuImouto** [EdenServer/community#4896] opened 2022-02-15 06:13 UTC
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)
- [ x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
ver 30181205_0

Juul says this is a unique issue shes only seen me deal with so even though theres simliar posts in bug reports I just assume this is different.

I cleared Nyzul floors1-100 prior and on my 2nd clear of nyzul on Oniichan I took us up and didnt get the right weapon. 

Honestly Im confused as to how this is suppose to work and if Im just retarded and this is how its intended to work, but Juul asked me to submit a bug report and provide the documentation so here it is.

Attached is the logs of every nyzul run Ive done on Oniichan and screenshots.
[Oniichan_2022.01.11.log](https://github.com/EdenServer/community/files/8066315/Oniichan_2022.01.11.log)
[Oniichan_2022.01.14.log](https://github.com/EdenServer/community/files/8066316/Oniichan_2022.01.14.log)
[Oniichan_2022.01.17.log](https://github.com/EdenServer/community/files/8066317/Oniichan_2022.01.17.log)
[Oniichan_2022.01.20.log](https://github.com/EdenServer/community/files/8066318/Oniichan_2022.01.20.log)
[Oniichan_2022.01.24.log](https://github.com/EdenServer/community/files/8066319/Oniichan_2022.01.24.log)
[Oniichan_2022.01.28.log](https://github.com/EdenServer/community/files/8066320/Oniichan_2022.01.28.log)
[Oniichan_2022.02.01.log](https://github.com/EdenServer/community/files/8066321/Oniichan_2022.02.01.log)
[Oniichan_2022.02.04.log](https://github.com/EdenServer/community/files/8066322/Oniichan_2022.02.04.log)
[Oniichan_2022.02.08.log](https://github.com/EdenServer/community/files/8066323/Oniichan_2022.02.08.log)
[Oniichan_2022.02.14.log](https://github.com/EdenServer/community/files/8066324/Oniichan_2022.02.14.log)
![Oniichan_2022 02 14_103014](https://user-images.githubusercontent.com/99710485/154002874-e4896234-3c2f-42f2-a260-3595f3850aba.png)
![Oniichan_2022 02 14_103034](https://user-images.githubusercontent.com/99710485/154002876-6b5e6aea-c24d-47ad-8367-8b6e7c0c00b0.png)
![Oniichan_2022 02 14_103110](https://user-images.githubusercontent.com/99710485/154002878-6e9e0469-2c4f-45c2-ab13-ab5b4fdea490.png)
![Raddick_2022](https://user-images.githubusercontent.com/99710485/154002882-fb8c8c41-6cc9-489d-a2fa-c19c364b6e26.png)

**Comment by falzum** [comment] 2022-02-15 10:17
Do you have the runic key?

**Comment by ConteAlmaviva** [comment] 2022-02-15 20:25
At present, I believe the behavior is this:

1. first clear of 96-100 - only one random weapon drop, no Runic Key KI obtained. *MUST* exit Nyzul on floor 100 to record data up to floor 100, otherwise it will not properly save progress up to floor 100.
2. Second clear of 96-100, with progress up to floor 100 saved - only one random weapon drop, Runic Key KI obtained.
3. Third clear of 96-100 (and presumably every clear thereafter) with the Runic Key in the possession of the person who took you up to floor 96 - two weapon drops, one matching the job of the person who took you up, the other randomly selected.

The prominent bug here seems to be not obtaining the Runic Key on your first clear of 96-100; I think Juul has a separate bug report on that. The September 2008 retail update notes have something about possession of the Runic Key not being required for a guaranteed weapon drop, but I do not know if prior to that update, having the Runic Key was a requirement for the guaranteed weapon drop (or if there was no guaranteed weapon drop at all.)

**Comment by KnowOne134** [comment] 2022-02-16 02:06
duplicate of https://github.com/EdenServer/community/issues/4887

**Closed by KnowOne134** 2022-02-16 02:06 UTC
