### ISSUE TITLE
Willpower torque quest currently not working.

### ISSUE THREAD

**Issue by Elysien** [EdenServer/community#3154] opened 2020-08-03 14:25 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Please fix, the torque is integral to a **_good_** RDM Utsusemi;Ichi SiD set :<

https://ffxiclopedia.fandom.com/wiki/Tea_with_a_Tonberry%3F
The NPC in which to start the quest is completely unresponsive.

**Comment by rude-jerk** [comment] 2020-10-28 23:52
Dupe of https://github.com/EdenServer/community/issues/2269

https://github.com/project-topaz/topaz/pull/1450

**Closed** 2020-11-30 16:15 UTC
Labels: Quest/Mission
