### ISSUE TITLE
Ranged attack shot cooldown

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#859] opened 2019-01-27 04:41 UTC
If you are out of range of a mob, or even not correctly facing a mob and attempt a ranged attack, the cooldown for the shot begins no matter what.  You must then WAIT for the cooldown to end before being able to take another shot.  Its pretty brutal if you mess up and just want to take a shot. 

Matty was kind enough to make a clip of it in action.  https://www.twitch.tv/thris_straizo/clip/BlushingBrightOrcaDBstyle?filter=clips&range=7d&sort=time

**Comment by godmode** [comment] 2019-03-16 12:03
Duplicate of #859

**Comment by Balrahn** [comment] 2019-03-16 13:28
I'm confused, my bug got closed as a duplicate referring to this bug report. My issue is not the same however. Ranged attack against a mob can be done within 25 yalms. Say if you start your ranged attack at 24 yalms and before the shot goes off, the mob has moved to say 30 yalms. Then the ranged attack gets interrupted because the mob is now out of range. This is not how ranged attack works on retail. As long as the ranged attack got started within range, it should always go off. Now for a player the shot will always get interrupted, but mobs however can easily start their shot at 24 yalms and you can run to 40 yalms and still get hit. I find this very in favour of the beastmen and think it should get evened out!

**Comment by godmode** [comment] 2019-03-16 14:25
Good call, that’s my mistake.

**Closed** 2019-04-20 11:55 UTC
Labels: in-code-review

**Comment by 59blargedy** [comment] 2020-03-26 19:44
not sure if this was fixed based on recent reports from players, though i have not tested myself. here's some data from retail:

Retail behavior shows that the mob can go far out of range (33 yalms) and still be hit/have the ra claim the mob
https://youtu.be/SHEs5cjBg2E

sort of tangential to this ticket but including it anyway:
spells _should_ cut off if out of range, but be able to be cast at 21.5 (testing range first, cutoff is at end). 
https://youtu.be/XHVqo2tSqzA

songs should cut off but be able to be cast at 21.5 (testing range first on threnody, cutoff is at end, horn equipped)
https://youtu.be/LCXBHzgyM5Y
