### ISSUE TITLE
Issue with quest https://ffxiclopedia.fandom.com/wiki/Onion_Rings

### ISSUE THREAD

**Issue by MGramolini** [EdenServer/community#947] opened 2019-02-10 19:58 UTC
Did not receive reward of https://ffxiclopedia.fandom.com/wiki/Bouncer_Club

**Comment by Shoruto** [comment] 2019-04-27 13:56
Submit a GM ticket

**Comment by MGramolini** [comment] 2019-04-27 18:10
Should I still submit a GM ticket after 3 months?

**Comment by Shoruto** [comment] 2019-04-27 19:40
If you want the club and you met the requirements.

**Comment by MGramolini** [comment] 2019-04-27 22:17
Back when I made this issue GMs didn’t have that ability and told me to make this bug report. So which is it?

**Comment by Shoruto** [comment] 2019-04-27 23:54
Leave it here to be looked at

**Comment by bkesecker** [comment] 2019-10-13 19:55
The quest logic seems to require the player to be above a certain rank, zoned, and talk to Kohlo-Lakolo.  Have you tried talking to Kohlo-Lakolo again?

**Comment by bkesecker** [comment] 2019-10-13 20:30
The issue seems to be if Crying Over Onions is started, and the Bouncer Club has yet to be received, Crying Over Onions will block getting the club until Crying Over  Onions is completed.

**Comment by Althaia** [comment] 2019-10-18 18:55
So when I was doing my Rank 3-1 mission, I picked up the Old Ring, thinking that I'd go back to Kohlo-Lakolo and flag this quest after "Inspector's Gadget!" ~ I'm pretty sure I had completed Inspector's Gadget at this point, but I'm not sure....

I received some sort of cutscene at the House of the Hero at some point (I think I was there for some rank or quest and got the CS unexpectedly upon clicking on the Door an extra time), in which they'd already gotten into the House of the Hero. This seems odd, because it's the old ring that would've allowed them to enter it, and I hadn't flagged "Onion Rings" at that point yet, as far as I knew.

Well, anyway, I eventually got back to Kohlo-Lakolo, with the Old Ring key item, and instead got the dialogue for "Crying Over Onions." So I went to the NPC in south Waters (Honoi-Gomoi) and got the low-down on how I'd have to kill some Level 60+ cactuar to finish that quest.

I figured I'd try "Onion Rings" again after completing "Crying Over Onions," which hasn't happened yet, even though "Onion Rings" is supposed to be after "Crying Over Onions." I just looked at my quest log, however, and it shows "Onion Rings" as being completed!

I still have the old ring in my Temporary Key items. Maybe I'm supposed to keep it to be able to access the House of the Hero for future quests? I dunno. Clearly something odd was happening back then, but I didn't make a report 'cos I didn't know enough about the Star Onion Brigade's storyline to really get what was going on.

Now it's months later and my memory's a little hazy; all I know is I didn't get the Bouncer Club reward, so clearly something went wonky with "Onion Rings." Perhaps the problem was caused by me getting the old ring before talking to Kohlo-Lakolo? Or that premature cutscene at the house screwed it up? I forget the exact order of events, sorry, but I know I didn't get the club.

Looking at the sales history of the item, it looks like at least one person was able to successfully get the club; it sold in May 2019:

https://edenxi.com/db/items/17029/bouncer_club

**Comment by Mahou81** [comment] 2020-04-22 13:24
BUMP! Did not receive reward after finishing this quest with both my main and alt. I don't care much about the reward myself, but it seems like a small thing that could easily be fixed!

**Comment by Spiffly** [comment] 2020-06-02 22:52
I have just completed this quest and also didn't receive the reward. I have tried zoning, talking to Kohlo-Lakolo again and nothing. I'm San d'Orian if that seems to make a difference? He just jumped straight to the next quest, i got no ackowledgement i had completed Onion Rings at all from him.

Not fussed about the rewards, just bumping to show it's still an issue.

**Comment by 59blargedy** [comment] 2021-11-29 16:45
resolved in November 29, 2021 update

**Closed by 59blargedy** 2021-11-29 16:45 UTC
Labels: Quest/Mission
