### ISSUE TITLE
Minstrel's Ring Latent Not Activating Under Correct Conditions

### ISSUE THREAD

**Issue by RenaviOnEden** [EdenServer/community#2597] opened 2020-04-01 08:57 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Minstrel's Ring is currently not working correctly, as it is only counting yellow hp from your base naked HP rather than your maximum HP at the start of the cast.  I've added +HP before starting songs in order to drop my HP % to 70ish without the latent activating at all, even if I keep that same % through the entire cast.  It also only needs to be equipped at the start of the cast, not until the end, which is different than other JSE rings.
Easy way to test is to drop HP to 75% of your base naked HP and see if latent activates.  Heal to full and then add +HP gear so that your base HP is only 75% of your current maximum to see if latent activates.  

version 30181205_0

**Comment by freddiepines** [comment] 2020-04-07 13:09
Confirmed, it's working exactly as stated above and not functioning properly.

**Comment by VirtuosusFFXI** [comment] 2020-06-02 04:00
This is affecting both Sorcerer's Ring and Medicine Ring, and presumably every other latent in the game that uses base HP to proc. They are all using your naked HP as your "base" HP. They should be using your currently equipped gear, excluding Convert HP>MP or MP>HP pieces, to determine the proc.

**Comment by VirtuosusFFXI** [comment] 2020-06-02 04:03
Important to note, however, that different rings seem to follow different rules:

https://ffxiclopedia.fandom.com/wiki/Sorcerer%27s_Ring

https://ffxiclopedia.fandom.com/wiki/Medicine_Ring

https://ffxiclopedia.fandom.com/wiki/Minstrel%27s_Ring

Might be a bit more complex to fix.

**Comment by VirtuosusFFXI** [comment] 2020-08-20 20:01
I believe the issue lies here: https://github.com/project-topaz/topaz/blob/8648c4071c1885ad1a388d74e7f868e39df2f75e/src/map/latent_effect_container.cpp#L703

`    case LATENT_HP_UNDER_TP_UNDER_100:
        expression = ((float)m_POwner->health.hp / m_POwner->health.maxhp) * 100 <= latentEffect.GetConditionsValue() && m_POwner->health.tp < 1000;
        break;`

health.maxhp is probably just taking your naked HP and not accounting for any HP added via equipment. This would need to be fixed for basically every HP and MP related latent listed there, assuming this is what is being used to determine whether the latent should activate or not. Maybe someone with a bit of coding knowledge (not me lol) can figure it out.

**Comment by VirtuosusFFXI** [comment] 2021-07-14 12:21
Just an update on this, as I have done some more recent testing:

Currently, because all HP and MP latent items use your base naked (no gear equipped) HP and MP, it is impossible to do some things that could be done in era. One example of this is the use of Uggalepih Pendant on jobs that do not have natural MP. Any non-mage job wanting to use Uggalepih Pendant on actions (examples include: COR Quick Draw, all Magical/Hybrid WS, etc) are unable to do so without putting at least 1 merit into MP. Even if you do put that merit into MP, you must then also pre-convert that MP off to get down to 5 MP or lower for it to even proc. 

The other issues are obviously that BRDs cannot rely on HP+ gear at the start of song casts to trigger their ring, and must instead lower their HP and survivability. Mages in general that are wanting to nuke will also have their Uggalepih Pendant latent active much less than era. For example, a BLM might have 1000 MP in their nuke set, but their naked MP is 800 and thus they only proc latent at 408/1000 or lower.

Examples: 
1) My COR/NIN has 30 MP in Quick Draw set (including Uggalepih Pendant) but my naked MP is 0. Even if I Quick Draw in 0/30 (0%) MP, Uggalepih Pendant will never proc.

2) My COR/WHM has 224 MP in Quick Draw set (including Uggalepih Pendant) but my naked MP is 194, and therefore I must reach floor(194 * 0.51) MP before the latent will proc. This is 98/224, or 43.75% total MP. 

From what I have found, this is how Uggalepih Pendant should function: 

![pendant](https://user-images.githubusercontent.com/49970272/125620667-59809f6a-18d4-4806-8935-a754bbe2ac03.png)

From: https://ffxiclopedia.fandom.com/wiki/COR_Quick_Draw_Guide_by_Arekkusu

If anyone is willing, retail testing on things like Uggalepih Pendant and lv 50 JSE Ring latents would go a long way into figuring out exactly how these all work and (hopefully) lead to a fix to these issues.

**Comment by 59blargedy** [comment] 2021-11-29 16:41
resolved in November 29, 2021 update. to note, currently it is all gear and not visible gear until that piece is validated on retail firmly

**Closed by 59blargedy** 2021-11-29 16:41 UTC
