### ISSUE TITLE
Golden Salvage: How to turn the correct chest into a Mimic.

### ISSUE THREAD

**Issue by IsaOsa** [EdenServer/community#3521] opened 2020-12-22 09:55 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

ver30181205_0
 
So after having messed this assault up countless times due to getting 12 Mimics, i believe we've finally figured out
the cause of this. When you let a chest turn into a Mimic and head for the next chest without letting the previous
chest settle back into npc mode so to speak. You can turn the correct chest into a Mimic as well. Since this assault
is cleared by SMN who are forced (avatar auto-attack on entities aggresive towards caster) to let the previous 
aggroed chests settle again noone else should've run into this.
Leaving enough time in between checking chests should prevent this from ever happening.

**Comment by Zidane-Quina** [comment] 2020-12-27 23:39
Just ran this 3 times with 2 SMNs.  We found out about this bug report after losing our first run after checking all 12 chests.  2nd run we communicated to ensure each other's mimics despawned back to Green text/NPC form. Ended up winning.  However, on the 3rd run we communicated for chest despawns and still got 12 mimics and lost. There were 2 chests on our last run that did not immediately turn into mimics in agro range. We had to click them and we got the dialogue "The chest contains...."  Then a mimic appeared. I thought this is the way all mimics were supposed to work but when I asked on Eden Discord I was told that the chests should agro when in range (around 8 yalms).  All of the other chests agroed like this so apparently there are 2 types of spawning mimics in this assault?  Looks like waiting for mimics to change back into NPC form isn't a gauranteed fix.

**Comment by KnowOne134** [comment] 2020-12-30 03:36
the winning chest doesnt agro so this shouldnt happen at all, now calling your pet while still having a chest agroed to you will make your pet go after that chest, but never the winning one. There is an issue with being able to use macroes to send pets at these npcs and if doing so without triggering it correctly in range then you are voiding the chaest of a win.
here as a SS of me standing at the winning chest with carby out chilling. did it 3x in a row no issue.
![image](https://user-images.githubusercontent.com/35616771/103328273-cdab6180-4a1d-11eb-8303-e16169cdabfa.png)

**Comment by KnowOne134** [comment] 2020-12-30 03:37
if there is more info im ears other wise ill close in a few

**Comment by Zidane-Quina** [comment] 2020-12-31 05:49
So the chests not agroing but still was a mimic happened on once or twice. The real issue is checking all 12 chests and none having the idol. We stopped checking separate chests and just stuck together as if SMN solo instead of 2 separate SMN. We are 2/2 since doing this.  Might want to test having 2 SMN split up and open chests at same time. Everyone I've talked to that does 1 chest at a time has never had issues

**Comment by KnowOne134** [comment] 2020-12-31 12:59
How is it a mimic and not agroing? It can only turn into a mimic if it agros or you somehow attack it via macros. Not in mimic form the menu only has trigger option

**Comment by falzum** [comment] 2020-12-31 14:23
I just ran this three times effortlessly. Not saying Zidane is wrong, but as of 20 min ago I had no issues. 

Ran up to the chest with carby out. If the chest aggros, carby saved me. If the chest didn't aggro, clicked it and got the Idol.

**Comment by KnowOne134** [comment] 2020-12-31 14:43
Yes. All I can think of is player error and having the pet attack the box before trying to trigger it or agro

**Comment by Zidane-Quina** [comment] 2020-12-31 22:56
Did you run it with 2 separate SMNs and have multiple mimics up at the same time. Once again. The mimic not agroing only happened in 1 run... the problem is 2 separate SMNs opening separate  chests at the same time. This big was reported by someone else and I am having the same issue. If we solo 1 chest at a time it is fine.

**Comment by Zidane-Quina** [comment] 2021-01-03 22:07
Also wanted to mention I am running 60 cap. Not sure that matters

**Comment by KnowOne134** [comment] 2021-02-28 15:07
closing due to not being able to reproduce

**Closed by KnowOne134** 2021-02-28 15:07 UTC
Labels: Assaults
