### ISSUE TITLE
Windy 4-1 reset bug

### ISSUE THREAD

**Issue by xxxArchangelxxx** [EdenServer/community#4121] opened 2021-03-07 23:53 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I recently completed 4-1 for Windurst and got the title and airship pass. I accidentally spoke with the Bastok consulate and got a cut scene telling me to speak to the arch duke again and that I already possessed the KI to do so. The Windurst consulate told me some message about the Star Syible and I could not progress past that point to complete rank 5.

**Comment by EdenPenance** [comment] 2021-03-08 00:02
This can be closed as a duplicate of #2318 . Updating 2318 with the necessary details as to why this happens.

**Comment by 59blargedy** [comment] 2021-03-08 16:13
closing as duplicate, thanks

**Closed by 59blargedy** 2021-03-08 16:13 UTC
