### ISSUE TITLE
Item Lost in Trade

### ISSUE THREAD

**Issue by Frylokk** [EdenServer/community#244] opened 2018-10-28 00:38 UTC
I, Kronk was buying a Thunder Staff from Mattyg, when we completed the trade he got the gil but the item was lost in the trade. If someone could help me that would be great.

**Comment by MGramolini** [comment] 2018-10-28 00:43
This is Mattyg.  I confirm Kronk purchased a Thunder Staff from me and I received the gil and no longer have the staff.

**Comment by godmode** [comment] 2018-10-30 01:58
Duplicate of #229

**Closed by godmode** 2018-10-30 01:58 UTC
