### ISSUE TITLE
Accuracy Bonus trait for Blue Mage does not confer + 10 accuracy

### ISSUE THREAD

**Issue by Jimmayus** [EdenServer/community#1682] opened 2019-05-22 04:52 UTC
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

see: https://ffxiclopedia.fandom.com/wiki/Blue_Mage/Job_Traits for reference

Blue Mages get the accuracy bonus trait (of _10 accuracy) from setting the two spells 'Frenetic Rip' and 'Dimensional Death'. However, on Eden it does not appear to correctly function. The job trait appears in your traits list, however the accuracy bonus does not seem to be conferred.

Without accuracy bonus in my gear as a BLU64/NIN32  checkparam says I have 304 accuracy. Setting 'Frenetic Rip' and 'Dimensional Death' grants me the accuracy bonus trait in my trait list, but (controlling for the +1 dex from setting DD) I still only have 304 accuracy.

**Comment by Jimmayus** [comment] 2019-05-22 04:53
I'd like to leave a follow-up here just to say that (using the above link in reference once again) the Attack Bonus trait from setting 'Uppercut' + 'Battle Dance' appears to work correctly. I would suggest using that code as a model to work against since they are substantially similar.

**Comment by xizeta** [comment] 2019-05-28 10:46
I checked all of the code, every ID and value is set up correctly. I also tested locally and received +11 Accuracy, using /checkparam (+1 DEX from Dimensional Death).

Please let me know if this is still an issue.

**Comment by Jimmayus** [comment] 2019-05-28 22:02
This is still occurring, I checked as soon as I got home from work today. What is notable, however, and something I didn't notice upon first checking is that _Ranged_ accuracy increased by 10, from 55 to 65 with this equipped. With no spells on checkparam returned 342 primary and secondary accuracy, and with only frenetic rip + dimensional death (and with accuracy bonus trait listed in my trait list) checkparam returned the same values.

**Comment by VirtuosusFFXI** [comment] 2019-05-28 22:07
Yeah, just confirmed the above. Ranged Accuracy went up, but not Melee Accuracy.

[https://i.imgur.com/iCIb7J4.png](url)

**Comment by VirtuosusFFXI** [comment] 2019-06-11 23:16
Looks like this is working now, tested with Frenetic Rip + Dimensional Death and /checkparam <me>.

It is now increasing accuracy by the appropriate amount.

**Comment by xizeta** [comment] 2019-06-12 08:56
@VirtuosusFFXI Thanks for posting your results. I have retested and still can't produce this issue. I'm glad it's working for you. I will close this issue. If anyone encounters this in future, please just reopen.

**Closed by xizeta** 2019-06-12 08:56 UTC
