### ISSUE TITLE
BST 2-Hr Familiar not extending charm to 30mins

### ISSUE THREAD

**Issue by post32015** [EdenServer/community#5116] opened 2022-06-15 02:11 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Solo BST farming subligars in Phomiuna Aqueducts involves charming then immediately using 2-hr to give you 30mins with an IT Oil Slick pet.  I’ve died a few times now with the charm dropping at 25mins.  

easily repeatable.

there was previously a ticket on this matter but it was resolved back in 2020.  As this issue has resurfaced, I am opening a new ticket.

**Comment by post32015** [comment] 2022-06-15 02:13
Previous ticket from 2020 when it was fixed last time is #3214.

**Comment by 59blargedy** [comment] 2022-06-15 02:51
do you have proof of it always being 30 minutes? wiki mentions this:
(era) "While active, Charm status cannot wear off naturally. Since Familiar lasts for up to 30 minutes, a charmed pet will stay with the user for up to 30 minutes from the start of the charm, regardless of level difference." 
(current) "Since Familiar lasts for up to 30 minutes, a charmed pet will stay with the user for up to 30 minutes from the start of the charm, regardless of level difference. Pay close attention to the 'up to 30 minutes' part. It won't always last 30 minutes. Be careful."
both era and current wikis point to a duration that isnt quite a static 30, but if there's an indication somewhere that this is false, please post, otherwise ill close this out.

**Comment by bliven-was-taken** [comment] 2022-06-15 03:09
Slime also have the resist charm trait.

**Comment by 59blargedy** [comment] 2022-06-23 13:36
my gut says it should probably be somewhere more in the line of 27-30 mins, but in the absence of data ill go with the original coder's 25-30 mins and am closing this out as the dreaded 'working as intended'.

**Closed by 59blargedy** 2022-06-23 13:36 UTC
