### ISSUE TITLE
Twinkle Shower Guild Point Turn In

### ISSUE THREAD

**Issue by inaringo** [EdenServer/community#574] opened 2018-12-24 00:37 UTC
https://ffxiclopedia.fandom.com/wiki/Guildworker's_Union

This page says that I should be able to turn in 70.4 Twinkle Showers for 1760 points. When I tried to do so, NPC took all the items and only gave me 350 points. Afterwards I tried turning in one at a time and it gave me 150 points. Tried turning in two and it gave me 145. Then turned in one at a time (each time point total going down by 5) until it went down to 95 and then she stopped taking. So yeah, I don't know how this is supposed to work but seems broken.

**Comment by godmode** [comment] 2018-12-25 14:56
Duplicate of #551

**Closed by godmode** 2018-12-25 14:56 UTC
