### ISSUE TITLE
Zoning between North and South Gustaberg occasionally does not load zone

### ISSUE THREAD

**Issue by tengokujin** [EdenServer/community#2267] opened 2019-12-11 01:51 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

While repeatable, it is not a consistently repeatable problem, so it's a frustrating problem to report.

When zoning between North and South Gustaberg (I usually do this zone on the western zone and this is where I usually observe this problem), my character and UI will load in, but the rest of the zone does not. My character appears to be floating in an inky black void. I am not sure if this is a problem on my end or a problem with server communication. Warping or relogging fixes this problem until the next time it happens.

**Comment by Setz0r** [comment] 2019-12-11 01:54
this is likely related to the new packet updates.  it's intermittent.  will be investigating

**Comment by Volkaru** [comment] 2019-12-11 02:20
This is actually caused by using Amelila's HD mods. Consider using the slightly lower quality version of those mods in this post: https://www.ffxiah.com/forum/topic/51963/ffxi-hd-mods 
If you still want their mod style but don't want to risk the zone being black. Can also happen with their lower jeuno mod

**Comment by godmode** [comment] 2019-12-11 17:09
OP can you confirm if you are using Amelia’s mods?

**Comment by tengokujin** [comment] 2019-12-12 02:14
I just have the HD Overhaul megapack. Amelia's disparate packs were too annoying to individually download and collate.

**Comment by KnowOne134** [comment] 2020-02-13 21:52
Issue is due to tampered client

**Closed by KnowOne134** 2020-02-13 21:52 UTC
