### ISSUE TITLE
Unable to fight back bug when the claimer dies.

### ISSUE THREAD

**Issue by moonyaco** [EdenServer/community#2016] opened 2019-09-06 16:18 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/54994876/64443585-dda28200-d104-11e9-9e4e-388e3c9916f0.png)

What happened was I was fighting 3 goblins, i killed 2 but the 3rd one was attacked by another player who died to it. Thereafter, I am unable to attack back the 3rd goblin due to the error 'Cannot attack - your target is already claimed'. Without the ability to fight back, I am forced to zone

**Comment by beauxq** [comment] 2019-09-07 18:16
duplicate of https://github.com/EdenServer/community/issues/1295

**Comment by 59blargedy** [comment] 2020-05-16 17:13
this should have been resolved by changes to claim/enmity. comment if still seeing this issue

**Closed by 59blargedy** 2020-05-16 17:13 UTC
