### ISSUE TITLE
Party disconnected after Promathia (Dawn) fight

### ISSUE THREAD

**Issue by Cortexx19** [EdenServer/community#5210] opened 2022-08-13 16:30 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details
Twice, the whole zone crashed after killing Promathia (characters outside bc got R0 too.
Logging back in, stuck inside BC with no cutscene or npc inside.

Client Version: 30181205_0
![img_20220813_121045](https://user-images.githubusercontent.com/111193129/184502725-cb4dedc2-2e0d-4eb2-bc10-2a577469ba79.jpg)
![img_20220813_121059](https://user-images.githubusercontent.com/111193129/184502733-2fe31cfb-f66e-4c88-b10f-3ee896da3cc9.jpg)
![img_20220813_121100](https://user-images.githubusercontent.com/111193129/184502743-7c437d39-d324-4a17-a1a7-03c171bf0d46.jpg)

**Comment by KnowOne134** [comment] 2024-10-26 20:10
closing as duplicate of https://github.com/EdenServer/community/issues/4842

**Closed by KnowOne134** 2024-10-26 20:10 UTC
