### ISSUE TITLE
Update 1/21/2019 Broke Ranged Attacks

### ISSUE THREAD

**Issue by CorlaZodren** [EdenServer/community#840] opened 2019-01-24 11:45 UTC
Delays still seem like they are taking the same amount of time to shoot.

Also when you try and use /ra <t> or similar commands to attempt to shoot again before the delay of the first ranged attack is finished it restarts the delay forcing you to wait even longer.

**Comment by godmode** [comment] 2019-01-24 13:35
Duplicate of #832

**Closed by godmode** 2019-01-24 13:35 UTC
