### ISSUE TITLE
EXP Chain #1

### ISSUE THREAD

**Issue by nickycupcakes** [EdenServer/community#1297] opened 2019-03-16 09:39 UTC
I am receiving EXP Chain #1 after killing a DC mob and then an EM or T mob

**Comment by nickycupcakes** [comment] 2019-03-17 08:49
To clarify - I was in Tahrongi Canyon using Level Sync.  I was level 23 or so, synced down to level 17.  

After that we moved on to Buburimu Peninsula and were able to repeat this, again under Level Sync.

**Comment by McLucas** [comment] 2019-03-17 21:08
I was encountering the same issue.  I see this from time to time as I have been bst/whm soloing.  Not sure if it is because I am killing lots of EP/DC/EMs.  Sadly I have not been able easily reproduce this.

**Comment by mlandrum22** [comment] 2019-03-18 00:57
If you kill and EM+, then the DC or less kills reset the chain timer after each kill. Then if you kill an EM+ after those then you can get a chain #1/2/etc. 

It worked like this in Nasomi too, no clue if that's era appropriate or not, been too long.

**Comment by Drognand** [comment] 2019-09-10 15:45
So chains start on any MOB EM and up. Your first or previous mob and start you off as long as it gives exp. If you kill say an EP then follow up with an EM or T you should get a chain 1 all the time. This is accurate. I believe this is not a bug.

**Comment by danismyhero** [comment] 2020-11-02 20:33
Re-emphasizing this:

https://ffxiclopedia.fandom.com/wiki/Experience_Chain?oldid=306599


This term is used to describe the acquisition of an increased number of experience points from a monster's death due to the speed in which the monsters were killed. The bonus is obtained by defeating monsters that check as Even Match or tougher (EM+) within a time limit that starts when the last EM+ mob is killed. The percentage bonus earned increases as the chain becomes longer; however, a chain will be broken by failing to defeat an EM+ mob before the time allowance expires. Simply defeating a monter below Even Match will not break a chain (example: Beastmaster mob's pet), as long as the EM+ is killed within the allowed time, based on the last eligible kill. In party settings, bonuses are based on each individual member's level, so it is possible for mobs that check EM to lower level members to give experience chains, while the same mob will check Decent Challenge to a higher level member and not give a chain. The maximum experience bonus is 50%. 

Decent Challenge or below does not add to or reset the chain, but also does not hurt the chain (as long as you kill the next Even Match+ within the previously Even Match+ chain timer).

To add to this bug:  mobs killed outside of your exp range, but within your party / alliance contribute and reset the chain timer.  I noticed in Sea, where we farm as an alliance and the mobs are all Even Match+.  While farming Temperence, Faith or Fortitude we have people at each tower killing mobs.  The out of range message would be given, then we would kill a mob and receive or continue the exp chain.

**Comment by InoUno** [comment] 2021-03-02 23:10
Should be resolved with February 8, 2021 patch.

**Closed by InoUno** 2021-03-02 23:10 UTC
Labels: Combat
