### ISSUE TITLE
Combat/Magic Skill premature cap

### ISSUE THREAD

**Issue by Rawkhawk** [EdenServer/community#2743] opened 2020-04-24 21:20 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Version 30181205_0

Skilling up club and enfeeb magic as a Level 37 WHM, I've run into an issue three times, they both turn blue in the skills screen signifying they are capped, but changing one piece are armor uncaps them.  Club and Enfeeb should be able to get to ~108 I believe, but Club has shown capped (blue text) at 83 and 89 for me.  Just swapped one piece of gear and it unlocks and I can skill up some more.  Was able to screen shot the time it happened with Enfeeb, after capped, swapped a ring, then it was uncapped.

![Enfeeb Capped at 83](https://user-images.githubusercontent.com/63567090/80257433-e671a500-864e-11ea-8a99-815056ace619.JPG)

![Enfeeb Uncapped at 83](https://user-images.githubusercontent.com/63567090/80257489-086b2780-864f-11ea-8451-fd2d07e8cf8a.JPG)

**Comment by FariskaEden** [comment] 2020-08-02 15:19
From what I can tell, it'll look at the enemy's level and cap them based on your combat/magic skill ratings. So in the picture above you fought what looks to be a level 29 Thread Leech and WHM has an enfeebling skill of C so it capped out at the level 29 cap which is 83.
![image](https://user-images.githubusercontent.com/46270382/89126207-ef75dc00-d4b1-11ea-9606-42058ccf7240.png)

**Comment by Slamm21** [comment] 2020-08-02 15:27
the above is correct for what you can get it to against that mob, but it should never be blue like that unless it is capped for your level.

**Comment by Rawkhawk** [comment] 2020-08-02 16:39
I was able to change and ring and continue to skill up, but potentially the following mobs were above lv29.  Although that certainly seems like were the bug is, if you hit skill cap on a mobs level, it caps your skill, even if you could take it higher.

**Comment by Shoruto** [comment] 2020-11-06 13:22
Duplicate of #1648 however more additional information provided so won't close.

**Comment by 59blargedy** [comment] 2022-09-21 15:21
resolved combat skill portion in september 21, 2022 update, will need to check on magic

**Closed by 59blargedy** 2022-09-21 15:21 UTC
Labels: Combat
