### ISSUE TITLE
Boreal Tiger Draw in into a wall

### ISSUE THREAD

**Issue by ccl085** [EdenServer/community#1551] opened 2019-04-16 23:33 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

We did fight Boreal Tiger in Xarcabard for LB2 today, at some point it did use draw in and we all got stuck into the wall, we had to teleport out and redo it.

**Comment by Shoruto** [comment] 2019-04-17 10:46
Related #1292

**Comment by godmode** [comment] 2019-04-20 11:58
Please make sure to search the bug tracker before posting a new issue. Duplicate of #1292

**Closed by godmode** 2019-04-20 11:58 UTC
