### ISSUE TITLE
Korroloka Tunnel ??? for NIN job quest disappearing too soon.

### ISSUE THREAD

**Issue by vrusso-kong** [EdenServer/community#2438] opened 2020-01-21 17:55 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver: 30181205_0

When popping the Korroloka Leeches NMs for the NIN job unlock quest for multiple people, expected behavior is party member A checks ??? to spawn NMs. After NMs die Party members B-E can check the ??? to receive the KI then A checks, gets the KI and the ??? despawns and resets in 15 minutes. This is to ease the burden of multiple people all needing the KI.

Just now we tried it for three people and the ??? despawned as soon as the first person to check it after the leeches died. Can confirm this was not the person who originally popped the NMs.

Vinsanity in game.
Thanks,
Vince

**Comment by vrusso-pivotal** [comment] 2020-01-21 18:02
Adding details, the party members were able to get the KI by clicking the ??? every 15 minutes without having to repeat the fight. So that is at least working at intended and further supports the bug in question.

**Comment by ShiyoKozuki** [comment] 2020-01-22 08:45
This is working as intended and not a bug.
https://classicffxi.fandom.com/wiki/Ayame_and_Kaede

If more than one party member needs this fight, only one person needs to pop the three leeches. After the last leech fades away, have a different party member who needs the item click the ???, then have the player who spawned the leeches click it afterwards. Otherwise the player who did not spawn the leeches will be unable to obtain the [1]Strangely Shaped Coral.

**Comment by vrusso-pivotal** [comment] 2020-01-22 16:41
Right and I'm saying thats not what happened. When the second party member clicked the ??? to get the KI, the ??? disappeared, and we had to wait 15 minutes for it to appear again for the original player who popped could click.

The bug is that the ??? disappeared when it shouldn't.

**Comment by PurisBordeaux** [comment] 2020-09-26 13:58
Adding a comment on this thread that this issue still persists.

**Comment by Shoruto** [comment] 2020-11-08 14:58
Duplicate of #1420

**Closed by Shoruto** 2020-11-08 14:58 UTC
Labels: Quest/Mission
