### ISSUE TITLE
SMN Avatars still steal claim

### ISSUE THREAD

**Issue by ultimazero** [EdenServer/community#863] opened 2019-01-27 05:12 UTC
Summoner pets will still steal claim from people if the monster aggros. Read it was patched out but it still happens.

**Comment by roriffxi** [comment] 2019-01-30 22:14
The patch for this was rolled back because it was preventing avatars from protecting their master normally, which is a huge hamper on gameplay.  For now please just do the right thing and transfer claim back (by joining their party, or warping) if a monsters claim is stolen by a pet.

**Comment by godmode** [comment] 2019-02-07 01:09
Duplicate of #293

**Closed by godmode** 2019-02-07 01:09 UTC
