### ISSUE TITLE
Activated Attachments / Frame Abilities Remove All TP From Automaton

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#2330] opened 2019-12-31 00:27 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Activated attachments (Flashbulb, Shock Absorber, Strobe, etc.) set the automaton's TP to 0 when used. This should not be happening and TP should remain the same when these abilities are used.

version 30181205_0

**Comment by Pupaiya** [comment] 2019-12-31 03:40
Shield Bash is also causing the Valoredge Automaton to lose all TP.

**Comment by KnowOne134** [comment] 2019-12-31 03:41
any ranged attack from RNG frame also

**Comment by FariskaEden** [comment] 2019-12-31 03:55
Can also confirm, shield bash from valoredge frame and ranged attacks from sharpshot frame are setting tp to 0.

**Comment by Volkaru** [comment] 2019-12-31 04:13
It seems to be any job ability that's resetting it. Maybe the script got messed up and is thinking the JAs are TP moves, and is resetting TP. Remember that automaton ranged attacks are also considered JAs.

**Comment by spaceIdiot** [comment] 2019-12-31 10:55
TP also gradually decreases on puppet when resting like a player that doesn't have signet.

**Comment by FariskaEden** [comment] 2019-12-31 13:50
That's how it should behave if a puppet rests, they can't get signet so they'll lose TP while resting.

**Comment by Volkaru** [comment] 2019-12-31 21:05
Fixed with the emergency maint this morning. Closing.

**Comment by FariskaEden** [comment] 2020-01-20 23:31
Seems like this bug returned with the latest patch. Lost all TP when stoneskin / stobe were used.

**Comment by Volkaru** [comment] 2020-01-21 05:55
Confirmed.

**Comment by Crescensx** [comment] 2020-01-23 17:42
Confirmed Ranged attack as well is still using the puppets TP

**Closed** 2020-01-25 15:42 UTC
