### ISSUE TITLE
gear that increases movement speed stacks with other movement increasing gear

### ISSUE THREAD

**Issue by bootseden** [EdenServer/community#3106] opened 2020-07-17 03:33 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details
 
version 30181205_0

movement increasing speed equipment stacks right now when it shouldn't 
https://ffxiclopedia.fandom.com/wiki/Movement_Speed
only one piece is chosen for the speed boosts
the only movement speed equipment that stacks are the ones that slow you down like dusk

**Comment by Slamm21** [comment] 2020-07-17 04:15
duplicate of https://github.com/EdenServer/community/issues/379, closing

**Closed by Slamm21** 2020-07-17 04:15 UTC
