### ISSUE TITLE
Poison II dot too strong

### ISSUE THREAD

**Issue by Steam-arch** [EdenServer/community#6044] opened 2024-12-30 12:40 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Poison II doing more damage than intended. Should be capped at 10/tic

![image](https://github.com/user-attachments/assets/4f9eacdc-691d-41ef-95db-bf393fbb8f95)
naked rdm poison II on a 1300 hp cluster,  its losing 1% /tic consistently and after awhile it loses 2% hp/tic so impossible for it to be a 10/tic Dot.  maybe no cap implemented/other. Unsure how to check targets exact HP on test server.

from jp wiki's Poison-page:
![image](https://github.com/user-attachments/assets/33c2f291-482f-4be4-a170-f96f0dece124)

**Comment by Mozzy4Ever** [comment] 2024-12-30 17:09
Duplicate of https://github.com/EdenServer/community/issues/5488

**Comment by KnowOne134** [comment] 2024-12-30 17:16
Wow 2 years and still open. Closing as duplicate and other ticket has more info

**Closed** 2024-12-30 17:16 UTC

**Comment by Steam-arch** [comment] 2024-12-30 21:22
Alright sorry. Thought that ticket was solely for the increase per magic skill being too strong, but cap being right. But there is a small mention of the Max damage at the end, which I misunderstood because of my primate brain.
