### ISSUE TITLE
Suggested temporary solution to Beastmaster stuck pets problem

### ISSUE THREAD

**Issue by MB213** [EdenServer/community#636] opened 2019-01-01 05:42 UTC
As we know when playing Beastmaster pets often get stuck due to navmesh problems. If the 'Fight' command is used when the pet is too far from the Beastmaster, they ignore the command.

This is not the case with Summoner pets. They also get stuck, but they'll obey an 'Assault' command _no matter how far they are from the Summoner_, as long as the Summoner is in range of the mob being targeted.

Would it be possible to temporarily transplant whatever code allows that to happen to Beastmaster's abilities? This would alleviate a lot of the issues the job has with stuck pets since they'll always find a way to move if given an order to fight.

**Comment by godmode** [comment] 2019-02-16 21:18
Duplicate of #438

**Closed by godmode** 2019-02-16 21:18 UTC
