### ISSUE TITLE
Magic burst for Enfeebles, Blm/Blu/Nin enfeebles, dia, bio give no message or bonuses

### ISSUE THREAD

**Issue by KnowOne134** [EdenServer/community#2424] opened 2020-01-16 21:19 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
currently uncoded to give any bonuses or set up 2nd messages

**Comment by ThrisStraizo** [comment] 2020-01-27 07:10
Duplicate of [#625](https://github.com/EdenServer/community/issues/625)

**Closed** 2020-01-27 12:14 UTC
