### ISSUE TITLE
Puppetmaster attachments on/attached to early players only

### ISSUE THREAD

**Issue by Jigawattts** [EdenServer/community#1754] opened 2019-06-09 10:38 UTC
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
Version: 30181205_0
Puppetmaster attachments Ice Maker and Flame Holder are on/equiped to Puppetmasters who bought from NPC Yoyoroon during the first 3 days of release. These 2 attachments are extremely important for the class, thus making the people who didn't get to buy them at a disadvantage. The only way to get the said attachments in game are by an ENM Pulling the Plug, which drops an Item called the Super Cermet, that is an ingredient in crafting the item. Possible solution to make it fair for other Puppetmasters would allowing it back on the NPC or enabling Pulling the Plug ENM.

**Comment by godmode** [comment] 2019-06-09 10:50
Pulling the Plug will be in development at some point. I know there are multiple places to post things so it can be confusing where to say what. I believe this may already be in the forums; you can chime in there if you would like. Closing this ticket because it is not a bug, it's a discussion about future development.

**Closed by godmode** 2019-06-09 10:50 UTC

**Comment by Jigawattts** [comment] 2019-06-09 21:01
What about the people who have access to these attachments already?
Shouldn't it be available to the rest of the Puppetmasters?
