### ISSUE TITLE
Unable to Flag Quest: Beyond The Sun

### ISSUE THREAD

**Issue by Serephim** [EdenServer/community#1277] opened 2019-03-14 19:46 UTC
As far as I know the quest Beyond The Sun doesn't exist yet and I am ready to collect my Maat's Cap any time now and I know there is others that need it and the there are a few more  that I know of that are pretty close too.

https://ffxiclopedia.fandom.com/wiki/Beyond_the_Sun

**Comment by godmode** [comment] 2019-03-14 19:49
Duplicate of #626

**Closed by godmode** 2019-03-14 19:49 UTC
