### ISSUE TITLE
Mobs randomly move faster than supposed to, Clip through world in too many situations.

### ISSUE THREAD

**Issue by Hestichan** [EdenServer/community#1997] opened 2019-08-31 01:41 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details

ver 30181205_0

I'm sure dev is aware, but I couldn't find a specific bug report for this:

1)
I've noticed several instances where normal mobs can run at 'super' speed to catch up with the player. They close the distance much faster than normal. Normally, mobs and players run at the same speed (except obviously mobs that move faster, like tigers, imps, etc.). This is not era kosher behavior, as far as I remember.

2)
Similar to this, is that I've seen several instances where mobs can clip right through the world to get to the player, whether this is clipping through fences that the player would not be able to pass through, teleporting 50m up or down in/out of holes to stay in contact with the player (rather than have to run all the way around like a normal entity that obeys the game's physics).

I've jumped down a hole in Gusgen to elude Juggler Hecatomb, only to have the NM clip right through the game world on top of me while I was using Escape (luckily it still proc'd). This 'cheating' and 'hacking' by the game's mobs really hurts my play experience. If I make a smart move to elude a mob, or get it to have to run around obstacles to get to me, I expect it to have to obey the same world physics that I do. As a player, I cannot magically clip through walls, so nor should mobs be able to under normal circumstances.

If a mob cannot route it's way to a player who moves to elude it, instead of clipping through the world, or whatever, it should simply lose the player's scent and revert to it's idle unclaimed state.

3)
Similar to the above (in that this is movement related), mobs are able to jump up into trees as they move, rather than have to stop or navigate around the object. While amusing, it's sometimes annoying when you are trying to fight them.

**Comment by Mozzy4Ever** [comment] 2019-09-01 19:08
This is a Navmesh issue

**Comment by beauxq** [comment] 2019-09-03 03:20
It's not all navmesh. I don't think the navmesh makes the mobs run faster than they're supposed to.

**Comment by mlandrum22** [comment] 2019-09-03 03:21
I believe it's just mage mobs. They catch up and cast, fail and fall behind. Then catch up and cast, etc.

**Comment by bkesecker** [comment] 2019-09-03 03:48
There is likely bursty network data causing the herky jerky movement speed which is in turn caused by a greedy set of database calls.  Perhaps some database profiling could reveal this issue.  Funny thought... could be web site accessing the who's online list, as I suspect it pulls from the same database.

**Comment by Hestichan** [comment] 2020-04-21 17:01
I don't know how navmesh works -- how it dictates where mobs are allowed or not allowed to move, but I wonder if there are coded 'rules' that allow mobs to 'cheat' the navigation mesh and teleport through it under various conditions? That and being able to navigate across mesh points? that logically shouldn't connect (i.e. go through walls, up/down impossible drops). Too bad nobody's made a visual navmesh editor! It'd be interesting to see it depicted somehow so that I could understand it better...

**Comment by Balrahn** [comment] 2020-06-06 09:00
I can't even outrun a groundskeeper with Wlegs on. If I run straight without any obstacles it will always be on my ass hitting me.

**Comment by InoUno** [comment] 2021-03-02 23:11
Resolved with March 1, 2021 patch.

**Closed by InoUno** 2021-03-02 23:11 UTC
