### ISSUE TITLE
15 minute weakness when dc'ing from dynamis

### ISSUE THREAD

**Issue by baroom84** [EdenServer/community#1771] opened 2019-06-13 01:28 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

A few people in our Jueno run dc'ed at different times and came back to a 15 minute weakness. Happened last week too.

**Comment by godmode** [comment] 2019-06-14 01:38
Duplicate of #1732

**Closed by godmode** 2019-06-14 01:38 UTC
