### ISSUE TITLE
King Vinegarroon

### ISSUE THREAD

**Issue by gweivyth** [EdenServer/community#114] opened 2018-10-09 02:03 UTC
Chilling out, maxing, relaxing all cool,
And all shooting some b-ball outside of Earth weather.
![e30dd15de02915c39668f3872f628750](https://user-images.githubusercontent.com/37130689/46642590-f2b61000-cb45-11e8-9379-9533051dd33e.jpg)

**Comment by godmode** [comment] 2018-10-10 00:19
Duplicate of #4

**Closed by godmode** 2018-10-10 00:19 UTC
