### ISSUE TITLE
About Catapult's Recent Adjustment

### ISSUE THREAD

**Issue by DrfistMD** [EdenServer/community#3480] opened 2020-12-08 04:54 UTC
### Checklist

- [ X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details
version 30181205_0

After Catapult's adjustment in today's patch, I think it's been tuned a bit too far in the strong direction.  On my 70 BLU in just Lower Delkfutt's tower, the Gigas within the lv30 range are chunking for me 200 per Catapult they land.  Meanwhile their TP moves are doing 20-30.  (216 defense before any buffs).
As a low 20s job running through Qufim, the Hunters now 1 shot me if they aggro, and by a fair margin.  Testing this out on my 21 PUP for instance (yeah it's a bit low, but I didn't have quick access to a level sync when double checking this) I was 1 shot by a Hunter yeeting a rock through my chest for 384.  I think this move in particular needs to be re-evaluated a bit as it should hit hard, but this seems a bit too hard.

**Comment by prwilson42** [comment] 2021-02-15 15:01
I was trying to farm chest key in Delkfutt's Tower and getting three shotted by the Gigas Sculptor' Catapult in lower tower.  I was on level 40 bst with a Tiger Familiar which caps at level 40.  My def 134.  My tiger was also getting hit with 250-350'ish Catapult's.  The Sculptors there con as low EP.
Later I ran through Qufim and got aggro from a Giant Hunter which also did very high Catapult damage to me.

Logs:
	Line 3681: [Gigas Sculptor] 128 Catapult ¨ Rinaria
	Line 3691: [Gigas Sculptor] Catapult (Miss) ¨ Rinaria
	Line 3703: [Gigas Sculptor] 172 Catapult ¨ TigerFamiliar
	Line 3808: [Gigas Sculptor] 133 Catapult ¨ Rinaria
	Line 3809: [Gigas Sculptor] 134 Catapult ¨ Rinaria
	Line 3814: [Gigas Sculptor] 130 Catapult ¨ Rinaria
	Line 3823: [Gigas Sculptor] 194 Catapult ¨ TigerFamiliar
	Line 3832: [Gigas Sculptor] 305 Catapult ¨ TigerFamiliar
	Line 3840: [Gigas Sculptor] 208 Catapult ¨ Rinaria
	Line 3925: [Giant Lobber] 128 Catapult ¨ Ancient Bat
	Line 3939: [Giant Lobber] Catapult (Miss) ¨ Rinaria
	Line 3940: [Giant Lobber] 107 Catapult ¨ Rinaria
	Line 3942: [Giant Lobber] Catapult (Miss) ¨ Rinaria
	Line 3960: [Giant Lobber] Catapult (Miss) ¨ TigerFamiliar
	Line 3966: [Giant Lobber] 188 Catapult ¨ TigerFamiliar
	Line 4334: [Gigas Sculptor] 284 Catapult ¨ TigerFamiliar
	Line 4337: [Gigas Sculptor] 276 Catapult ¨ TigerFamiliar
	Line 4338: [Gigas Sculptor] 356 Catapult ¨ TigerFamiliar
	Line 4355: [Gigas Sculptor] 300 Catapult ¨ Rinaria
	Line 4357: [Gigas Sculptor] 162 Catapult ¨ Rinaria
	Line 4358: [Gigas Sculptor] 302 Catapult ¨ Rinaria
	Line 5134: [Giant Hunter] Catapult (Miss) ¨ Rinaria
	Line 5135: [Giant Hunter] 94 Catapult ¨ Rinaria
	Line 5144: [Giant Hunter] 93 Catapult ¨ Rinaria
	Line 5153: [Giant Hunter] 289 Catapult ¨ Glow Bat
	Line 5167: [Giant Hunter] Catapult (Miss) ¨ Glow Bat
	Line 5175: [Giant Hunter] Catapult (Miss) ¨ Rinaria
	Line 5184: [Giant Hunter] Catapult (Miss) ¨ Rinaria
	Line 5195: [Giant Hunter] Catapult (Miss) ¨ Rinaria
	Line 5298: [Giant Hunter] 252 Catapult ¨ Rinaria
	Line 5299: [Giant Hunter] Catapult (Miss) ¨ Rinaria
	Line 5300: [Giant Hunter] 153 Catapult ¨ Rinaria
	Line 5301: [Giant Hunter] 305 Catapult ¨ Rinaria

I went on retail to see what damage my level 40 COR would take and it was significantly less.  COR had 159 def. 
The Stonemason's are little higher level but still EP to my COR.  I could not find any Sculptor to compare to. The accuracy seems very high on Eden too, the retail giga missed more often.  

Logs:
        Line 110: 08:32:12[Gigas Stonemason] 89 Catapult ¨ Psychofetrus
	Line 111: 08:32:22[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 112: 08:32:29[Gigas Stonemason] 79 Catapult ¨ Psychofetrus
	Line 113: 08:32:36[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 114: 08:32:46[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 115: 08:32:53[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 116: 08:33:02[Gigas Stonemason] 83 Catapult ¨ Psychofetrus
	Line 118: 08:33:11[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 124: 08:33:20[Gigas Stonemason] 88 Catapult ¨ Psychofetrus
	Line 129: 08:33:27[Gigas Stonemason] Catapult (Miss) ¨ Cherukiki
	Line 136: 08:33:35[Gigas Stonemason] 64 Catapult ¨ Cherukiki
	Line 143: 08:33:44[Gigas Stonemason] 70 Catapult ¨ Cherukiki
	Line 155: 08:33:56[Gigas Stonemason] Catapult (Miss) ¨ Cherukiki
	Line 167: 08:34:07[Gigas Stonemason] 77 Catapult ¨ Cherukiki
	Line 207: 08:34:36[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 215: 08:34:46[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 224: 08:34:55[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 234: 08:35:05[Gigas Stonemason] 66 Catapult ¨ Psychofetrus
	Line 242: 08:35:12[Gigas Stonemason] 63 Catapult ¨ Psychofetrus
	Line 252: 08:35:21[Gigas Stonemason] 69 Catapult ¨ Cherukiki
	Line 261: 08:35:32[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 270: 08:35:40[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 278: 08:35:49[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus
	Line 286: 08:35:58[Gigas Stonemason] Catapult (Miss) ¨ Psychofetrus

Reproducible steps:
Go to Qufim or inside the tower on a level 40 job then get aggro from a ranger giga then die after 2-3 hits.

Version: 30181205_0

**Comment by ThoseWhoFight** [comment] 2021-02-15 15:32
I feel the same way personally, but don't really have much hard evidence to back up the claim. Catapult still feels overtuned imo but I'm basically basing that solely off of memory.

There's a few videos online showing Jotunn Rangers and Catapults landing on players but it's tough to know what buffs they have on etc.

https://youtu.be/BiJQVtqNiLI

Around the 3 min mark you can see a few land on the group's mage for around 200 ish. I'm pretty positive I've seen some land for 400+ on Eden since the patch

**Comment by deepbreathingeden** [comment] 2021-03-01 13:44
![bbc for juul](https://user-images.githubusercontent.com/53072734/109505193-c7854000-7ab5-11eb-803a-41c04d4e0c6b.jpg)

**Comment by GiichiHiro** [comment] 2021-03-17 19:54
ver 30181205_0

Here's some more evidence that it's over tuned: https://www.youtube.com/watch?v=6VvIvI4oaD0
This is a level synced 30pld, taking 30-50 damage, with armor sync in, so some adjustment to take into consideration there.

Vs my Level synced 30mnk:
![wtfcatapult](https://user-images.githubusercontent.com/66037286/111529757-47abd680-8741-11eb-9857-b6accb015a5f.PNG) Wearing windurstian Gi set

**Comment by 59blargedy** [comment] 2023-03-26 03:31
resolved in tp move adjustments

**Closed by 59blargedy** 2023-03-26 03:31 UTC
Labels: Combat
