### ISSUE TITLE
Grahs in SEA seeming to take lower magic damge than should

### ISSUE THREAD

**Issue by Darcatvar** [EdenServer/community#4107] opened 2021-03-02 20:43 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Nuking on BLM in sea the grahs seem to be only taking between 600-700 damage from tier IV nukes now.

**Comment by Darcatvar** [comment] 2021-03-04 14:34
It also seems the magic damage to statues in dynamis are a bit on the low side. Used to be able to one shot in a well geared blm, even on retail, and now it is rare an unresisted AM II takes one out.

**Comment by 59blargedy** [comment] 2021-03-04 14:40
ghrahs have mdt and mdb added to them per collected testing. statues as well, with mdb varying across quadav vs orc vs yags. the only statues you may be remembering are sandy, that have the lowest mdb. im leaving the ticket open bc ghrahs have about 5 mdb too much that needs to be removed, but in general this is correct.

**Comment by 59blargedy** [comment] 2021-03-08 16:05
small mdb tweak resolved in March 8, 2021 update, rest is as intended

**Closed by 59blargedy** 2021-03-08 16:05 UTC
Labels: Combat
