### ISSUE TITLE
Haste duration at lv40 too short

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3336] opened 2020-10-13 14:22 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Haste duration at lv40 is 2:30 instead of 3 minutes. 

/ver 30181205_0

Can be easily replicated by going into 40 cap pso'xja and casting haste.

**Comment by Shoruto** [comment] 2020-10-29 22:26
Confirmed - It is 3 minutes (as long as it's not cast under a level 40 player, then duration is decreased, similar to Sneak/Invis)

https://ffxi.allakhazam.com/db/spell.html?ffspell=82
https://www.bg-wiki.com/index.php?title=Haste&oldid=37221
https://ffxiclopedia.fandom.com/wiki/Haste?oldid=299489

Duration
Mar 31 2006
Since it's not been mentioned - yes, the duration of this spell is three (3) minutes.

Well, on testing it out a couple of times it actually seems to be about 2 minutes and 59 seconds. But ABOUT 3 minutes nontheless.

**Comment by falzum** [comment] 2020-10-30 16:40
I'm in riverne A right now, capped at level 40. Haste is lasting 2:30 when it should be a full 3 minutes.

**Comment by deepbreathingeden** [comment] 2021-03-01 13:51
![dfgsdfg](https://user-images.githubusercontent.com/53072734/109506175-c9033800-7ab6-11eb-9995-723aa67db4d2.png)

**Comment by deepbreathingeden** [comment] 2021-03-01 13:52
![1614121272006](https://user-images.githubusercontent.com/53072734/109506222-d6202700-7ab6-11eb-9008-0a68c9890dc9.jpg)

**Comment by 59blargedy** [comment] 2021-05-31 14:34
resolved in May 31, 2021 update

**Closed by 59blargedy** 2021-05-31 14:34 UTC
