### ISSUE TITLE
CoP 8-4 Meteor casting way too fast

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#3173] opened 2020-08-09 23:31 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Please see attached photo from 8/9 after maint. Meteor is casting in ~1-2 seconds. According to wiki, it should be a 10 second cast time. https://ffxiclopedia.fandom.com/wiki/Dawn

![Meteor](https://user-images.githubusercontent.com/55296729/89744021-c8517880-da76-11ea-9eb9-b046153034ed.PNG)

/ver 30181205_0

**Comment by 59blargedy** [comment] 2020-08-09 23:48
duplicate of https://github.com/EdenServer/community/issues/2630

**Closed by 59blargedy** 2020-08-09 23:48 UTC
