### ISSUE TITLE
Fomor Dark Knight spawning during the day

### ISSUE THREAD

**Issue by Appotemmis** [EdenServer/community#3564] opened 2021-01-09 00:13 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Client: 30181205_0

Nothing major but at E-7 In Misareaux Coast, there is a Fomor Dark Knight that spawns during the day.

![Artemmis_2021 01 09_001157](https://user-images.githubusercontent.com/77178224/104076911-7bcdbd00-520f-11eb-99b1-c187b8051d8c.png)

**Comment by Mozzy4Ever** [comment] 2021-01-09 00:29
Duplicate of https://github.com/EdenServer/community/issues/2234 and https://github.com/EdenServer/community/issues/1855

**Comment by 59blargedy** [comment] 2021-01-12 16:26
closing as duplicate, but thank you for reporting

**Closed by 59blargedy** 2021-01-12 16:26 UTC
