### ISSUE TITLE
gardening pots disappear and die random

### ISSUE THREAD

**Issue by stacyvinje** [EdenServer/community#715] opened 2019-01-09 06:21 UTC
Within the last 4 hours I've had 2pots (tree saplings) disappear off table and die on Dabeast, and 1 pot (tree cuttings) do the same on Oloaf.  When you are in the mog house you can no longer see the pots but when you look under gardening you see it on the floor dead.  Why are the pots disappearing? Both me and Dabeast have been checking the plants religiously.  3:30 was the last time they were checked today and then again on the darks day that just passed.  In that time they died.  (Only checking the plants on darksday)
Thank you for your help

**Comment by Scarman33** [comment] 2019-01-09 12:39
This happened to me as well.  I have lost 3 plants now - 2 tree cuttings, 1 vegetable in brass pots.  I have checked twice a day.

Plants are in brass pots on maple tables.  Both times it has happened, I have checked plants, logged out, checked plants on another character, logged back in on the first character and found a pot no longer on the table, but on the floor and withered.  This was right after checking it and having it say the plant is doing well.

**Comment by Scarman33** [comment] 2019-01-09 13:13
It happened twice today, where I would check the plants, leave the MH and then re-enter.  In both cases, it was the third pot from the top of the mog safe list, if this helps any.

**Comment by marlinla** [comment] 2019-01-10 23:12
Confirming. Same type relocation happened twice. Pot was on table, then ends up in corner.

https://i.imgur.com/c3Z00Mw.png
https://i.imgur.com/OCsV66Z.png

**Comment by phobos1234** [comment] 2019-01-11 01:34
Same thing here.  

Brass pot, maple table. Tree cuttings, fed a light crystal in Bastok.

![phobos_2019 01 10_203012](https://user-images.githubusercontent.com/46583105/51007817-0f802c00-1517-11e9-9cf5-60bf9ed0f1ca.png)

**Comment by phobos1234** [comment] 2019-01-11 12:55
Also to note, the withered and dry plant that is now on the floor says I fed no crystal, when in reality I obviously fed a crystal.

**Comment by olafvinje** [comment] 2019-01-12 21:59
Please help, Lost 2 saplings in one house and 1 cutting in another. Random Plant Death (RPD) Pot left my table and appeared elsewhere in mog house.

**Comment by marlinla** [comment] 2019-01-12 22:06
I think a table in the corner where the pots always end up on the floor is a reasonable workaround. Could not be more than 1000 gil. Could flip the table once the bug is fixed.

**Comment by beastffxi** [comment] 2019-01-12 22:18
Not sure that will work, one of my pots went into the corner even tho I have another piece of furniture there, its inside / overlapping 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 12, 2019 at 5:06 PM, marlinla<notifications@github.com> wrote:   
I think a table in the corner where the pots always end up on the floor is a reasonable workaround. Could not be more than 1000 gil. Could flip the table once the bug is fixed.

**Comment by phobos1234** [comment] 2019-01-12 22:20
That won't work. It took away my Crystal I fed it and killed it regardless- Phobos

**Comment by beastffxi** [comment] 2019-01-12 22:21
one of mine dropped from table and moved to corner, but there was already a piece of furniture there, so you can just see the tip of the dead plant

**Comment by beastffxi** [comment] 2019-01-12 23:00
2 more died upon entering just now after maint..... fed them crystals earlier today, and even shows that they were fed 2 xtals :( 5 plants down now
Dabeast............

**Comment by beastffxi** [comment] 2019-01-13 15:59
So meatman has 3 cuttings that have randomly died, piggie has 1 sapling random death, and dabeast 3 saplings random death. This is the first time Ive had any randoms die, have been gardeing in full house waves since it was released. Wondering if theres any recommendations for what to do after this harvest? Should i take my pots out of layout and re-organize them? Or is some file corrupted in my houses, all are different accounts though, and wife has only lost 1 plant random. Thanks

**Comment by marlinla** [comment] 2019-01-13 17:10
Did you get a plant seppuku since the key item hotfix? 20 of mine have survived 2 plant cycles so far.

@beastffxi stop using expensive seeds until this is confirmed fixed, lol.

**Comment by beastffxi** [comment] 2019-01-13 19:42
I lost more after last nights KI fix 
Im not going to plant any more expensive seeds, these were in mid cycle when this started for me. Ive grown cuttings and saplings without problems before this batch. So this was new problem for me

**Comment by Caelic** [comment] 2019-01-14 05:17
Just happened to me. This morning all 10 brass pots were on the same maple table, all healthy. About 10-12 hours later, two have randomly been moved to the floor at the back corners of my mog house and both are dead. Gonna leave them there hoping they are filling the corners so that it can't happen again...

**Comment by ElectroNicMan83** [comment] 2019-01-14 23:32
I lost 3  tree Cutting here. It seem to happen, when zoning in / zoning out.  Happened on Jimbo if you can track and see the log to help pinpoint the probs.

**Comment by phobos1234** [comment] 2019-01-17 03:18
Just lost another tree sapling.  As soon as I moved the pot out of the corner of the room I zoned in and another died.  DO NOT MOVE POTS OUT OF THE CORNER.

**Comment by godmode** [comment] 2019-02-07 00:38
Closing this issue in favor of a ticket that addresses the root cause. #918

**Closed by godmode** 2019-02-07 00:38 UTC
