### ISSUE TITLE
An Explorer's Footsteps quest loops the final text.

### ISSUE THREAD

**Issue by brndmfrd** [EdenServer/community#1812] opened 2019-06-24 02:06 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details   
# Issue:    
Unable to complete quest "An Explorer's Footsteps".    
Other reported issues are similar, but this is different in that all clay tablets have been turned in.    

# Steps:    
* Completion of the last clay tablet (mine was from Sauromugue Champaign).  
* I approached Abelard without talking to him.  
* I traded the last tablet to him and his text acknowledges that it is the last tablet.  
* He awards me 10k gil.  
* Successive attempts to talk with him are met with the text "You're back! and with the last one! ... I give you this."   
* Nothing is given. Victory music is triggered.  

# Added Info
* Quest "An Explorer's Footsteps" is still flagged as an active quest.  
* I am doing the quest "Signed in Blood" and I am unable to progress.  
* I am doing Signed in Blood with another and I did this tablet quest with them and they turned in all clay tablets with success. The discrepancy seems to be with turning in the last clay tablet by talking with Abelard and trading to Abelard before talking to him.   
* I have attempted to resolve the issue by logging out and logging back in and zoning out/in.  

# Version:   
"version 30181205_0"

**Comment by godmode** [comment] 2019-06-24 20:16
Great details here. Thanks!

**Comment by Kopolt** [comment] 2019-06-24 20:49
I have the very same problem. Completely identical. It wouldn't be so bad if the signed in blood quest wouldn't be blocked by this. Thanks for looking into this.

**Comment by Althaia** [comment] 2019-09-07 18:35
I have also experienced that this quest prevents continuation of "Signed in Blood." GodMode said in previous Closed Issues it's that way on retail, too, but this seems like an issue that could be fixed on Eden, given how small our player base is compared to retail. We have to get past the third banishing gate to complete this quest, but how often do you see people unable to get past even the first banishing gate, for lack of participation?

With "Explorer's Footsteps" open, I completed the first part of "Signed in Blood," which is trading the cathedral tapestry to the NPC in San d'Oria to get the initial cutscene, but now I can't proceed with what should've been a relatively easy quest.

For whatever reason, the cathedral tapestry wasn't consumed by trading it to the NPC; I don't know if that's related to this issue or not. This has been previously mentioned in the closed issue #838 by pksweets on Jan 24 and [#744](https://github.com/EdenServer/community/issues/744#issuecomment-468796044) by reynierk on Mar 1.

There were closed issues that you can see for more information on this matter; I have not included duplicates in this list:

[#744](https://github.com/EdenServer/community/issues/744)
[#930](https://github.com/EdenServer/community/issues/930)
[#858](https://github.com/EdenServer/community/issues/858)

If it is in fact this way on retail, then I guess nothing will be done about it. It doesn't say so on FFXIclopedia, which is for retail FFXI, but perhaps GodMode is thinking of an era-only problem, which has since been fixed in retail?

Unsatisfied with this explanation, I did a bit more digging and found a note from 2012 indicating that Abelard will mention his little hobby in the dialogue for "Signed in Blood." Now THIS may be why, in retail, you cannot proceed with "Signed in Blood" without first completing "Explorer's Footsteps." Here it is, found on [this page](https://ffxiclopedia.fandom.com/wiki/Talk:Signed_in_Blood):

- Wouldn't the Prereq be starting An Explorer's Footsteps? Considering Abelard speaks to you as if you were already aware of his little hobby. Fanmattai (talk) 11:03, August 5, 2012 (UTC) 

I implore GodMode and team to re-code the quest on Eden such that we only need to do the initial 15 tablets (or get the Crawler's Nest map) to get "Signed in Blood" text to trigger. Surely, at that point, we're well aware of his "little hobby."

To anyone frustrated by this, if nothing else, I've confirmed that it has been GodMode's stance that it is "normal" to not be able to proceed with "Signed in Blood" if you have not completed "Explorer's Footsteps" will all 17 tablets. In the case above (in the original post), brndmfrd did complete the quest but still couldn't get the dialogue for "Signed in Blood" to trigger.

**Comment by Althaia** [comment] 2019-10-04 17:52
Okay, I just turned in my 17th tablet, so I'm going to lay out what I did:

- I was doing Signed in Blood, stuck on the part where I have to talk to the mayor.
- Turned in my last tablet (mine was from Batallia Downs).
- Approached Abelard and immediately talked to him, got this text:

"You're back! And with the last one! Thank you so much, my friend. In return for your unwavering kindness, I give you this."
Obtained 10000 gil.

- Talked to him again and got the cutscene for Signed in Blood.
- Talked to him again and got a smaller repeat of Signed in Blood quest text.
- Since I still had the clay tablet, I attempted to trade it to him.
- Abelard won't accept the clay tablet.
- I then zoned out and zoned back into Selbina.
- Result: no change: Abelard still just talks to me about Signed in Blood and won't accept the Clay Tablet.

**Comment by bkesecker** [comment] 2019-12-23 05:33
Thanks for the all the details @Althaia  Abelard's code has been a thorn for a while.  Rewrote the whole thing and added support for what wasn't there.  If the pull request is approved before Dec 30, it should be in that release.

**Comment by bkesecker** [comment] 2019-12-23 05:34
@brndmfrd Also, thanks for reporting with loads of detail.

**Closed** 2019-12-27 02:22 UTC
Labels: in-code-review
