### ISSUE TITLE
Beadeaux (F-8) have not  Afflictors,But being weakened

### ISSUE THREAD

**Issue by bb123649a** [EdenServer/community#4974] opened 2022-04-09 22:22 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

**Comment by Mozzy4Ever** [comment] 2022-04-09 22:26
Duplicate of https://github.com/EdenServer/community/issues/829

**Comment by KnowOne134** [comment] 2022-04-18 15:57
Corrected 4/18/2022

**Closed by KnowOne134** 2022-04-18 15:57 UTC
