### ISSUE TITLE
enspell damage and mob element weakness is incorrect

### ISSUE THREAD

**Issue by Raulfin** [EdenServer/community#3128] opened 2020-07-23 05:16 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
ver30181205_0
Monsters are immune to damage types they are weak to when that damage is delt as an additional effect such as light bolts or Enspells.

Reproduction;
Beetles are weak to Ice and Light
As RDM cast EnBlizzard and attack a beetle, the additional effect damage from the Enspell will deal 0.
Using a crossbow with Holy Bolts, ranged attack a beetle and the additional effect damage of the bolt will deal 0 damage.

Also Enaero does not damage bats, but Enfire does damage Bombs.

**Comment by guitarmacist** [comment] 2020-07-23 05:54
This seems to be affecting everything with a weakness. Can confirm Holy Bolts hit for 0 damage on all skeletons, bats, and spirits, but still work fine on targets not weak to Holy. Enaero hits for 0 damage on beetles in Garlaige, but Acid Bolts (which should be considered Wind-based) still apply. A plain Blizzard nuke was hitting for full damage while Enblizzard was hitting for 0 with 143 Enhancing. Armor and Shield Break's Wind- and Ice-based additional effects (respectively) land on these beetles as well. Based on this, I assume the issue is isolated to flat damage-based additional effects.

**Comment by Raulfin** [comment] 2020-07-26 00:01
Orcish Warmachine's which are marked weak to water take damage as expected from EnWater.

**Comment by Raulfin** [comment] 2020-09-27 18:54
After the September 27, 2020 Update, Flys and Crabs now take damage as expected from enblizzard, crabs take dmg as expected from Enthunder, but bats still take 0 dmg from Enaero.

**Comment by 59blargedy** [comment] 2021-11-29 16:48
resolved in November 29, 2021 update

**Closed by 59blargedy** 2021-11-29 16:48 UTC
Labels: Combat
