### ISSUE TITLE
Gigas Double Attacking and attacking super fast.

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#48] opened 2018-10-03 17:48 UTC
Gigas in beaucedine glacier double attacking and attacking very fast.

**Comment by Mozzy4Ever** [comment] 2018-10-04 03:34
Seems to be a beastmen thing. a lot of orcs in Davoi are doing the same thing, if even they're PLD.. Monks attack very fast, and DRGs were double attacking every round.

**Comment by godmode** [comment] 2018-10-12 00:35
Duplicate of #44

**Comment by godmode** [comment] 2018-10-12 00:36
Seaboard Vulture and Gigas in beaucedine glacier as well

**Closed by godmode** 2018-10-12 00:35 UTC
