### ISSUE TITLE
AF drop rate in Beacedine (potentially Xarc as well)

### ISSUE THREAD

**Issue by joebinne** [EdenServer/community#2928] opened 2020-06-05 02:17 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ X] I have provided my client version in the details. (type /ver into your game window)

### Details

For the 2nd week in a row, after 2-3 hours into Dynamis Beaucedine we got 0 AF with multiple TH4 present. From multiple 640x480 vids I watched on youtube, most group would at the very least  have got a couple of DRG, BST and MNK. The coins drops seems ok. Please up the drop rate of DRG/BST/MNK and also all the other AFs.

You can reproduce this easily by going into Dynamis Beaucedine and getting no AF drops.

/ver 30181205_0

Hugs and pogo sticks!

**Comment by Volkaru** [comment] 2020-06-05 02:22
Duplicate of #2927 
Also, why?

**Closed by Volkaru** 2020-06-05 02:22 UTC
