### ISSUE TITLE
/yell and chat filters

### ISSUE THREAD

**Issue by Xaver-Entropia** [EdenServer/community#423] opened 2018-12-07 04:50 UTC
Chat filter for /yell doesn't seem to work. That plus the already known issue of chat filters not saving makes the chat log quite annoying at times.

Could we just have a global LS wich we can just unequip instead of being spammed even inside our moghauses?

**Comment by Aneyus** [comment] 2018-12-07 11:55
I dunno about you but I would prefer working chat filters. Set your sights high!

**Comment by Xaver-Entropia** [comment] 2018-12-07 22:31
Whats exactly the purpose of yell in this server? Because ppl aren't using it just to seek for pt or to sell items, they are using it to make questions, have discussions and in an instance to promote streams.

Also, if I suggested having a global LS instead of correcting chat filters was that the developers already have enough things to do. A LS is something that requires way less time sink.

**Comment by Cheezcakee** [comment] 2018-12-09 04:55
Plz working yell filters. The great thing about kupols is you could unequip it lol. <3

**Comment by godmode** [comment] 2018-12-10 02:45
We will get yell filters working as well as /seacom; but in the mean time please reserve /yell for lfg, help, and wtb/wts messages. The cooldown will be increased to 15m on Tuesday due to the immense population growth. If it keeps being polluted with idle chatter then it will probably be reverted back to cities only.

**Comment by godmode** [comment] 2018-12-21 22:55
Also zoning resets /yell timer to 0 #386

**Comment by KnowOne134** [comment] 2020-10-31 02:43
!yells off/on implemented

**Comment by KnowOne134** [comment] 2020-10-31 02:44
duplicate of #354

**Closed by KnowOne134** 2020-10-31 02:44 UTC
Labels: needs-implemented
