### ISSUE TITLE
Decent challenge monsters count for EXP chains

### ISSUE THREAD

**Issue by ShiyoKozuki** [EdenServer/community#2282] opened 2019-12-15 23:50 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
If level sync is activated(have not tested without level sync) and you pull a decent challenge monster, it will "start" experience chains. You cannot chain them specifically, but if you pull a decent challenge THEN pull an EM or higher, you'll get chain # 1. I have tested this on many different monsters and they all work as long as they read "decent challenge" at least.

https://ffxiclopedia.fandom.com/wiki/Experience_Chain?oldid=306599
This term is used to describe the acquisition of an increased number of experience points from a monster's death due to the speed in which the monsters were killed. The bonus is obtained by defeating monsters that check as Even Match or tougher (EM+) within a time limit that starts when the last EM+ mob is killed. The percentage bonus earned increases as the chain becomes longer; however, a chain will be broken by failing to defeat an EM+ mob before the time allowance expires. Simply defeating a monter below Even Match will not break a chain (example: Beastmaster mob's pet), as long as the EM+ is killed within the allowed time, based on the last eligible kill. In party settings, bonuses are based on each individual member's level, so it is possible for mobs that check EM to lower level members to give experience chains, while the same mob will check Decent Challenge to a higher level member and not give a chain. The maximum experience bonus is 50%.

version 301812505_0

**Comment by 59blargedy** [comment] 2020-11-01 16:15
duplicate of https://github.com/EdenServer/community/issues/1297

**Closed by 59blargedy** 2020-11-01 16:15 UTC
