### ISSUE TITLE
Parry Procs when Hit

### ISSUE THREAD

**Issue by Drognand** [EdenServer/community#958] opened 2019-02-12 15:21 UTC
I have noticed the past couple days i am getting Parry Procs and skills when I get hit.
![drognand_2019 02 12_100325](https://user-images.githubusercontent.com/47567545/52645975-d89f8c00-2eaf-11e9-99ef-fd4e40ee79d2.png)

**Comment by rujind** [comment] 2019-02-13 14:50
I'm not 100% on this, but at some point SE redid defensive skill ups (because they were very poorly implemented and an extreme hassle to raise). Now, every time you are swung at you should have a chance to gain in any defensive skill you meet the requirements for.

**Comment by godmode** [comment] 2019-02-13 15:01
That does sound familiar but I’m not sure either.

**Comment by Drognand** [comment] 2019-02-13 15:34
i tho have not noticed the same thing happening with shield or block tho. I get what your saying i was just wanting to be safe then sorry as i remember the way skills were back in the "old days" lol

**Comment by Setz0r** [comment] 2019-02-21 22:30
It looks like a 2012 update made it so that you do not have to have parry proc in order to gain a skillup for it.

**Comment by SBC-Nyxai** [comment] 2019-06-18 22:25
I was going to make a bug report saying that shadows are sometimes still consumed when parrying until I saw this issue. If you reference https://www.twitch.tv/videos/440839078?t=02h08m34s and watch there are two times where I get a parry skillup and a shadow is still consumed within about 20 seconds. Not sure if this is an issue with shadows being consumed on parry or if this is the issue where parry is being skilled up without it activating as this issue addresses.

**Comment by E5una** [comment] 2020-04-24 15:56
What's the status of this ticket? I've heard people mention that they are skilling up their parry much faster than on retail, and this 2012 update cited by setzor seems to the cause. It sounds like Shield skill ups only happen when your shield procs, but parry skill ups can happen whenever you are attacked.

**Comment by 59blargedy** [comment] 2021-10-04 15:23
resolved with parry changes a few updates ago, and fully resolved with October 4, 2021 update

**Closed by 59blargedy** 2021-10-04 15:23 UTC
Labels: Combat
