### ISSUE TITLE
SMN pet doesn't despawn on death

### ISSUE THREAD

**Issue by maeinit** [EdenServer/community#644] opened 2019-01-01 21:44 UTC
While leveling I got foot kicked for 52 damage by a Savanna Rarab. Needless to say I got one shoted at that level on SMN, but after I died Carbuncle stayed out and kept attacking until the rarab was dead(or until it probably died itself). I'm pretty sure avatars are suppose to despawn when the SMN dies.

https://gyazo.com/ef7b247eb3f38a75b7b0b670bae6d24f
![image](https://user-images.githubusercontent.com/12605529/50576649-3af27080-0dcb-11e9-809b-a9a7b1b955d2.png)

https://gyazo.com/5a01013d3d312de894885247a268c84a
![image](https://user-images.githubusercontent.com/12605529/50576652-43e34200-0dcb-11e9-86a2-7b88d64db78b.png)

**Comment by godmode** [comment] 2019-01-03 03:33
Duplicate of #124

**Closed by godmode** 2019-01-03 03:33 UTC
