### ISSUE TITLE
Bugged at Wall of Dark Arts

### ISSUE THREAD

**Issue by Riphook** [EdenServer/community#796] opened 2019-01-19 20:35 UTC
Had aggro, click the wall of dark arts in Davoi ( yes I have key item and it worked later ) while I had aggro and it made me get stuck in the cutscene for getting through the wall of dark arts.

https://youtu.be/9szfzkWxjXU

Video of it happening after I was stuck...would have started video sooner but had no reason to :P

**Comment by starnack** [comment] 2019-02-26 00:34
Had the same issue happen today, even with carbuncle on the add, it still bugged and left me for dead.

**Comment by setsuk0** [comment] 2019-03-20 00:06
This just happened to me. I clicked on the wall of dark arts and got aggro. My screen went black but never let me through the wall. It also did not give me the message to homepoint once I finally died, so I'm just stuck staring at a black screen.

**Comment by KnowOne134** [comment] 2020-05-14 21:41
Closing as issue is duplicate of 
https://github.com/EdenServer/community/issues/460

**Closed by KnowOne134** 2020-05-14 21:41 UTC
