### ISSUE TITLE
BLU merit trait Assimilation not functional

### ISSUE THREAD

**Issue by icariumkupo** [EdenServer/community#1707] opened 2019-05-27 20:15 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

/ver 30181205_0 

BLU merit trait Assimilation has no effect. With 1 point in this ability, BLU magic points remains capped at 45.

**Comment by Serephim** [comment] 2020-04-24 18:08
I just went 3/3 in this and I got 0 extra Blue Magic points. :(
FeelsBadMan

**Comment by KnowOne134** [comment] 2020-04-24 18:17
Duplicate
https://github.com/EdenServer/community/issues/1707

**Comment by Serephim** [comment] 2020-04-24 18:51
This is a duplicate of itself? lol

**Comment by KnowOne134** [comment] 2020-04-24 18:53
Haha. I read it as a new issue and did a search search

**Comment by Serephim** [comment] 2020-04-24 18:54
Ah, yeah I just wanted to give a second confirmation that this was indeed broken.
Even at 2/3 and 3/3.

**Comment by KnowOne134** [comment] 2020-04-24 19:03
A issue I've seen many try and give up on fixing

**Comment by Serephim** [comment] 2020-04-24 19:05
That sucks. :(
Any chance of me getting the 12 merit points refunded then if this will never get fixed? XD

**Comment by KnowOne134** [comment] 2020-04-24 19:10
Would have to ask a gm idk via ticket system

**Comment by Serephim** [comment] 2020-04-24 19:12
Cool will do.

**Comment by Caelic** [comment] 2020-05-08 00:09
menu_merit.cpp

As it turns out, offset 0x0A is a uint16, not a uint8. This section
```cpp
ref<uint8>(0x0A) = PChar->PMeritPoints->GetMeritPoints();

	uint8 flag = 0x00;

	if (PChar->jobs.job[PChar->GetMJob()] >= 75 && charutils::hasKeyItem(PChar, 606))			// keyitem Limit Breaker
	{
		flag |= 0x20;
		if (PChar->MeritMode)
		{
			flag |= 0x80;
		}
	}

	//capped EXP
	if ((PChar->jobs.job[PChar->GetMJob()] >= PChar->jobs.genkai && PChar->jobs.exp[PChar->GetMJob()] == charutils::GetExpNEXTLevel(PChar->jobs.job[PChar->GetMJob()]) - 1) 
		|| PChar->MeritMode)
	{
		flag |= 0x40;
	}

	ref<uint8>(0x0B) = flag;```
I changed to
```cpp
uint16 bits = 0;
    bits += PChar->PMeritPoints->GetMeritPoints()                                & 0b0000000001111111; // first seven bits are merit points
    if (PChar->GetMJob() == JOB_BLU && PChar->GetMLevel() > 74)
    bits += (PChar->PMeritPoints->GetMeritValue(MERIT_ASSIMILATION, PChar) << 7) & 0b0001111110000000; // next six bits are assimilation points. the last three bits are the three flags below:
    bits += (PChar->jobs.job[PChar->GetMJob()] >= 75 && charutils::hasKeyItem(PChar, 606)) << 13;      // is 75 and has limit breaker KI
    bits += ((PChar->jobs.job[PChar->GetMJob()] >= PChar->jobs.genkai && PChar->jobs.exp[PChar->GetMJob()] == charutils::GetExpNEXTLevel(PChar->jobs.job[PChar->GetMJob()]) - 1) || PChar->MeritMode) << 14; // my exp is capped
    bits += (bits & (1 << 13) && PChar->MeritMode) << 15; // flag 13 is set and merit mode is on
    ref<uint16>(0x0A) = bits;```
did lots of testing and it works perfectly. HUUUUUUUUUUUUUUUUGE credit and thanks to Devi Letti posting information yesterday on why this was not working. Jimmay copied what he wrote into the festivus channel on the Eden discord including decompiled client code which enabled me to fix this.

Somewhat related but if you guys ever start working on Ballista, there is another similar issue in the packet that handles nameflags where a piece of data is being treated as a uint8 where it's actually a uint16 so hit me up if you run into issues with enabling the PVP flag if Ballista ever gets worked on here on Eden.

**Closed** 2020-05-23 13:16 UTC
