### ISSUE TITLE
NPC Jajaroon selling Dragoon Die and Puppemaster Die for swapped prices

### ISSUE THREAD

**Issue by CaptainThief** [EdenServer/community#5733] opened 2023-08-21 03:04 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

My friend went to go buy me Dragoon Die in Nashmau and noticed the price seemed a bit steep for a level 23 die, and also that the level 52 Puppetmaster Die seemed a bit cheap. Upon checking the classic wiki at https://classicffxi.fandom.com/wiki/Jajaroon it was confirmed that Dragoon Die is being sold for 82,500 gil like PUP should be, and PUP's is being sold for 9,216 like DRG should be. Just talk to Jajaroon to confirm these prices.

Ashita version 3.1.1.9 Interface 3.000000
![Dragoon Die issue Eden XI](https://github.com/EdenServer/community/assets/142765512/dd929bb6-66a0-45cf-ba80-b958e1b929cf)
![Jajaroon Classic Wiki Eden XI](https://github.com/EdenServer/community/assets/142765512/e133f161-1de5-43db-91f5-f0727794c48c)

Thanks!

**Comment by falzum** [comment] 2023-08-21 09:24
Not a bug. Your friend needs the new dats released with last updated.

The dice levels are swapped in era.

https://github.com/EdenServer/Eden-Client_DATs

**Comment by falzum** [comment] 2023-08-21 09:25
Unless of course your friend has the updated files, and the npc still has jacked prices. Then it is wrong

**Closed** 2023-08-22 00:58 UTC
