### ISSUE TITLE
Mass Audit of Lottery NM PH respawn rates and pop chances

### ISSUE THREAD

**Issue by burkewitz** [EdenServer/community#1636] opened 2019-05-11 18:35 UTC
### Checklist

- [ x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

After looking at several bug reports (most recently that which involved the eastern shadow), personal experience, and player testimony, I formally request to perform mass audit of all lottery NM respawn times and pop chances.

From my experience, for the limited number of NM’s I’ve personally camped, and from player testimonies I’ve gathered, there is a large disparity between average pop times of various NM’s and era accurate retail testimonies. This is primarily due the blanket chance for pop given to the vast majority of lotto NM’s (10% for 16 min respawns, 5% for 5 minute), regardless of the number of PH’s are present for a given NM. This results in incredibly predictable and relatively fast pops for NM’s such as Huu Mjuu (which has 6 PH’s at 5 min respawns all set at 5% pop chance, per base DSP) (I’ve never waited more than an hour after ToD to repop him, despite retail testimonials stating that it can take up to 6 hours to pop), while single PH 16 min @ 10% have closer to what seems like era accurate retail pop windows (the majority of retail testimonials taking up to 8, and assuming perfect 1 hit kills on spawn at pop resulting in ~97% chance to pop by then) (a problem I assume was corrected by the recent Eastern/Western shadows ticket).

Part of these large disparities is due in large part to assumptions made by base DSP that “good enough is good enough”. The other part is that a properly working PH system isn’t in place, which I understand is in the works, and would likely solve the disparity. Regardless, a mass audit can be performed now, and would be necessary to adjust pop chance when a properly working PH system is in place. With the system that is in place now, a properly audited pop chance would result in retail accurate observable pop windows.

I am volunteering to go zone by zone, and if this is something worth pursuing, can provide a couple zones worth I’ve already done, with references used, corrected pop chances for current system, and pop chances for a properly working system (where DSP would select one PH on NM death and use that single PH to calculate pop for the next spawn), and the formulas used for either for future proofing.

I appreciate your consideration on this matter.

**Comment by Enignite** [comment] 2019-05-12 14:37
In addition the timer until window for lotto NMs reopens could be looked at as well, for instance Demonic Tiphia says:

> Window opens as early as 120 minutes after its last Time of Death, but is highly unlikely to spawn early. Frequently witnessed to spawn as many as 8 hours after its last Time of Death.

And someone on DSP took this to mean that windows reopens 2~8hr after ToD, when it obviously means that it opens after 2hr, but can take many hours of killing PHs to spawn if unlucky. Because there's no way of telling if a NM window is open this more or less means that all NMs with this randomised window reopen after the maximum amount of time has past.


We should be careful with trying to make certain spawn rates retail accurate if it means lowering them even further, I feel that some NM chances are already too low for the level of gear/rate that they drop them at, for instance Beadeaux drops have barely been on the AH over last few months because they are single PH at 5% every 5min with ~15% drop rates and hardly worth the time to camp for low/mid level gear you'd end up replacing. And when they were finally sold again they all massively jumped in price, just not by enough for people to start actively camping (unlike say Mary's Horn which jumped from 5k to 120k and is a core BRD instrument). Another case is that Enkelados Bracelets are almost never sold because the NM can take 3hr+ and not even pop, all for a 5% chance. 

Even if this is somewhat retail accurate in spawn rate (someone complains about taking 5hr then 12hr to pop Enky) what isn't retail accurate is the fact that there is no market for these items.

**Comment by godmode** [comment] 2019-05-12 14:49
Many things are different on Eden than base DSP. Please provide specific titles and reproduceable steps for bug reports. If this is a general concern/awareness post please post it on the forums in the development section. Several NMs have adjusted pop and respawn times. Closing this as it is not specific.

**Closed by godmode** 2019-05-12 14:49 UTC
