### ISSUE TITLE
Seaboard Vulture Double Attacking

### ISSUE THREAD

**Issue by Cheezcakee** [EdenServer/community#120] opened 2018-10-09 22:11 UTC
Seaboard Vulture are double attacking like the gigas and orcs that shouldn't be.

**Comment by Aneyus** [comment] 2018-10-10 02:32
Possibly related to #48 & #44 ?

**Comment by godmode** [comment] 2018-10-12 00:35
Duplicate of #44

**Closed by godmode** 2018-10-12 00:35 UTC
