### ISSUE TITLE
Character stuck under East Ronfaure

### ISSUE THREAD

**Issue by Gulluul** [EdenServer/community#1490] opened 2019-04-07 13:44 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

I was walking into West Ronfaure from South San D'oria. My game got stuck in the downloading screen so I exited the game. Upon reentering the game, my character was below West Ronfaure and unable to walk.

![Gulluul_2019 04 07_092743](https://user-images.githubusercontent.com/49367703/55684522-a3e10b80-5919-11e9-9f17-d28466f1dcad.png)
![Gulluul_2019 04 07_092754](https://user-images.githubusercontent.com/49367703/55684523-a6dbfc00-5919-11e9-849c-d79ed89a598d.png)

**Comment by Shoruto** [comment] 2019-04-07 13:46
First question - Are you able to type in game and access the menu?  If so have you submitted a GM ticket?

**Comment by Gulluul** [comment] 2019-04-07 13:47
yes, submitted a GM ticket. Just wanted to report the bug

**Comment by Far-The-Killer** [comment] 2019-04-07 13:48
Please provide the client version.

**Comment by Gulluul** [comment] 2019-04-07 13:48
Version 30181205_0

**Comment by godmode** [comment] 2019-04-07 14:27
Duplicate of #392

**Comment by godmode** [comment] 2019-04-07 14:28
No worries about posting this. The original report was not descriptive. I changed the title of it so that people can search for it easier. Thanks for reporting.

**Closed by godmode** 2019-04-07 14:27 UTC
