### ISSUE TITLE
Copper Quadavs running ultra speed. Quadavs going through walls, linking a mile away.

### ISSUE THREAD

**Issue by Novadragon-Siren** [EdenServer/community#548] opened 2018-12-20 23:11 UTC
Palborough Mines from my stream clip. This makes it EXTREMELY difficult to even get a chest key to unlock Kazham.

https://clips.twitch.tv/SneakyPoliteStorkKreygasm

**Comment by Nyoomy** [comment] 2018-12-22 09:44
If you look at the clip - the top right corner is showing that you're loading the zone in, once that finishes the Quadavs start darting to you - the ones behind the wall run through the wall to catch up to where they were in real time. If someone was watching from an outside source, I'd wager they'd be seeing the Quadavs running around the wall like normal. I don't think this is a bug with Eden, just a quirk of the game itself - a similar thing happens with retail but the mobs just warp to their current locations instead of running through walls to catch up.

**Comment by Novadragon-Siren** [comment] 2018-12-22 13:15
I mean, you can take a look for yourself. I'm running SSD on FFXI, getting any load is ultra fast. Got rid of Old Quadav once, pulled a Copper, and others ran to me insanely fast.

**Comment by Nyoomy** [comment] 2018-12-22 15:58
I'm watching the clip again and I'm still seeing it. As soon as the loading icon disappears at the top right of the screen is when the Quadavs start moving on your screen, but you're able to get aggro before you've personally loaded into the zone. I assume it's a network problem rather than loading the game itself, even with a great internet connection, going from EU to NA takes a bit longer to load stuff in.

But yeah - Palborough Mines is a pain to solo in because sound linking is a pita.

**Comment by godmode** [comment] 2018-12-22 20:06
Duplicate of #193

**Closed by godmode** 2018-12-22 20:06 UTC
