### ISSUE TITLE
Excessively low dig accuracy.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#142] opened 2018-10-11 15:27 UTC
LQM (48%), no weather in Western Altepa at Initiate rank. Screenshot below is the norm, not an outlier.

This run: 
Bigs - 20/240 (8.33%)
Lils - 22/240 (9.17%)

https://i.gyazo.com/thumb/1000/d194772bf0873417eb9a926a5f60672f-jpg.jpg

**Comment by chlorr** [comment] 2018-10-11 21:03
Not sure, but according to wiki, 50%~ moon is the worst time to dig. and I have personally noticed a difference with varying phases. Not too sure if its just our ranks are too low still or digging isn't 100% optimal yet. but I also have had a few trips end up like this and its very disheartening.

 Really puts ele staves up in price. cause there is no new Ele ore atm from bc's or digging (rank 9+ on retail) but thats a few months of work if not more to maaaaaaybe get ele ore.

Close to rank 3, then i will be keeping notes, instead of rough estimating my total stacks

**Comment by Lilswitche** [comment] 2018-10-11 21:12
I got the impression as well that weather automatically increases the dig accuracy as a result of having chances to get crystals.  

On the subject of Elemental Ores: there's plenty of posts out there and evidence that A20 (Adept) is the first rank that you can pull up Ele Ores, and not Veteran.  Although the frequency at the Adept rank is much lower.

**Comment by gweivyth** [comment] 2018-10-12 21:54
Big and I talked about this a little bit in /tells already, but I observed a pretty similar set of results.  

I fear that we're going to have a gigantic problem very soon, there are only really 4 active diggers that I know of (us three and Xaver) and that means elemental ores are going to be extremely bottlenecked, so much so that unless Gardening is coming VERY soon, we might not be able to take on any new players simply because getting elemental staves for them will be LITERALLY impossible, and at the very least they NEED Dark Staff after 51.  

As far as actual digging results, moon phase seems like it might be WAY too particular.  If you're in a bad moon phase, you can go 80+ digs without digging up anything, which is absoslutely preopsterious.  You should be able to pull up items still, but it shouldn't be NOTHING.  In retail I remember people mentioning that digging in off-moon phase times would yield more junk (common items) and the reason people really dug during those times was to level up, while digging during good moon phases was for profit.  

That would be fine, I'm okay digging up a bunch of Lauan Logs and stuff, but to dig for over an hour and get nothing out of it makes me not want to do it at all.

**Comment by chlorr** [comment] 2018-10-12 22:09
^ i couldn't have put it better myself

**Comment by Wiggo32** [comment] 2018-10-14 05:31
Hey guys! FWIW, my 2 cents on digging is that it is working as intended. Pretty close to retail standard without the nuisance of having "dig fatigue". It is a system designed to reward those who have put in the required time and effort necessary to achieve the ranks that return the most profit (as is retail). An A50 digger just won't have as high a dig accuracy as an A20 digger (as is retail).  It's true digging relies on Moon Phase, you can either be digging for profit or digging for skill (as is retail). Though, even higher ranking diggers will still come up with decent items on off moon phases, it's a just reward for achieving the rank (as is retail). Now, you're probably right in that the *AMOUNT* of items achieved on an off moon phase isn't exactly retail spec. So, if that's the main concern, I would probably suggest opening a discussion on the forums and see if the community might have any input or voice to make changes to that aspect. Though, keep in mind that while an increase in "junk" or "low level" items as they are sometimes referred to during off moon phases might mean something like implementing dig fatigue to rebalance that out. I don't really know, as I'm just speculating on possible outcomes. As far as I'm told there are more than just 4 active diggers currently on this server with some of them achieving impressive results. In my honest opinion, I personally feel those people should be rewarded for their efforts. I've read reports of Veteran Rank diggers being able to pull as many as 10 ores out during a dig cycle (as is retail). And they would deserve every one. So, with that, I'm most likely going to request that GM close this issue as it's not really an issue and maybe move this over to a "discussion" on QoL improvements. Thanks for listening.

**Comment by gweivyth** [comment] 2018-10-15 04:15
Well on the info provided about digging it mentions that bad moon phases can reduce dig accuracy by up to 50%, but we've been seeing results that just don't seem to match up with that. Earlier in Yuhtunga during 55% waning, I went 64 digs without pulling up anything at rank 2. During a good moon phase I was going 1/5 on average. The math just doesn't seem to add up, unless there is something we aren't taking into account/don't know about.

I didn't mean anything I said here as a personal attack obviously, all we have to go on is our own observations and those seem to line up pretty well. As for there being more than 4 active diggers, idk how that could be.  The server isn't very big, we would have bumped into each other by now, and it's easy to see who is digging by finding who is selling Coral and Philo Stones.

**Closed** 2018-11-29 00:07 UTC
Labels: wontfix
