### ISSUE TITLE
Mog Wardrobe 2 not functional at rank 6 Bastok

### ISSUE THREAD

**Issue by Umarusuzy** [EdenServer/community#1160] opened 2019-03-01 23:38 UTC
Ticket #996 can be referenced for the same issue.  I'm currently rank 6 Bastok.  Wardrobe 2 isn't functional on my character Umaruchan.

**Comment by godmode** [comment] 2019-03-01 23:38
Duplicate of #996

**Closed by godmode** 2019-03-01 23:38 UTC

**Comment by BuffaloOnEden** [comment] 2019-03-01 23:42
Mine doesn't work either. Character name is Buffalo.

**Comment by godmode** [comment] 2019-03-01 23:45
This ticket is closed please write it on the original ticket that was linked to. #996
