### ISSUE TITLE
Enemies Aggro through the floor in Beadeaux

### ISSUE THREAD

**Issue by Orangemenace** [EdenServer/community#2873] opened 2020-05-20 05:08 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
In E-11/F-11 in Beadeaux (at the very least in that section), the enemies aggroed and walked up through the floor to come attack us when we had no aggro until that point. We were not sneaked but none of the enemies on the upper floor were in range to detect us and the ones below aggroed and walked up through the floor to attack.

Client Version 30181205_0

**Comment by Volkaru** [comment] 2020-05-20 15:01
Please search for previous bugs before making a new one. 
Duplicate of #193 , #338 , #665 , #801 , and various other Navmesh related bugs. Will be fixed with the eventual Navmesh rewrite.

**Closed by Volkaru** 2020-05-20 15:01 UTC
Labels: navmesh
