### ISSUE TITLE
Gallant's Roll has out of era effect

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#2961] opened 2020-06-09 08:59 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Gallant's Roll is currently giving a percentage boost to Defense instead of its era effect of damage reflection.

Changed in 2012:
[https://forum.square-enix.com/ffxi/threads/19789-dev1069-Corsair-Job-Adjustments?p=264442&highlight=phantom+roll#post264442](url)

**Comment by VirtuosusFFXI** [comment] 2020-06-09 09:02
The link I posted my provide some insight into some other rolls potentially having incorrect values or effects as well.

**Comment by Slamm21** [comment] 2020-06-09 10:24
Duplicate of https://github.com/EdenServer/community/issues/1566

**Closed** 2020-06-09 12:48 UTC
