### ISSUE TITLE
Physical mobskills don't interrupt spellcasts.

### ISSUE THREAD

**Issue by Lilswitche** [EdenServer/community#2774] opened 2020-05-01 15:11 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

As the title says: all physical mobskills (excluding mobskills that displace their target) do not currently have a chance to interrupt spellcasts like Utsusemi.  ie. Foot kick, Stomping, Battle Dance, Slam Dunk, etc.

It should be noted there are some physical knockback abilities that, as far as I know, don't ever have chances to interrupt spellcasts innately such as Goblin Rush.  For those mobskills that displace the target, the interruption happens as a result of moving the target away from their original cast location and as such, a player could move back to the original cast location and get their spell to cast.

**Comment by Shoruto** [comment] 2020-11-06 12:48
Duplicate of #861 If you have any additional information you can add to the original report.

**Closed by Shoruto** 2020-11-06 12:48 UTC
Labels: Combat
