### ISSUE TITLE
Cannot Cast Herb Pastoral

### ISSUE THREAD

**Issue by Jamini** [EdenServer/community#1346] opened 2019-03-20 18:48 UTC
Level 18BRD/WHM cannot Cast Herb Pastoral.

I am capable of using the Herb Pastoral scroll, but when I attempt to cast the song I get the following message in chat/echo.

[charname] cannot cast Herb Pastoral

I am able to replicate this with every form of spellcasting. Via menu or /ma "Herb Pastoral" < me>

Tested on Character: Jamini

**Comment by Hariel5** [comment] 2019-04-10 05:43
Level 9 brd/whm and i've the same issue; learned the song but can't cast it.

**Comment by Yaoyorozu95** [comment] 2019-05-04 17:35
Hello everyone!
I also have not been able to cast it either, giving me the same issue as you both.
Maybe its an out of era spell?
I mean it IS only poison resistance but would be nice to be able to use it if I learned it.
 - Yaoyorozu

**Comment by Volkaru** [comment] 2019-05-04 19:22
Duplicate of #1356 .
None of the bard resistance songs are currently working (other than carols.)

**Comment by Yaoyorozu95** [comment] 2019-05-05 00:14
> Duplicate of #1356 .
> None of the bard resistance songs are currently working (other than carols.)

So what do they do with this info? If anything at all. Im sure there are priorities, but will it eventually get put in?

**Comment by 59blargedy** [comment] 2020-11-03 16:29
going to keep this all under #1356 as a blanket issue for bard resistance songs, which will eventually be put in.

**Closed by 59blargedy** 2020-11-03 16:29 UTC
Labels: needs-implemented
