### ISSUE TITLE
Pebbles and Darts delay is broken 

### ISSUE THREAD

**Issue by mrsidewinder** [EdenServer/community#3244] opened 2020-09-08 16:41 UTC
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ x ] I have provided my client version in the details. (type /ver into your game window)

When u cast pebbles an darts since sunday patch they are 10 seconds delay. I clocked them. 

I dont have many ERA data but i guess they shouldnt be longer(2x) than gun to shoot.

Please fix them

U may /equip ammo "pebble"
And use /ra <t> to test it

Thank you

Version 30181205_0

**Comment by Wannaspoon** [comment] 2020-09-08 20:20
duplicate of #3238

**Comment by 59blargedy** [comment] 2020-09-20 18:26
resolved w/ september 20 update

**Closed by 59blargedy** 2020-09-20 18:26 UTC
Labels: in-code-review
