### ISSUE TITLE
Elemental Seal - Resists

### ISSUE THREAD

**Issue by panfunk** [EdenServer/community#2058] opened 2019-09-21 06:15 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Elemental Seal does not add 'enough' magic accuracy.
During our last Cerberus encounter, we used ES+Elegy 4 times, and it was resisted twice.
Also saw several ES+Elegy resists on Khimaira, and some ES+Sleep resists on Fafnir.

While I'm not sure if ES makes spells land 100% of the time, I'm certain that 2/4 is extremely unlikely on retail. I can't remember any instance where ES failed on retail, but it's been a long time.

Iirc, for stuff like Fafnir that build resistance to sleep, ES+Sleep would still land, but only last for a few seconds if resistance was built prior.

If anyone has some memory of ES+Elegy resists from retail, please comment, since I'm not sure if this ever happened.

There are several bug reports concerning magic accuracy, but I haven't seen one specifically about Elemental Seal.

**Comment by beauxq** [comment] 2019-09-21 12:04
From what I remember, elemental seal should make 100% no resist unless the target is immune. The main place I might think there's an exception to that is NMs that build resistance to a certain spell over a fight.

**Comment by Raphtalia1** [comment] 2019-09-21 14:31
From what I recall ES makes the next spell extremely accurate but not 100%, there always seemed to be a (very small) chance to resist it, but this normally manifested in a partial resist rather than a full resist (1/2 1/4 1/8 etc) generally speaking you should see nearly no resists from both elemental seal and magic burst if your skill and lvl are appropriate for the content.

On retail a lvl 65 rdm/blm ele seal slowing fafnir would probably only stick for a handful of seconds, and not even land without ele seal. A 75 rdm/blm could count on ele seal to have full or near full duration unless the fight had gone on far longer than it should have

**Comment by everlast101069** [comment] 2019-09-21 17:25
Assuming proper gear for the content you are using ES with it is very accurate. On retail even with the amount of stat vomit now it made spells land that normally wouldn't but it does get resisted. According to this its a 265 magic accuracy boost.
https://www.bg-wiki.com/bg/Elemental_Seal

**Comment by Slamm21** [comment] 2019-09-22 22:28
256 magic accuracy boost would increase your magic hit rate by a minimum of 128%, so basically it should increase it to 95% unless you are so low that you are currently just floored at 5%.

**Comment by Oyaziiiiiii** [comment] 2019-09-23 20:47
I don't remember there ever being a resist with ES unless the mob had some form of innate resistance or unless it was a special instance where SE made mobs build resist over time(sleep on Fafnir/tiamat). You couldn't do stuff like sleep undead with dark based sleep or bind an ice elemental, even with ES. We even had underlvled brd/blm sometimes for khim and cerb and they landed np.

**Comment by Slamm21** [comment] 2019-09-23 22:12
that's because of how high the boost is.
256 magic accuracy will boost your hit rate from 128% at a minimum up to a maximum of 256% depending on your dint/dmnd.
Essentially unless you are mad gimp you will cap 95% magic hit rate with ES unless the mob is immune or has incredible high resistance to the spell.

**Comment by perkuprightmeow** [comment] 2019-09-24 14:27
Just wanted to contribute that I had Vivian resist an Elemental Seal > Sleep II last night on RDM. Really odd for something that's supposed to be resistant but not immune?

**Comment by Slamm21** [comment] 2019-09-24 15:04
5% chance of that happening on retail.

**Comment by perkuprightmeow** [comment] 2019-09-24 16:15
Ooo, each time? My luck knows no bounds.

**Comment by Slamm21** [comment] 2019-09-24 16:37
Yes each time. Your magic hit rate will always range between 5% and 95% unless the mob is immune.

**Comment by Mikokiko** [comment] 2019-09-27 13:47
Fully merited blm, with all HQ gear, with a complete enfeebling set.

Elemental seal + Sleep II on Fafnir = always get resisted, I do it to see if it will ever land, never had it happen.

In dynamis Elemental seal + Freeze II on a statu can get resist. (Aquilo by itself is +10 ele and 5 int)

Something is wrong with how Elemental seal work on here.  I recall never getting resisted on ERA on my geared BLM. I also recall being able to sleep fafnir as a BLM. 

It's one thing to go by saying " oh but there's a 5% chance it get resist because database said so" To people reporting it's just not working. 

Here it's a case where ES is not working properly. Specially when nin/drk can land sleep on fafnir about 80% of the time when they spam it for aggro purpose. Something is off and needs to be looked into.

**Comment by Slamm21** [comment] 2019-09-27 14:00
No one here ever said this report is incorrect, it was just clarified that elemental seal will still leave you a 5% chance of a spell being resisted. It does sound like ES is not giving the +256 magic accuracy.

**Comment by Oyaziiiiiii** [comment] 2019-09-28 20:16
> No one here ever said this report is incorrect, it was just clarified that elemental seal will still leave you a 5% chance of a spell being resisted. It does sound like ES is not giving the +256 magic accuracy.

I don't recall it ever getting resisted on Khim/Cerberus, not even once. And we fought them a lot.

**Comment by Slamm21** [comment] 2019-09-28 23:08
It still does, just like accuracy caps at 95%, so does magic hit rate.

**Comment by beauxq** [comment] 2019-09-29 13:23
Magic accuracy is not the same as melee accuracy because there are partial resists.
With capped magic accuracy, the probability of getting a full resist (of getting the "XXX resists" message with sleep) is only 1%, not 5%.
The other 4% is for partial resists.

So if perkuprightmeow and Mikokiko are talking about getting "...Vivian resists..." or "Fafnir resists...", that should not be a 5% chance, that should only be a 1% chance.

**Comment by Slamm21** [comment] 2019-09-29 13:43
You would roll twice for sleep, 95% chance of a 60 second and if not it rolls again 95% for a 30 second so it still can resist but a very low chance 0.025%. low but entirely possible.

**Comment by Mikokiko** [comment] 2019-09-29 13:54
> Magic accuracy is not the same as melee accuracy because there are partial resists.
> With capped magic accuracy, the probability of getting a full resist (of getting the "XXX resists" message with sleep) is only 1%, not 5%.
> The other 4% is for partial resists.
> 
> So if perkuprightmeow and Mikokiko are talking about getting "...Vivian resists..." or "Fafnir resists...", that should not be a 5% chance, that should only be a 1% chance.

Yes, wich is my point, right now it's resisting way too much and not working as intended. I have never landed a ES sleep II on Fafnir, despite how geared my blm is, wich make no sence at all. This was just to bring a point on how broken it is. Saying there a chance to resist is one thing, but it being 100% resisted is another.

**Comment by Oyaziiiiiii** [comment] 2019-10-01 23:48
I read through a bunch of old BG threads and experiments people ran back in the day and my conclusion is that the 95% magic accuracy cap refers to full duration of the spell. The other 5% is comprised of partial resists and in extremely rare cases, a full resist. 

https://www.bluegartr.com/threads/57252-Elemental-Seal-Question
https://www.bluegartr.com/threads/79076-Fully-meritted-Focalization-vs-Elemental-Seal
https://www.bluegartr.com/threads/78828-MACC-Debate-(From-Random-Thread)
https://robonosto.blogspot.com/search/label/magic%20accuracy
https://www.bluegartr.com/threads/83846-Extensive-Paralyze-I-Testing

>You would roll twice for sleep, 95% chance of a 60 second and if not it rolls again 95% for a 30 second so it still can full resist but a very low chance 0.025%. low but entirely possible.

This is correct. I think it was a terminology thing before. After reading through the threads and data, I found that most consider a "resist" as any spell that doesn't last the full duration, which includes partial resists. I thought you were saying the chance for a full resist was 1/20 which made no sense.

**Comment by Slamm21** [comment] 2019-10-02 01:19
yeah sorry for the confusion.

**Comment by ShiyoKozuki** [comment] 2019-12-11 05:41
Elemental seal isn't +100% hit rate, or even +95%.
Khim has 50% earth SDT and all wyrms have 100% dark SDT.
Dynamis statues also have 85-115% SDT to every element.

https://www.bg-wiki.com/bg/Resist#Elemental_SDT

**Comment by 59blargedy** [comment] 2021-03-01 16:23
resolved in March 1, 2021 update.

**Closed by 59blargedy** 2021-03-01 16:23 UTC
