### ISSUE TITLE
Ground King Abjurations

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#451] opened 2018-12-10 02:56 UTC
Please audit the ground king abjurations, they are dropping at much too low of a rate.

**Comment by Oyaziiiiiii** [comment] 2018-12-10 03:58
2nd abjuration. Another thing to look into maybe is why they seem to really favor one particular abjuration. Nidhogg, for example, has been heavily favoring mbody drops over the other three.

**Comment by godmode** [comment] 2018-12-10 04:08
This may be fixed on Tuesday's patch. I think it had the same issue that Jeuno did.

**Comment by kochiemonster** [comment] 2018-12-11 16:09
If fixed, can you mail a few of us some earthen bodies to make up for all the wasted time. Thx

**Comment by Treble011** [comment] 2018-12-12 00:05
I agree with Kochie. Our last 4 Nidhoggs have dropped M Body only. Refund, please. Willing to kill again!

**Comment by icariumkupo** [comment] 2018-12-12 01:20
Let's have Nidhogg pop every day for a week!

**Comment by godmode** [comment] 2018-12-14 13:46
Now that drop groups have been implemented please start a separate counter for these. They should be working as intended now but leave a comment if they are still as rare as Ridill's.

**Closed by godmode** 2018-12-14 13:46 UTC

**Comment by Oyaziiiiiii** [comment] 2019-04-20 22:50
As an update: 
Fafnir and Nidhogg still have never dropped more than one abjuration for us. Nidhogg seems to favor mbody > nlegs/abody > ebody. We've killed 15 nidhoggs since the eden launch. 

King Behemoth hasn't dropped a defending ring either in about 30 eden kills which is entirely possibly considering the low drop rate, but that might be worth looking into as well.
