### ISSUE TITLE
Slendlix Spindlethumb NM, Inner Horutoto Ruins.

### ISSUE THREAD

**Issue by Novadragon-Siren** [EdenServer/community#681] opened 2019-01-06 11:21 UTC
NM is meant to be a Goblin, but he is a mage Warlord in Inner Horutoto Ruins.

https://imgur.com/sgVkyPP

**Comment by Novadragon-Siren** [comment] 2019-01-06 11:37
Pretty sure Eden. Friend Mattyg from Kupo said he saw him as an Orc.

**Comment by jmcmorris** [comment] 2019-01-06 16:58
@godmode This would be caused by the NM having the wrong model assigned to it in the mob_pool table.

**Comment by godmode** [comment] 2019-01-06 16:58
Yep

**Comment by MGramolini** [comment] 2019-01-13 11:33
NM is out of era anyway.  But it has been this way since Kupo.

**Closed** 2019-04-10 03:49 UTC
