### ISSUE TITLE
Mob hate table not resetting after player dies & reenters a zone.

### ISSUE THREAD

**Issue by Apocalypse612** [EdenServer/community#1854] opened 2019-07-04 09:59 UTC
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Mobs are not clearing their hate table correctly after a player dies & re-enters a zone.

SCENARIO: Player A and Player B engages a mob. Player A dies, mid-fight and player B resumes the battle. Player A zones back in and runs toward the fight on the other side of the map, and before he gets there Player B dies. The Mob now has hate on player A half way across the map, and instead of returning to his spawn position and regaining HP he will begin to path toward player A.

**Comment by godmode** [comment] 2019-07-12 20:36
Duplicate of #530

**Closed by godmode** 2019-07-12 20:36 UTC
