### ISSUE TITLE
Some HuXzoi Aerns doing a Reraise animation then remaining dead on the floor. Corpses slides around like it was alive/moving. Not targetable and do not respawn.

### ISSUE THREAD

**Issue by Avarghaladion** [EdenServer/community#5921] opened 2024-07-27 21:42 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

30181205_0

HuXzoi Aerns killed yesterday in the first room on the left after entering zone did RR animation > resumed corpse-mode after animation finished > are still dead/sliding around.

**Comment by Mozzy4Ever** [comment] 2024-07-28 02:52
Duplicate of https://github.com/EdenServer/community/issues/3061

**Comment by 59blargedy** [comment] 2024-07-30 23:35
closing as duplicate

**Closed by 59blargedy** 2024-07-30 23:35 UTC
