### ISSUE TITLE
Carbuncle/Avatars don't attack aggressive mobs/Meteorite far too weak

### ISSUE THREAD

**Issue by RhysonEden** [EdenServer/community#856] opened 2019-01-26 18:40 UTC
So, in trying to fix an issue, you all created one.

Carbuncle and the avatars do not attack mobs that become aggressive towards players now.

Meteorite is now far below era value.

**Comment by godmode** [comment] 2019-01-26 20:56
Duplicate of #837

**Closed by godmode** 2019-01-26 20:56 UTC
