### ISSUE TITLE
Monastic Cavern entrance has too many orcs (see video)

### ISSUE THREAD

**Issue by hyakuzaku** [EdenServer/community#5315] opened 2022-10-12 09:25 UTC
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted.
- [X] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [X] I have provided my client version in the details. (type /ver into your game window)
- [X] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

![image](https://user-images.githubusercontent.com/65121606/195304241-88e95515-d460-44b0-9932-7c2e6c682eb2.png)

Reproducible steps:

Play on retail
Zone into Monastic Cavern from Davoi at H-12~
View the Orcs
Play on Eden
Zone into Monastic Cavern from Davoi at H-12~
View the Orcs

Video of what I'm talking about:
https://youtu.be/68wuImFzegA

The first half is retail, the second half is Eden. Retail has only 2 Orcs, where as Eden has what I feel safe describing as a "buttload" of Orcs, seeming like the someone just trained the whole zone.

**Comment by Steam-arch** [comment] 2022-10-12 09:38
Hmm, wasnt there something more behind this? Like for some reason retail era had a crazy ammount of orcs loaded.  At this momenty my memory fails me.

**Comment by E5una** [comment] 2022-10-12 10:02
This is a well known bug with duplicate bug reports (see https://github.com/EdenServer/community/issues/864 for example). The issue is that on retail mobs share spawns. It’s not trivial to fix due to ur being not trivial to understand their spawns. Eden’s approach in the past has been to do it right rather than guess at a solution, I can’t speak for devs current perspective on this but I wanted to give some insight into how this is hard to fix correctly. In rangemaunt pass for example there are BST gobs that share spawns with a Scorpion. The trouble is not only understanding the pool, but observing it in retail over a LARGE sample size to understand the distribution of spawns within the pool if they are not even. Hope that helps, and sorry to update a bug report with what is really a discord post, I just never know how to find the same people in discord.

**Comment by hyakuzaku** [comment] 2022-10-12 10:12
I mean, I get it. Getting retail accurate spawn rates etc is an insane amount of effort, however the difference here is absolutely comical and truly scary to newer players who might be doing the genkai quest. 

Zone like Rangemaunt Pass & Dangruf Wadi might never be accurate because they changed all the mobs there after 99, deleting whole spawns of things like the "Stickpin" leeches for example. 

For this I feel a reasonable compromise would be 2 orcs with and equal chance of spawning whatever jobs are of that tier. At least it's "more correct" than what is currently there.

**Comment by 59blargedy** [comment] 2023-02-20 14:37
duplicate, resolved by another dev in february 20, 2023 update

**Closed by 59blargedy** 2023-02-20 14:37 UTC
