### ISSUE TITLE
Party Flag

### ISSUE THREAD

**Issue by StriderClerix** [EdenServer/community#1171] opened 2019-03-03 00:43 UTC
Party flag sometimes stays up even while in a party. 
![clerix_2019 03 02_194128](https://user-images.githubusercontent.com/46233090/53689420-6f2ed280-3d23-11e9-9acb-403a3020aa5c.png)8

**Comment by godmode** [comment] 2019-03-15 23:00
Duplicate of #907

**Closed by godmode** 2019-03-15 23:00 UTC
