### ISSUE TITLE
Mobs Attack Through Floor in Palborough Mines

### ISSUE THREAD

**Issue by JigokunoOusama** [EdenServer/community#338] opened 2018-11-20 04:08 UTC
An Amethyst Quadav aggroed through the floor on the second floor of Palborough Mines just after Qu'Vho Deathhurler and the mushroom caves at the first Veteran Quadav spawn point.  It brought it's entire group up with it, but did not train other mobs.

**Comment by beauxq** [comment] 2018-11-20 13:13
possible duplicate of https://github.com/EdenServer/community/issues/193

**Comment by godmode** [comment] 2018-11-20 13:16
Duplicate of #193

**Closed by godmode** 2018-11-20 13:16 UTC

**Comment by JigokunoOusama** [comment] 2018-11-23 08:14
That occurred in Beaudeux; It's not even the same zone.  If you want to make the bug more general to mobs aggroing through the floor then that would prevent people like me from making duplicate bug reports.

**Comment by godmode** [comment] 2018-11-23 13:07
I think the report name of 193 is pretty generic. Are you thinking of a better name I can change it to?
