### ISSUE TITLE
Asking crafting guild members for synthesis information freezes character.

### ISSUE THREAD

**Issue by Shuu-37** [EdenServer/community#306] opened 2018-11-10 07:34 UTC
~~After speaking with Fatimah NPC in Bastok Goldsmithing guild, unable to move or do anything.~~

Speaking to a crafting guild person and asking for synthesis information freezes your character.

**Comment by chlorr** [comment] 2018-11-10 22:15
I've only experienced this when accidently asking for tips from them miss clicking instead of support. maybe that happened?

**Comment by Shuu-37** [comment] 2018-11-10 22:19
@chlorr Yep, exactly that.

**Comment by chlorr** [comment] 2018-11-10 22:20
yeah idk why it happens but can confirm you freeze when doing so

**Comment by godmode** [comment] 2019-02-16 22:04
Duplicate of #435

**Closed by godmode** 2019-02-16 22:04 UTC
