### ISSUE TITLE
Curse Machines in Bedeaux

### ISSUE THREAD

**Issue by SaberSuper** [EdenServer/community#799] opened 2019-01-19 23:58 UTC
Curse Machine in Beadeaux is cursing you from below at L-6 on the outside part of the map.  I don't believe it is suppose to curse you until you go down into the caves.  I might be wrong but i do believe this is a bug revolving around the curse machines.

**Comment by KnowOne134** [comment] 2021-07-28 01:41
duplicate of https://github.com/EdenServer/community/issues/829

**Closed by KnowOne134** 2021-07-28 01:41 UTC
Labels: navmesh
