### ISSUE TITLE
Can't Raise After Tractor in BCNM

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#693] opened 2019-01-08 02:42 UTC
This was during the ZM4 BCNM fight, don't know if that matters. Gives message "You cannot attack that target." GM had to remove those characters from the BCNM.

**Comment by godmode** [comment] 2019-01-08 11:36
Duplicate of #653

**Comment by slassen** [comment] 2020-04-04 00:00
This should not be happening anymore. Was fixed a while back. Please comment if you see the issue return.

**Closed by slassen** 2020-04-04 00:00 UTC
