### ISSUE TITLE
Incorrect Alchemy GP item

### ISSUE THREAD

**Issue by Tjonke** [EdenServer/community#1880] opened 2019-07-13 15:26 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ ] I have provided my client version in the details. (type /ver into your game window)

### Details

Today the Alchemy GP collector requested Fruit Punches for Journeyman rank, Fruit Punches are a drop from NM in Sarutabaruta and are used in the Tropical Punches synth (81 Leathercraft) and have absolutely nothing to do with Alchemy.

**Comment by godmode** [comment] 2019-07-13 17:23
Duplicate of #1875

**Closed by godmode** 2019-07-13 17:23 UTC
