### ISSUE TITLE
Bind is overpowered

### ISSUE THREAD

**Issue by tectal831** [EdenServer/community#1164] opened 2019-03-02 08:30 UTC
Bind is way too strong, especially in regards to NMs.

**Comment by roriffxi** [comment] 2019-03-02 16:08
Any details on this? In my experience bind has been a little week. It breaks on the first damage the vast vast vast majority of the time.

Is it possible there are some mobs that should be immune to it that aren't? 

There is already a lot of stuff you can't do as a blm because bind breaks too easily.

**Comment by beauxq** [comment] 2019-03-02 16:14
This is not appropriate to make an issue here like this - without some more specific information.

**Comment by tectal831** [comment] 2019-03-02 17:23
You should not be able to infinitely chain bind nms for full duration, especially hnms as I've seen done on vrtra, and on bcnms like divine might. Bind is simply too strong as it sits atm

**Comment by Oyaziiiiiii** [comment] 2019-03-02 19:19
Bind was regularly used by RDMs to solo NMs and was 100% used in Divine Might by groups using a "conventional" strategy. TBH, I can't remember ever even trying to bind vrtra on retail but there also wasn't much need for it, as it was a much easier battle there. So I can't say one way or another how much vrtra should or shouldn't resist bind. It wasn't hard to gravity/slow/para/etc him though.

**Comment by Lilswitche** [comment] 2019-03-02 19:30
On retail, bind was never been subject to decreasing duration or resistance for multiple casts.  The only such spell, other than those with specific mechanics like Khimaira with Stun, was gravity.  That spell was specifically nerfed because of how it made mobs easier to fight. ([Source](http://www.playonline.com/comnewsus/200402264502.html)

I can speak from personal experience that on retail I've solo'd numerous NMs using a bind-kite strategy and only occasionally using gravity when I got a bind resist. These consisted of NMs like Steam Cleaner, Zipacna, Faust, Ullikummi, and Seiryu.  I've also on numerous occassions spent upwards of 25mins holding NMs like Nid/KB using bind/gravity with ease.  There's videos out there of RDMs using these strategies for long periods of time specifically because Bind doesn't build resistance of any kind (Sources: [1](https://www.youtube.com/watch?v=pqTbRTZeyo4), [2](https://www.youtube.com/watch?v=mi7TOiWfcN0), [3](https://www.youtube.com/watch?v=Xo6_o8A_kKM))).  

Speaking to bind breaking when damage is done: normally on weaker mobs bind would have a greater % chance to not break on damage and on more difficult mobs it was the inverse.  It may have always been a function of PlayerLevel vs MonsterLevel.

**Comment by godmode** [comment] 2019-03-02 19:32
I believe the duration had more of a range on retail, yes?

**Comment by Lilswitche** [comment] 2019-03-02 19:44
I didn't pay much attention to the range of duration on eden because I haven't played RDM/BLM here at all myself.  On retail, if you didn't come packing with a good Enfeebling/Magic Accuracy set the range/land rate was inconsistent.

**Comment by Avestaffxi** [comment] 2019-03-02 19:53
> You should not be able to infinitely chain bind nms for full duration, especially hnms as I've seen done on vrtra

I do not think anybody ever tried to bind Vrtra.  And if you need actual video reference, there's countless kiting videos on youtube with chatlogs visible, showing zero bind attempts on Vrtra, even under 25% and with alliance members at critical health.  If anything, bind should be more sturdy and not break at the slightest dmg done. 

What's prompting this in the first place?

**Comment by Lilswitche** [comment] 2019-03-02 20:02
The issue atm with Bind is if the main target (more emnity) is out of range when bound, it should be targeting the next highest within melee range until the bind is broken.  I don't think this happens on Eden atm.  Vrtra was bindable on retail but the reason you don't see it during alliance fights is because if you bind it, it'll swing at targets nearby and if there happened to be someone that walked up behind it you risked a Spike Flail.

**Comment by Treble011** [comment] 2019-03-02 20:15
> > What's prompting this in the first place? 

Most likely because we used bind to kite Vrtra because he has absurd regain and was spamming any time anyone got close.

**Comment by tectal831** [comment] 2019-03-02 20:21
What prompted this was a conversation I had with godmode about binding mons when we did Divine Might, and in forgot to until i saw somebody yesterday bind nuking VE and it reminded me to post the bug report for godmode to look into.

**Comment by Avestaffxi** [comment] 2019-03-02 21:23
Okay but bind nuking is an intended game mechanic... and that DM video posted above was from 2006. Clearly showing all ark angels being bound while they fought one in hallway at 2:50.  Not a bug

**Comment by tectal831** [comment] 2019-03-02 21:45
Godmode understood what I was trying to say. There isnt enough range in bind times, they always land at 100% potency atm

**Comment by Strumerjohn** [comment] 2019-03-02 22:41
Are they? I feel like I've had binds not last 60 seconds before, without someone breaking, and I have like 315 enfeebling skill.

**Comment by tectal831** [comment] 2019-03-02 22:47
Its definitely worth researching, which thanks for giving us a good bit of research to comb through everyone. I may be wrong because this is all just a feeling, but it's worth at least researching and testing

**Comment by panfunk** [comment] 2019-03-04 05:14
Since I held KV in several occasions as RDM with Bind, I can confirm that like 9/10 Binds (mabye more) held for the full duration on KV, i.e. 60seconds.

**Comment by godmode** [comment] 2019-03-04 05:25
Can you specify if you meant that about retail or Eden, Pan?

**Comment by panfunk** [comment] 2019-03-04 05:27
Spoke of Eden.
I held KV on retail around 2006, but more with gravity iirc. IDR if it was because of bind resistance or something else.

**Comment by Strumerjohn** [comment] 2019-03-04 08:51
KV is a scorpion though. Since they're weak to ice, shouldn't that contribute towards a higher chance at unresisted bind? When I was binding Suzaku about a week ago I feel like almost all of my binds were partially resisted and not full duration but that makes sense since she's fire-aspected. I think we should look at statistics on unaspected mobs or those not weak or strong to ice.

**Comment by gweivyth** [comment] 2019-03-04 19:20
I did a lot of the Avesta-style soloing on retail as RDM.  Bind if definitely not working the same on Eden as it does on era retail.  On retail, Bind worked a lot closer to sneak/invis as we have it here, the duration had a range and you could end up on either end of that range, anywhere from 10 seconds up to what felt like 40 seconds.  It never seemed like a spell that had resist ranges, it just felt arbitrary and random.  (Because you saw these same ranges on things much lower level than you as well.)  It was basically good enough to get you into a situation where you could reapply Gravity or Sleep, but it wasn't supposed to be your main kiting tool like it seems to be here. 

This was just the SPELL Bind though, other binding effects seemed to have static durations.  Shadowbind in particular always seemed to have the exact same 35 seconds and it was either a hit or a miss.

**Comment by Elysien** [comment] 2019-03-04 21:26
Echoing what Gwei said, I also have a lot of experience with RDM solo and the utilization of Bind, particularly with Sky NMs like Faust and Zipacna. Bind durations could vary quite wildly on them, with even durations as low as 5 seconds. However, it seemed that repeated use in succession caused the really low end of durations. For instance I could get some pretty good duration binds consistently during the beginning, but as the fight went on I would rarely see a 20+ second bind. 

There is a patch somewhere that SE did that added gradual resistance to these spells when they were repeatedly used in succession, the resistance would deteriorate if you held off casting those spells for awhile. I'm sure with some digging you could find it, but otherwise I'm also sure there are numerous videos of a RDMs soloing the sky NMs.

**Comment by Oyaziiiiiii** [comment] 2019-03-05 22:52
Currently on Eden you either get a full resist, half duration, or full duration. I think this applies to all debuffs, not just bind. From what I've read I think there should probably be a 1/4 and 1/8 duration as well.

As for resistance building with bind, I can't find any info on it ever being added and I just went through every patch on the playonline website. I found the notes for when gravity resistance building was added, sleep resistance on certain wyrms was added, and when elemental resistances added. SE was pretty specific in their update notes so I don't think resistance building to bind is something they'd have left out. So that makes me think that it was either never actually thing, or always actually a thing. There seems to be a lot of differing opinions on the subject, both here and across the old school message boards. I can't say for sure one way or another as I didn't do any RDM soloing on retail. I'll link a bunch of stuff I've been reading through.

https://www.bluegartr.com/threads/58566
https://www.bluegartr.com/threads/59690-The-magic-resistance-patch
https://www.bluegartr.com/threads/67464-Formal-Magic-Accuracy-Testing#post2410168
https://robonosto.blogspot.com/2008/12/on-magic-resist-rates.html
http://www.playonline.com/pcd/update/ff11us/20060725vNusN1/detail.html (July 2006 magic resistance patch, no mention of bind or any other enfeebles)
http://www.playonline.com/comnewsus/200402264502.html (Feb 2004 gravity builds resistance patch)

**Comment by gweivyth** [comment] 2019-03-07 15:48
> There is a patch somewhere that SE did that added gradual resistance to these spells when they were repeatedly used in succession, the resistance would deteriorate if you held off casting those spells for awhile--it might only apply to Gravity and Sleep but I'm not sure--in any case there was certainly a range a good range on bind. I'm sure with some digging you could find it, but otherwise I'm also sure there are numerous videos of a RDMs soloing the sky NMs to give a good idea of how it looks.

Haha, it's nice to know that my memory isn't as bad as I thought!  Admittedly my memory is pretty addled by degeneracy so it's questionable at best.  Mcd posted some good source info on when the changes were applied though so maybe not much else to discuss.  

Personally I think Bind would be in a good place if we picked a range and used it as the baseline going forward.  We might never get it to be 100% retail accurate because there isn't that much data on the ranges as they were intended to be during that era, so if we could just get close I think a lot of people would find that to be an okay attempt.

**Comment by erenik** [comment] 2019-03-17 01:45
When enemies use this at low levels in Eden it is way too overpowered. From my memories it should not last too long (and have a random duration) and should break immediately on getting hit.

**Comment by Slamm21** [comment] 2019-05-29 09:18
As a RDM who used to solo various nms including some Sky Gods, I can 100% say on retail that not just bind but every single magical spell gained increased resistance on a NM when used and this was only lowered with time. This was a 2006 update you can read about here [https://www.bg-wiki.com/bg/The_History_of_Final_Fantasy_XI/2006](url)
A common strategy was to maximise the casting time between each bind and then if the mob was not immune to gravity you would switch to that for a bit while Bind resistance went back to normal.

As for whether this currently happens on Eden, eyeballing it seems like it does, but I have not done enough testing to know for sure.

Bind does not seem OP at all to me right now, on retail sometimes it would wear off in 2 seconds and sometimes stay for a very long time, sometimes 1 damage would cause it to wear and sometimes you would need to Nuke for it to wear off when it remained on after a Bio 3. It seems the same on Eden to me so far.

**Comment by 59blargedy** [comment] 2021-06-28 14:44
im closing this out as the variable portion of this is mainly resolved june 28, 2021 and the strength of bind is documented in another bug report.

**Closed by 59blargedy** 2021-06-28 14:44 UTC
Labels: Combat
