### ISSUE TITLE
Pickaxe Swinging Twice 

### ISSUE THREAD

**Issue by TheChefm** [EdenServer/community#3569] opened 2021-01-11 16:15 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [30181205_0 ] I have provided my client version in the details. (type /ver into your game window)

### Details

Use the /item pickaxe command  has the pickaxe swinging twice -  Falafel is also witness.

**Comment by rude-jerk** [comment] 2021-01-11 16:16
Duplicate of 3568

**Closed by rude-jerk** 2021-01-11 16:16 UTC
