### ISSUE TITLE
Bubble Shower hits monsters claimed by others

### ISSUE THREAD

**Issue by scorchedxi** [EdenServer/community#2963] opened 2020-06-09 14:12 UTC
### Checklist

- [x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x ] I have provided my client version in the details. (type /ver into your game window)

### Details
Bubble shower from pets hits monsters that are claimed by other people/parties. If the killing blow is dealt by Bubble shower, the loot drops to that person/party that used Bubble shower.
I did not test to see if this was jug pet specific or if it was also a problem with charmed crabs.

**Comment by Slamm21** [comment] 2020-06-09 14:21
This is a duplicate of https://github.com/EdenServer/community/issues/2823

**Closed by Slamm21** 2020-06-09 14:21 UTC
