### ISSUE TITLE
Unlisted Qualities

### ISSUE THREAD

**Issue by dantaface** [EdenServer/community#1996] opened 2019-08-30 20:44 UTC
### Checklist

- [ ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

![image](https://user-images.githubusercontent.com/27158646/64050136-21b1e780-cb45-11e9-888a-48bc5c0b1257.png)

![image](https://user-images.githubusercontent.com/27158646/64050187-3f7f4c80-cb45-11e9-94c8-93f1fb1ce28b.png)

Toon : GILFARMER

UNLISTED QUALITIES STILL BUGGED, CANNOT FINISH QUEST, NOT ABLE TO RECEIVE THE SILVER INGOT. QUEST REMAINS ON THE QUEST LIST

**Comment by KnowOne134** [comment] 2019-08-30 20:49
Fixed in Monday's patch

**Comment by godmode** [comment] 2019-08-30 23:45
Duplicate of #1971

**Closed by godmode** 2019-08-30 23:45 UTC
