### ISSUE TITLE
Ghrah hit hard.  Real hard.

### ISSUE THREAD

**Issue by danismyhero** [EdenServer/community#3483] opened 2020-12-09 02:12 UTC
### Checklist

- [ x ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ x ] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [?!] I have provided my client version in the details. (type /ver into your game window)
Ow.

https://cdn.discordapp.com/attachments/182956971668799489/786035805852139540/unknown.png

https://cdn.discordapp.com/attachments/182956971668799489/786050162748948480/unknown.png

**Comment by danismyhero** [comment] 2020-12-10 02:25
So.  This happened in dynamis:

![image](https://user-images.githubusercontent.com/49649778/101713135-a1bf4080-3a5c-11eb-8563-f5d5409615f4.png)

I am wearing this:

![image](https://user-images.githubusercontent.com/49649778/101713169-b7346a80-3a5c-11eb-99ab-dec59ba57fbf.png)

Might be an issue with the earring and not the mobs.

**Comment by tigo9** [comment] 2020-12-11 22:02
Any confirmation / investigation on this one?

**Comment by Mozzy4Ever** [comment] 2020-12-11 22:04
If there was, someone would've posted something. There's usually not replies to bugs on what's going on behind the scenes. They get closed when they get fixed for the most part.

**Comment by tigo9** [comment] 2020-12-11 22:28
More looking for confirmation to see if it is indeed a bug in the gear and therefore not worth spending seals trying to get atm.

**Comment by danismyhero** [comment] 2020-12-12 04:04
It has not happened since I removed the earring from my gearsets.  Going to re-add and see if it pops up.

**Comment by 59blargedy** [comment] 2021-01-04 15:41
am relatively sure the latent change put in today will fix the problem, but as i could never duplicate it on test i'm not 100% positive. can you please test @danismyhero and let me know on this ticket if the issue still occurs? if not i'll close in a week.

**Comment by danismyhero** [comment] 2021-01-04 21:36
Did a bunch of testing (RIP BLM exp).  The earring is working properly under the assumed conditions (<25% HP, <1000% TP).  Tested on Cactaur 1000 Needles (still hurts).  While taking hits from Ghrah earlier, at no point did I take a large, unexpected amount of damage.

**Comment by 59blargedy** [comment] 2021-01-04 23:56
gahh, sorry for your xp, but i am glad the issue appears to be resolved and the pdt is working as intended. thank you for checking! i'll close this but can comment on here if issue reoccurs and we'll try to figure it out.

**Closed by 59blargedy** 2021-01-04 23:56 UTC
Labels: Combat, Sea/Limbus
