### ISSUE TITLE
Hunter's Prelude Reduces RACC

### ISSUE THREAD

**Issue by Alamandaros** [EdenServer/community#738] opened 2019-01-12 03:29 UTC
![image](https://user-images.githubusercontent.com/46425313/51068718-8a6d4380-15f8-11e9-831e-43c4e64b1c8b.png)

Casting Hunter's Prelude will lower RACC instead of increase. Confirmed by multiple other people in my party. I've been told this is a DSP related bug and only happens at lower levels. I'm unsure as to what level it starts giving proper RACC.

**Comment by godmode** [comment] 2019-01-12 15:09
Duplicate of #519 Please comment on the original ticket if you have more details like your level, jobs et cetera.

**Closed by godmode** 2019-01-12 15:09 UTC
Labels: need-more-info
