### ISSUE TITLE
Misnamed Tonberry in Den of Rancor

### ISSUE THREAD

**Issue by kochiemonster** [EdenServer/community#678] opened 2019-01-06 04:01 UTC
There is a tonberry imprecator (blm) with a club and drops blm test.  But it is called slasher  at H-8 on map 5  i think. Right near zone back into jungle

**Comment by Caelic** [comment] 2019-01-06 19:57
Mob names can't be changed server side. They have to be fixed with .dat mods in your client.

**Comment by tectal831** [comment] 2019-01-08 05:18
Please check version update from today and try again

**Comment by Setz0r** [comment] 2019-01-18 19:14
@kochiemonster can you confirm the issue is still ongoing?  Which version of client are/were you using.

Thanks!

**Comment by kochiemonster** [comment] 2019-01-20 21:33
I'd have to get back through the gates. ><  
I was updated after latest dsp pull.

**Closed** 2019-05-09 21:27 UTC
Labels: in-code-review
