### ISSUE TITLE
"The Requiem" BRD AF quest

### ISSUE THREAD

**Issue by Matsur000** [EdenServer/community#224] opened 2018-10-24 13:19 UTC
Completed the quest up to the fight in The Eldieme Necropolis but instead of trading the holy water I examined the sarcophagi. This triggered the cut scene and gave me the key item without having to trade the water and fight the 4 NMs.

**Comment by bkesecker** [comment] 2019-02-24 22:23
Cannot reproduce.  Code history does not indicate that this was fixed in DSP since this issue was recorded.  I traced the possibility back through quest progression, and it is basically zero.  Perhaps the quest flags were goofy or this was filed mistakenly.  Even if the player DCed during certain events, Yum's death flag is required to get the key item cutscene.  Recommend closing.

**Comment by bkesecker** [comment] 2019-04-14 16:33
There seems to be a pattern emerging such that when setVar Lua is called, another setVar (either from somewhere else, or from another player) causes one of the setVar calls to fail silently.  Perhaps if setVar used a transaction, this problem may go away.  Similar to issues seen with mission 2-3's, as there are a few back-to-back calls to setVar in that code.

**Closed** 2019-04-25 22:37 UTC
Labels: event-related
