### ISSUE TITLE
Goblin Gambler aggro'd but didn't fight me in Bubu. Pen.

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2258] opened 2019-12-05 20:34 UTC
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

Here's a weird one. I was running into Buburimu Peninsula for my usual deathwarping when I came across a Goblin Gambler at (I-8).

I stood right in front of him and waited for my reaming. It never came. I had him selected and locked and just stood there for a little bit, then started running around him. He turned when I ran around, just like he would if I had aggro'd him, but he didn't attack me.

So I suspect that he did aggro to me, but for whatever reason, did absolutely nothing to me. A minute or two later, a Leecher came along and finished me off, but just thought I'd report this. ;P

**Comment by Setz0r** [comment] 2019-12-05 20:35
were you standing next to any obstacles or walls?

**Comment by Althaia** [comment] 2019-12-05 21:11
Nope, I was right in front of him, close enough to pat him on the head if I wanted to.

It was on a bit of a hill though, dunno if that counts as an obstacle...

**Comment by Setz0r** [comment] 2019-12-05 21:15
it's possible he was "under" the map and couldn't see you, but the way the game renders entities, it appeared as being on top of the map next to you, this happens with mobs that spawn on or near hills sometimes.

**Comment by Althaia** [comment] 2019-12-05 21:58
He followed me around when I turned, so it feels like he could see me XD

The leecher who killed me right next to him was definitely behaving as expected, hah.

**Comment by Oyaziiiiiii** [comment] 2019-12-06 19:05
This happened to me as well with a Soulflayer in Caedarva Mire. I even bound it and it still didn't attempt to cast on me.

**Comment by Volkaru** [comment] 2019-12-09 19:03
Also happened with a BLM Skeleton in Caedarva a few days ago to me. It just followed me and stared at me until I actually hit it. Almost like a Hpemde.

**Comment by Natakei** [comment] 2019-12-10 12:09
i've experienced similar issues with Yagudo Theologist in Giddeus, i've had several just stare at me while i slowly punched my way through all of their friends that aggro'd as normal and then watch me rest. if i happened to wander close (to punch) they would melee, but no spellcasting whatsoever. The priests and mendicants in the same area behave as intended

**Comment by Volkaru** [comment] 2019-12-10 14:50
Looks like it's only an issue with BLM mobs.

**Comment by rreina** [comment] 2019-12-10 22:34
I confirm this happened to me with a Boggy in Gusgen Mines. This was on 9th Dec, post patch.
There was a Little Rock in the way to me facing the mob, but it should have been able to attack me as I could range attack it

**Comment by ShiyoKozuki** [comment] 2019-12-11 05:09
I have seen BLM mobs aggro me and just stare at me and do nothing.

**Comment by E5una** [comment] 2020-03-16 13:38
If any devs want to clean this story up, this problem was likely resolved in the 3/8/2020 patch where mob MP regeneration was fixed outside of combat (See https://github.com/EdenServer/community/issues/2492). Previously any monster that could buff itself would run itself out of MP as long as people were staying in the zone. I'm fairly sure this "out of mp" condition in combination with spellcaster monster AI is what was causing the problem everyone reported here. Since that has been resolved, I don't think you'll see this anymore. 

To be clear, the condition shouldn't happen anymore, its not that someone specifically fixed this, were an out of MP spellcaster to aggro again.

**Comment by 59blargedy** [comment] 2021-09-17 18:24
i think through various changes to casting, pathfinding, and mp regen as mentioned above, this is no longer an issue, so closing

**Closed by 59blargedy** 2021-09-17 18:24 UTC
