### ISSUE TITLE
Automaton getting stuck on terrain.

### ISSUE THREAD

**Issue by Volkaru** [EdenServer/community#1024] opened 2019-02-17 18:33 UTC
Automatons are having issues where they're getting stuck on the terrain constantly. Sometimes in weird places. This can make it to where I have to either run 30'+ away to make them teleport beside me, or I can't get them to get in melee range when EXPing. They shouldn't be able to get stuck on anything. Automatons would always glide through objects if it'd get stuck on them in retail on the fastest path back to the master.
![volkaru_2019 02 17_082523](https://user-images.githubusercontent.com/9113384/52917377-84295180-329f-11e9-96a2-1e631545decd.png)

**Comment by Nyoomy** [comment] 2019-02-17 19:37
This is the same bug happening to all other pet classes referenced here: #438 

I'm not sure if it's been fixed for other pet jobs yet

**Comment by rujind** [comment] 2019-02-18 15:14
Yeah I am hoping to see some sort of leniency added involving pet pathing. Could be a temp fix.

**Comment by godmode** [comment] 2019-02-19 02:02
Duplicate of #438

**Closed by godmode** 2019-02-19 02:02 UTC
