### ISSUE TITLE
Blm spells and MP.

### ISSUE THREAD

**Issue by NovaDrag0n** [EdenServer/community#407] opened 2018-12-03 22:58 UTC
I'm currently Level 5 blm, have 7 MP and game states I don't have enough MP to use Stone or Water. Stone cost 4 MP and Water cost 5 mp, cannot use if I'm below 10 MP.

**Comment by NovaDrag0n** [comment] 2018-12-03 23:01
Ok might below 15 MP, Water/Stone refuses at 11 MP.

**Comment by beauxq** [comment] 2018-12-03 23:14
Duplicate of https://github.com/EdenServer/community/issues/30

**Comment by godmode** [comment] 2018-12-03 23:37
Duplicate of #30

**Closed by godmode** 2018-12-03 23:37 UTC
