### ISSUE TITLE
Hunter's Prelude not single target

### ISSUE THREAD

**Issue by ThrisStraizo** [EdenServer/community#1204] opened 2019-03-07 04:05 UTC
The song is currently an AoE hitting all party members, but it should be a single target song.

**Comment by Setz0r** [comment] 2019-03-07 04:08
on retail it was AoE during my testing

**Comment by roclm** [comment] 2019-03-07 05:16
That's a somewhat recent change on retail. I believe Etudes and Preludes might've been AoE ages ago on retail (something like 2005?) but for most of the game's lifespan, and certainly during the "era" Eden is shooting for, they were single target.
http://forum.square-enix.com/ffxi/threads/27883-dev1138-Bard-Job-Adjustments

**Comment by Setz0r** [comment] 2019-03-07 05:31
damnit @roclm making more work for us :D  thanks man

**Comment by godmode** [comment] 2019-03-07 12:06
Setzor actually has to touch the database now >:)

**Comment by setsuk0** [comment] 2019-04-06 07:30
Any chance this will be worked on soon? As a bard who hit 75 in the past week and is now doing end game, I'm finding it increasingly problematic to have rangers request prelude. Sure, you could argue to just tell them to fix their position, but this is even more difficult in dynamis/end game type of situations where I might end up in a party with various melee/ranged. Hoping this is fixed sooner rather than later since prelude hitting the correct target is more important than the crab sushi complaint I M O.

**Comment by godmode** [comment] 2019-04-06 11:01
I did the code part of it but I still need it dat modded otherwise you’ll only be able to cast prelude on yourself. Since I’m not familiar with that process it’s not going to be this week.

**Comment by Aenge** [comment] 2019-09-08 22:02
Can anyone confirm if this should be usable on alliance members as well as party members?

**Comment by setsuk0** [comment] 2019-09-09 03:44
@Aenge It should be single target and usable only on party members. Subsequently it is necessary for the BRD to be in the party with the RNG who is intended to receive the song buff. There are no songs that can be cast on members of the alliance, only within one's own party.

**Comment by Aenge** [comment] 2019-09-09 03:50
@setsuk0 Thanks. I should have a fix for this submitted sometime soon.

**Comment by godmode** [comment] 2019-09-09 11:04
Thanks, Aenge!

**Comment by Spider-Dan** [comment] 2019-09-10 07:05
The unstated factor here is the Bard job ability Pianissimo, which was implemented in the 2008/06/10 update:  http://www.playonline.com/pcd/verup/ff11us/detail/3347/detail.html

That ability (which is out-of-era for Eden) made the next AOE bard song apply only to a single target.  Later on in 2012, SE changed the single-target Etudes and Preludes back to AOE, seemingly recognizing that Pianissimo allows the caster to make the song single-target on demand.

I would suggest that that bug is more accurately phrased as "Single-target songs exhibiting out-of-era behavior," as the issue is not specific to Hunter's Prelude; it also affects Archer's Prelude, all the Etudes, and possibly the merit abilities Foe Sirvente and Adventurer's Dirge (which were also single-target prior to 2012).

**Closed** 2019-10-13 14:59 UTC
Labels: needs-dat-mod

**Comment by sukasaroth** [comment] 2019-10-13 21:45
In retail it was single target, then changed to AOE with the addition of the ability Pianissimo.
