### ISSUE TITLE
Fei'Yin Cutscenes in Entrance ( WHM AF / 5-1 )

### ISSUE THREAD

**Issue by Althaia** [EdenServer/community#2157] opened 2019-10-24 21:48 UTC
### Checklist

* [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
* [x] I have provided reproducible steps. (No "as the title says" posts please. Provide reproducible steps even if it seems like a waste of time.)
* [x] I have provided my client version in the details. (type /ver into your game window)

### Details

My client version is: Version 30181205_0

UPDATE1/Note: I understand a little bit more about what happened. The WHM AF Body quest CS was putting me on the OTHER side of the zoning point to B. Glacier... the zoning point is at the bottom of the stairs; I somehow ended up on the other side of the stairs, so every time I went down the stairs, I'd zone out.

I think Fei'Yin may be a little broken... I tried searching GitHub, nothing like this on there.

We were doing my WHM AF Body fight and I kept getting the cutscene for it at the entrance.

Every time I tried to go forward down the steps, it would zone me out, and if I went backwards, I kept going till I hit a black screen I couldn't go through (I also was off to the left to the map, not on the map any longer).

Finally, after three or four WHM cutscenes, I saw someone standing there down the steps and /follow'd them. It still zoned me out, but when I zoned back in, no more CS.

So I was finally able to get into Fei'Yin. Triggered the fight by trading the bell, got the WHM Body AF, everything else fine.

Someone else in my party kept getting the cutscene for 5-1 multiple times, never even saw the WHM AF cutscene. He tried logging out and logging back in again to no avail.

Finally, he gave up after four times of this 5-1 cutscene, but he was still able to trade the bell to the ??? point and complete the quest successfully. He never saw the WHM AF cutscene, though.

UPDATE2: A couple more of my WHM friends also got the cutscene for WHM AF today and were able to enter Fei'Yin without any problems, so I guess it's just me, weird.

**Comment by Mozzy4Ever** [comment] 2019-10-26 19:54
Pretty sure this issue (and others like it, as there are several FeiYin zone-in CS issues) are related to other missions/quests that are active on a character taking precedence over one another due to the order of the .lua 

https://github.com/DarkstarProject/darkstar/blob/fc1fcef9eb5093cc4cd5738c2da9154ec9b4be6a/scripts/zones/FeiYin/Zone.lua

WHM AF check is at the bottom of the onZoneIn check, so if you have Peace for the Spirits (RDM AF Hat), Mission 5-1 on FeiYin step, or Sandy 9-2 on FeiYin step then you'll have cutscene issues.

**Comment by 59blargedy** [comment] 2022-08-20 00:24
looking at the code my guess is this players vars just werent correct at the time, there's no quests or missions that dont move forward and allow you to obtain the next, and the positioning issue can be caused by a bad connection. im just not seeing anything that requires a code change, so closing ticket

**Closed by 59blargedy** 2022-08-20 00:24 UTC
Labels: Quest/Mission
