### ISSUE TITLE
Dia ticking for 0 damage

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#221] opened 2018-10-24 05:00 UTC
Both Dia1 and Dia2 are ticking for 0 damage. Dia3 too maybe but I don't have access to it.

http://ffxiclopedia.wikia.com/wiki/Dia
http://ffxiclopedia.wikia.com/wiki/Dia_II

**Comment by Serephim** [comment] 2018-11-01 22:30
Confirmed. I can pull mobs with Dia on BRD and lullaby them. lol

**Comment by Aelas** [comment] 2018-11-10 03:41
dia also doesn't lower defense

**Comment by beauxq** [comment] 2018-11-21 19:04
I think it would be best to apply the "fixed" label, but don't close the issue until it's compiled and running on the server.

That way it's less likely that someone will post a duplicate because they don't find it when they search open issues.

**Comment by godmode** [comment] 2018-11-21 19:12
These are linked to the private repository so when it’s merged on there it closes them automatically.

**Comment by roriffxi** [comment] 2018-12-05 21:44
This isn't fixed on the player end.  If I receive Dia from a mob, I'm not losing HP and my Defense is not reduced.

It does appear to work against mobs (they will wake immediately if I sleep them, so the dmg is ticking, and attacks do more damage).

**Closed** 2018-12-14 13:44 UTC
Labels: fixed

**Comment by Frutiebutie** [comment] 2018-12-15 17:44
Well, this is broken again, Dia and Bio both do nothing.

**Comment by godmode** [comment] 2018-12-15 18:19
Will be fixed on Tuesday’s patch. Thanks for notifying us.
